# This file created by conda-build 2.1.18
# meta.yaml template originally from:
# /recipe_root, last modified Mon Feb 19 17:20:07 2018
# ------------------------------------------------

package:
    name: ipykernel
    version: 4.8.2
source:
    fn: ipykernel-4.8.2.tar.gz
    sha256: c091449dd0fad7710ddd9c4a06e8b9e15277da306590bc07a3a1afa6b4453c8f
    url: https://pypi.io/packages/source/i/ipykernel/ipykernel-4.8.2.tar.gz
build:
    noarch: ''
    noarch_python: false
    number: '0'
    script:
        - pip install --no-deps .
        - python -m ipykernel install --prefix $PREFIX
    string: py36_0
requirements:
    build:
        - traitlets 4.3.2 py36_0
        - decorator 4.1.2 py36_0
        - certifi 2018.1.18 py36_0
        - python 3.6.4 0
        - xz 5.2.3 0
        - pyzmq 17.0.0 py36_3
        - openssl 1.0.2n 0
        - prompt_toolkit 1.0.15 py36_0
        - pip 9.0.1 py36_1
        - wcwidth 0.1.7 py36_0
        - readline 7.0 0
        - setuptools 38.5.1 py36_0
        - parso 0.1.1 py_0
        - jupyter_client 5.2.2 py36_0
        - zlib 1.2.11 0
        - ipython_genutils 0.2.0 py36_0
        - pexpect 4.4.0 py36_0
        - pickleshare 0.7.4 py36_0
        - simplegeneric 0.8.1 py36_0
        - tk 8.6.7 0
        - ipython 6.2.1 py36_1
        - pygments 2.2.0 py36_0
        - python-dateutil 2.6.1 py36_0
        - zeromq 4.2.3 2
        - tornado 4.5.3 py36_0
        - jedi 0.11.1 py36_0
        - ca-certificates 2018.1.18 0
        - ncurses 5.9 10
        - jupyter_core 4.4.0 py_0
        - six 1.11.0 py36_1
        - wheel 0.30.0 py36_2
        - ptyprocess 0.5.2 py36_0
        - sqlite 3.20.1 2
        - libsodium 1.0.15 1
    run:
        - python
        - ipython >=4.0
        - traitlets >=4.1
        - jupyter_client
        - tornado >=4.0
test:
    imports:
        - ipykernel
about:
    home: http://ipython.org
    license: BSD 3-clause
    license_file: COPYING.md
    summary: IPython Kernel for Jupyter
extra:
    final: true
    recipe-maintainers:
        - jakirkham
        - pelson
        - minrk
        - ocefpaf
        - blink1073
