# This file created by conda-build 3.13.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Thu Aug 23 18:28:45 2018
# ------------------------------------------------

package:
    name: bleach
    version: 2.1.4
source:
    fn: bleach-2.1.4.tar.gz
    sha256: 0ee95f6167129859c5dce9b1ca291ebdb5d8cd7e382ca0e237dfd0dad63f63d8
    url: https://pypi.io/packages/source/b/bleach/bleach-2.1.4.tar.gz
build:
    noarch: python
    number: '1'
    script: pip install --no-deps .
    string: py_1
requirements:
    host:
        - bzip2 1.0.6 h470a237_2
        - ca-certificates 2018.8.13 ha4d7672_0
        - certifi 2018.8.13 py27_0
        - libgcc-ng 7.2.0 hdf63c60_3
        - libstdcxx-ng 7.2.0 hdf63c60_3
        - ncurses 6.1 hfc679d8_1
        - openssl 1.0.2o h470a237_1
        - pip 18.0 py27_1
        - python 2.7.15 h9fef7bc_0
        - readline 7.0 haf1bffa_1
        - setuptools 40.2.0 py27_0
        - sqlite 3.24.0 h2f33b56_0
        - tk 8.6.8 0
        - wheel 0.31.1 py27_1
        - zlib 1.2.11 h470a237_3
    run:
        - html5lib >=0.99999999pre,!=1.0b1,!=1.0b2,!=1.0b3,!=1.0b4,!=1.0b5,!=1.0b6,!=1.0b7,!=1.0b8
        - python
        - setuptools
        - six
test:
    imports:
        - bleach
about:
    description: 'Bleach is an allowed-list-based HTML sanitizing library that escapes
        or

        strips markup and attributes.

        '
    dev_url: https://github.com/mozilla/bleach
    doc_source_url: https://github.com/mozilla/bleach/blob/master/docs/index.rst
    doc_url: https://bleach.readthedocs.io/
    home: https://github.com/mozilla/bleach
    license: Apache-2.0
    license_family: Apache
    license_file: LICENSE
    summary: Easy, whitelist-based HTML-sanitizing tool
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - minrk
