c_compiler: toolchain_c
channel_sources: conda-forge,defaults
channel_targets: conda-forge main
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cxx_compiler: toolchain_cxx
docker_image: condaforge/linux-anvil
fortran_compiler: gfortran
ignore_build_only_deps: numpy
lua: '5'
numpy: '1.11'
perl: 5.26.0
pin_run_as_build:
  python: {max_pin: x.x, min_pin: x.x}
  r-base: {min_pin: x.x.x, max_pin: x.x.x}
  qt: {max_pin: x.x}
python: '3.6'
qt: '5.6'
r_base: '3.4'
target_platform: linux-64
