# This file created by conda-build 3.13.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Aug 27 16:34:10 2018
# ------------------------------------------------

package:
    name: pyqt
    version: 5.6.0
source:
    fn: PyQt5_gpl-5.6.tar.gz
    sha1: 8920e4094470ff93f79e257c37c46f5cd0bff7ab
    url: http://sourceforge.net/projects/pyqt/files/PyQt5/PyQt-5.6/PyQt5_gpl-5.6.tar.gz
build:
    number: '7'
    string: py36h8210e8a_7
requirements:
    build:
        - toolchain 2.1.6 0
        - toolchain_c_linux-64 2.1.6 0
        - toolchain_cxx_linux-64 2.1.6 0
    host:
        - bzip2 1.0.6 h470a237_2
        - ca-certificates 2018.8.24 ha4d7672_0
        - dbus 1.13.0 h3a4f0e9_0
        - expat 2.2.5 hfc679d8_1
        - fontconfig 2.13.0 h65d0f4c_5
        - freetype 2.9.1 h6debe1e_1
        - gettext 0.19.8.1 0
        - glib 2.55.0 h464dc38_2
        - gst-plugins-base 1.12.5 hde13a9d_0
        - gstreamer 1.12.5 h61a6719_0
        - icu 58.2 hfc679d8_0
        - jpeg 9c h470a237_0
        - libffi 3.2.1 hfc679d8_4
        - libgcc-ng 7.2.0 hdf63c60_3
        - libiconv 1.15 h470a237_2
        - libpng 1.6.35 ha92aebf_0
        - libstdcxx-ng 7.2.0 hdf63c60_3
        - libuuid 2.32.1 h470a237_0
        - libxcb 1.13 h470a237_2
        - libxml2 2.9.8 h422b904_3
        - ncurses 6.1 hfc679d8_1
        - openssl 1.0.2o h470a237_1
        - pcre 8.41 h470a237_2
        - pthread-stubs 0.4 h470a237_1
        - python 3.6.6 h5001a0f_0
        - qt 5.6.2 hf70d934_9
        - readline 7.0 haf1bffa_1
        - sip 4.18 py36_1
        - sqlite 3.24.0 h2f33b56_0
        - tk 8.6.8 0
        - xorg-libxau 1.0.8 h470a237_6
        - xorg-libxdmcp 1.1.2 h470a237_7
        - xz 5.2.4 h470a237_1
        - zlib 1.2.11 h470a237_3
    run:
        - libgcc-ng >=4.9
        - libstdcxx-ng >=4.9
        - python >=3.6,<3.7.0a0
        - qt >=5.6.2,<5.7.0a0
        - sip 4.18.*
test:
    commands:
        - DISPLAY=localhost:1.0 xvfb-run -a bash -c 'python pyqt_test.py'
    files:
        - pyqt_test.py
    imports:
        - PyQt5.QtCore
        - PyQt5.QtGui
        - PyQt5.QtHelp
        - PyQt5.QtMultimedia
        - PyQt5.QtMultimediaWidgets
        - PyQt5.QtNetwork
        - PyQt5.QtOpenGL
        - PyQt5.QtPrintSupport
        - PyQt5.QtQml
        - PyQt5.QtQuick
        - PyQt5.QtSvg
        - PyQt5.QtTest
        - PyQt5.QtWebChannel
        - PyQt5.QtWebKitWidgets
        - PyQt5.QtWebSockets
        - PyQt5.QtWidgets
        - PyQt5.QtXml
        - PyQt5.QtXmlPatterns
about:
    description: '"PyQt is a set of Python v2 and v3 bindings for The Qt Company''s
        Qt

        application framework and runs on all platforms supported by Qt including

        Windows, MacOS/X and Linux. PyQt5 supports Qt v5. PyQt4 supports Qt v4 and

        will build against Qt v5. The bindings are implemented as a set of Python

        modules and contain over 1,000 classes."

        '
    dev_url: https://github.com/pyqt
    doc_url: https://www.riverbankcomputing.com/software/pyqt/
    home: http://www.riverbankcomputing.co.uk/software/pyqt
    license: Commercial, GPL-2.0, GPL-3.0
    license_family: GPL
    license_file: LICENSE
    summary: Python binding of the cross-platform GUI toolkit Qt.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ccordoba12
        - gillins
        - jschueller
        - mingwandroid
        - msarahan
        - ocefpaf
