# This file created by conda-build 3.12.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Jul 31 17:43:19 2018
# ------------------------------------------------

package:
    name: wheel
    version: 0.31.1
source:
    sha256: 0a2e54558a0628f2145d2fc822137e322412115173e8a2ddbe1c9024338ae83c
    url: https://pypi.io/packages/source/w/wheel/wheel-0.31.1.tar.gz
build:
    entry_points:
        - wheel = wheel.tool:main
    number: '1'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py36_1
requirements:
    host:
        - bzip2 1.0.6 h470a237_2
        - ca-certificates 2018.4.16 0
        - certifi 2018.4.16 py36_0
        - libffi 3.2.1 3
        - libgcc-ng 7.2.0 hdf63c60_3
        - libstdcxx-ng 7.2.0 hdf63c60_3
        - ncurses 6.1 hfc679d8_1
        - openssl 1.0.2o h470a237_1
        - python 3.6.6 h5001a0f_0
        - readline 7.0 haf1bffa_1
        - setuptools 40.0.0 py36_1
        - sqlite 3.24.0 h2f33b56_0
        - tk 8.6.8 0
        - xz 5.2.4 h470a237_0
        - zlib 1.2.11 h470a237_3
    run:
        - python >=3.6,<3.7.0a0
        - setuptools
test:
    commands:
        - wheel --help
    imports:
        - wheel
        - wheel.signatures
        - wheel.tool
about:
    home: https://bitbucket.org/pypa/wheel/
    license: MIT
    license_file: LICENSE.txt
    summary: A built-package format for Python.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - mingwandroid
        - ocefpaf
        - pelson
