# This file created by conda-build 3.10.9+36.gd10dbde.dirty
# meta.yaml template originally from:
# /home/rdonnelly/conda/aggregate/bcrypt-feedstock/recipe, last modified Mon Oct 30 09:19:16 2017
# ------------------------------------------------

package:
    name: bcrypt
    version: 3.1.4
source:
    fn: bcrypt-3.1.4.tar.gz
    sha256: 67ed1a374c9155ec0840214ce804616de49c3df9c5bc66740687c1c9b1cd9e8d
    url: https://pypi.io/packages/source/b/bcrypt/bcrypt-3.1.4.tar.gz
build:
    number: '0'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py36h14c3975_0
requirements:
    build:
        - binutils_impl_linux-64 2.28.1 had2808c_3
        - binutils_linux-64 7.2.0 had2808c_27
        - gcc_impl_linux-64 7.2.0 habb00fd_3
        - gcc_linux-64 7.2.0 h550dcbe_27
        - libstdcxx-ng 7.2.0 hdf63c60_3
    host:
        - ca-certificates 2018.03.07 0
        - certifi 2018.4.16 py36_0
        - cffi 1.11.5 py36h9745a5d_0
        - libedit 3.1.20170329 h6b74fdf_2
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 7.2.0 hdf63c60_3
        - libstdcxx-ng 7.2.0 hdf63c60_3
        - ncurses 6.1 hf484d3e_0
        - openssl 1.0.2o h20670df_0
        - pycparser 2.18 py36_1
        - python 3.6.6 hc3d631a_0
        - readline 7.0 ha6073c6_4
        - setuptools 39.2.0 py36_0
        - sqlite 3.24.0 h84994c4_0
        - tk 8.6.7 hc745277_3
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 ha838bed_2
    run:
        - cffi >=1.1
        - libgcc-ng >=7.2.0
        - python >=3.6,<3.7.0a0
        - six >=1.4.1
test:
    commands:
        - pytest tests
    imports:
        - bcrypt
        - bcrypt._bcrypt
    requires:
        - pytest >=3.2.1
    source_files:
        - tests
about:
    description: 'Modern password hashing for your software and your servers

        '
    doc_source_url: https://github.com/pyca/bcrypt/blob/master/README.rst
    doc_url: https://pypi.python.org/pypi/bcrypt/3.1.3
    home: https://github.com/pyca/bcrypt/
    license: Apache License, Version 2.0
    license_family: Apache
    license_file: LICENSE
    summary: modern password hashing for your software and your servers
extra:
    copy_test_source_files: true
    final: true
