# This file created by conda-build 2.1.18
# meta.yaml template originally from:
# /recipe_root, last modified Thu Feb  8 16:22:25 2018
# ------------------------------------------------

package:
    name: gettext
    version: 0.19.8.1
source:
    fn: gettext-0.19.8.1.tar.xz
    sha256: 105556dbc5c3fbbc2aa0edb46d22d055748b6f5c7cd7a8d99f8e7eb84e938be4
    url: ftp://ftp.gnu.org/pub/gnu/gettext/gettext-0.19.8.1.tar.xz
build:
    noarch: ''
    noarch_python: false
    number: '0'
    string: '0'
requirements:
    build:
        - libiconv 1.15 0
        - libffi 3.2.1 3
    run: []
test:
    commands:
        - test -f ${PREFIX}/lib/libgettextlib.so
about:
    home: https://www.gnu.org/software/gettext/
    license: GPLv2
    license_file: COPYING
    summary: Internationalization package.
extra:
    final: true
    recipe-maintainers:
        - scopatz
