# This file created by conda-build 2.1.18
# meta.yaml template originally from:
# /recipe_root, last modified Mon Mar  5 01:45:51 2018
# ------------------------------------------------

package:
    name: h5py
    version: 2.7.1
source:
    sha256: 55bdefda47c49973ec24384097d18eb5f84797c057aaf0bf0b6b0f7860ad43e7
    url: https://github.com/h5py/h5py/archive/2.7.1.tar.gz
build:
    noarch: ''
    noarch_python: false
    number: '3'
    string: py36_3
requirements:
    build:
        - cython 0.27.3 py36_0
        - certifi 2018.1.18 py36_0
        - hdf5 1.10.1 2
        - python 3.6.4 0
        - xz 5.2.3 0
        - openssl 1.0.2n 0
        - openblas 0.2.20 7
        - readline 7.0 0
        - setuptools 38.5.1 py36_0
        - pkgconfig 1.3.1 py36_0
        - zlib 1.2.11 0
        - pkg-config 0.29.1 2
        - tk 8.6.7 0
        - blas 1.1 openblas
        - libgfortran 3.0.0 1
        - ca-certificates 2018.1.18 0
        - ncurses 5.9 10
        - numpy 1.8.2 py36_blas_openblas_201
        - six 1.11.0 py36_1
        - sqlite 3.20.1 2
    run:
        - python
        - numpy >=1.8,<1.14
        - hdf5 1.10.1
        - six
test:
    imports:
        - h5py
about:
    home: http://www.h5py.org/
    license: BSD 3-Clause
    license_file: licenses/license.txt
    summary: Read and write HDF5 files from Python.
extra:
    final: true
    recipe-maintainers:
        - jakirkham
        - pitrou
        - tacaswell
