# This file created by conda-build 2.1.17
# meta.yaml template originally from:
# /recipe_root, last modified Mon Jul 24 08:16:00 2017
# ------------------------------------------------

package:
    name: aioeasywebdav
    version: 2.2.0
source:
    fn: aioeasywebdav-2.2.0.tar.gz
    sha256: 2645934033bf2788ac962123d223e853fdbb0425127080e86b43be58d5d2545f
    url: https://pypi.io/packages/source/a/aioeasywebdav/aioeasywebdav-2.2.0.tar.gz
build:
    noarch: ''
    noarch_python: false
    number: '0'
    script: python setup.py install --single-version-externally-managed --record record.txt
    string: py36_0
requirements:
    build:
        - ca-certificates 2017.4.17 0
        - ncurses 5.9 10
        - sqlite 3.13.0 1
        - tk 8.5.19 1
        - xz 5.2.2 0
        - zlib 1.2.11 0
        - openssl 1.0.2l 0
        - readline 6.2 0
        - python 3.6.2 0
        - async-timeout 1.2.1 py36_0
        - certifi 2017.4.17 py36_0
        - chardet 3.0.2 py36_1
        - multidict 2.1.4 py36_0
        - six 1.10.0 py36_1
        - setuptools 36.2.0 py36_0
        - yarl 0.10.0 py36_0
        - aiohttp 2.0.7 py36_0
        - setuptools_scm 1.15.6 py36_0
    run:
        - python
        - aiohttp
        - six
test:
    imports:
        - aioeasywebdav
about:
    description: 'This project started as a port of the requests-based EasyWebDAV

        (http://github.com/amnong/easywebdav) to asyncio on Python 3.5. It has

        since been extended with additional features.

        '
    dev_url: https://gitlab.alelec.net/corona/aioeasywebdav
    home: https://gitlab.alelec.net/corona/aioeasywebdav
    license: ISC
    license_file: LICENSE
    summary: A straight-forward WebDAV client, ported from easywebdav to use aiohttp.
extra:
    final: true
    recipe-maintainers:
        - johanneskoester
