# This file created by conda-build 3.12.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sat Jul 28 07:16:23 2018
# ------------------------------------------------

package:
    name: pyvcf
    version: 0.6.8
source:
    sha256: e9d872513d179d229ab61da47a33f42726e9613784d1cb2bac3f8e2642f6f9d9
    url: https://pypi.io/packages/source/P/PyVCF/PyVCF-0.6.8.tar.gz
build:
    number: '0'
    script: python -m pip install --no-deps --ignore-installed .
    string: py36_0
requirements:
    host:
        - bzip2 1.0.6 h470a237_2
        - ca-certificates 2018.4.16 0
        - certifi 2018.4.16 py36_0
        - libffi 3.2.1 3
        - libgcc-ng 7.2.0 hdf63c60_3
        - libstdcxx-ng 7.2.0 hdf63c60_3
        - ncurses 6.1 hfc679d8_1
        - openssl 1.0.2o h470a237_1
        - pip 18.0 py36_0
        - python 3.6.6 h5001a0f_0
        - readline 7.0 haf1bffa_1
        - setuptools 40.0.0 py36_0
        - sqlite 3.24.0 h2f33b56_0
        - tk 8.6.8 0
        - wheel 0.31.1 py36_0
        - xz 5.2.4 h470a237_0
        - zlib 1.2.11 h470a237_3
    run:
        - python >=3.6,<3.7.0a0
test:
    imports:
        - vcf
about:
    description: 'The intent of this module is to mimic the csv module in

        the Python stdlib, as opposed to more flexible serialization

        formats like JSON or YAML. vcf will attempt to parse the

        content of each record based on the data types specified in

        the meta-information lines -- specifically the \##INFO and \##FORMAT

        lines. If these lines are missing or incomplete, it will check

        against the reserved types mentioned in the spec. Failing

        that, it will just return strings.

        '
    dev_url: https://github.com/jamescasbon/PyVCF
    doc_url: http://pyvcf.readthedocs.io
    home: https://github.com/jamescasbon/PyVCF
    license: BSD-3-Clause
    license_family: BSD
    license_file: LICENSE
    summary: A Variant Call Format (VCF) v4.0 and v4.1 parser for Python.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - PertuyF
        - acaprez
        - bgruening
        - corburn
        - kyleabeauchamp
        - pvanheus
        - sodre
