c_compiler: toolchain_c
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cxx_compiler: gxx
fortran_compiler: gfortran
gstreamer: '1.12'
ignore_build_only_deps: python
lua: '5'
numpy: '1.11'
perl: '5.26'
pin_run_as_build:
  python: {min_pin: x.x, max_pin: x.x}
  r-base: {min_pin: x.x.x, max_pin: x.x.x}
  gstreamer: {max_pin: x.x}
  perl: {max_pin: x.x.x}
  xz: {max_pin: x.x}
python: '3.6'
r_base: '3.4'
target_platform: linux-64
xz: '5.2'
