# This file created by conda-build 3.12.1
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Aug 14 20:38:11 2018
# ------------------------------------------------

package:
    name: cryptography
    version: 2.3.1
source:
    sha256: 8d10113ca826a4c29d5b85b2c4e045ffa8bad74fb525ee0eceb1d38d4c70dfd6
    url: https://pypi.io/packages/source/c/cryptography/cryptography-2.3.1.tar.gz
build:
    number: '0'
    script:
        - export CFLAGS="-I${PREFIX}/include ${CFLAGS}"
        - export LDFLAGS="-L${PREFIX}/lib ${LDFLAGS}"
        - python -m pip install --no-deps --ignore-installed .
    string: py36hdffb7b8_0
requirements:
    build:
        - toolchain 2.1.6 0
        - toolchain_c_linux-64 2.1.6 0
    host:
        - bzip2 1.0.6 h470a237_2
        - ca-certificates 2018.4.16 0
        - certifi 2018.8.13 py36_0
        - cffi 1.11.5 py36h5e8e0c9_1
        - cryptography-vectors 2.3.1 py36_0
        - libffi 3.2.1 hfc679d8_4
        - libgcc-ng 7.2.0 hdf63c60_3
        - libstdcxx-ng 7.2.0 hdf63c60_3
        - ncurses 6.1 hfc679d8_1
        - openssl 1.0.2o h470a237_1
        - pip 18.0 py36_1
        - pycparser 2.18 py_1
        - python 3.6.6 h5001a0f_0
        - readline 7.0 haf1bffa_1
        - setuptools 40.0.0 py36_1
        - sqlite 3.24.0 h2f33b56_0
        - tk 8.6.8 0
        - wheel 0.31.1 py36_1
        - xz 5.2.4 h470a237_1
        - zlib 1.2.11 h470a237_3
    run:
        - asn1crypto >=0.21.0
        - cffi >=1.7
        - cryptography-vectors 2.3.1.*
        - idna >=2.1
        - libgcc-ng >=4.9
        - openssl >=1.0.2o,<1.0.3a
        - python >=3.6,<3.7.0a0
        - six >=1.4.1
test:
    commands:
        - pytest
    imports:
        - cryptography
        - cryptography.fernet
        - cryptography.hazmat
        - cryptography.hazmat.backends
        - cryptography.hazmat.backends.openssl
        - cryptography.hazmat.bindings
        - cryptography.hazmat.bindings.openssl
        - cryptography.hazmat.primitives
        - cryptography.hazmat.primitives.asymmetric
        - cryptography.hazmat.primitives.ciphers
        - cryptography.hazmat.primitives.kdf
        - cryptography.hazmat.primitives.twofactor
        - cryptography.x509
    requires:
        - cryptography-vectors 2.3.1.*
        - hypothesis >=1.11.4
        - iso8601
        - pretend
        - pytest >=3.2.1,!=3.3.0
        - pytz
    source_files:
        - tests
about:
    description: 'Cryptography is a package which provides cryptographic recipes and

        primitives to Python developers. Our goal is for it to be your

        "cryptographic standard library". It supports Python 2.6-2.7, Python 3.3+,

        and PyPy 2.6+. Cryptography includes both high level recipes, and low level

        interfaces to common cryptographic algorithms such as symmetric ciphers,

        message digests and key derivation functions.

        '
    dev_url: https://github.com/pyca/cryptography
    doc_source_url: https://github.com/pyca/cryptography/tree/master/docs
    doc_url: http://cryptography.readthedocs.io/
    home: https://github.com/pyca/cryptography
    license: Apache 2.0 or BSD 3-Clause, PSF 2
    license_family: BSD
    license_file: LICENSE
    summary: Provides cryptographic recipes and primitives to Python developers
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jschueller
        - ocefpaf
