# This file created by conda-build 2.1.18
# meta.yaml template originally from:
# /recipe_root, last modified Tue Dec 26 03:32:43 2017
# ------------------------------------------------

package:
    name: sqlite
    version: 3.20.1
source:
    patches: ''
    sha256: 06129c03dced9f87733a8cba408871bd60673b8f93b920ba8d815efab0a06301
    url: https://www.sqlite.org/2017/sqlite-autoconf-3190300.tar.gz
build:
    features: ''
    noarch: ''
    noarch_python: false
    number: '2'
    string: '2'
requirements:
    build:
        - readline 7.0 0
        - zlib 1.2.11 0
        - pkg-config 0.29.1 2
        - ncurses 5.9 10
        - toolchain 2.1.2 0
    run:
        - ncurses 5.9
        - readline 7.0
test:
    commands:
        - sqlite3 --version
        - conda inspect linkages -p $PREFIX $PKG_NAME
about:
    home: http://www.sqlite.org/
    license: Public-Domain (http://www.sqlite.org/copyright.html)
    summary: Implements a self-contained, zero-configuration, SQL database engine.
extra:
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - msarahan
        - ocefpaf
        - snorfalorpagus
