# This file created by conda-build 3.0.15+50.g6024f3f
# meta.yaml template originally from:
# /home/rdonnelly/conda/aggregate/libgcc-feedstock/recipe, last modified Sun Sep 17 15:35:06 2017
# ------------------------------------------------

package:
    name: libgcc
    version: 7.2.0
build:
    always_include_files:
        - lib/libgfortran.so.3
        - lib/libgfortran.so.3.0.0
    number: '2'
    string: h69d50b8_2
requirements:
    build:
        - cloog 0.18.0 0
        - gcc 4.8.5 7
        - gmp 6.1.2 hb3b607b_0
        - isl 0.12.2 0
        - libgcc-ng 7.2.0 hcbc56d2_1
        - libstdcxx-ng 7.2.0 h24385c6_1
        - mpc 1.0.3 hf803216_4
        - mpfr 3.1.5 h12ff648_1
    run:
        - libgcc-ng >=7.2.0
        - libstdcxx-ng >=7.2.0
about:
    home: http://gcc.gnu.org/
    license: GNU GPL 3+ with GCC Runtime Library
    license_family: GPL
    summary: Shared libraries for the GNU Compiler Collection
extra:
    copy_test_source_files: true
    final: true
