# This file created by conda-build 2.1.15
# meta.yaml template originally from:
# /recipe_root, last modified Thu Jun 22 20:28:15 2017
# ------------------------------------------------

package:
    name: pynacl
    version: 1.1.2
source:
    fn: pynacl-1.1.2.tar.gz
    sha256: 448897f0cfe3607dc23a871fa4405ef00926179df27ee8dfd0e46d42c60d8968
    url: https://github.com/pyca/pynacl/archive/1.1.2.tar.gz
build:
    noarch: ''
    noarch_python: false
    number: '0'
    script: python setup.py install --single-version-externally-managed --record record.txt
    string: py36_0
requirements:
    build:
        - openssl 1.0.2k 0
        - sqlite 3.13.0 1
        - libffi 3.2.1 3
        - python 3.6.1 3
        - setuptools 33.1.1 py36_0
        - ca-certificates 2017.4.17 0
        - cffi 1.10.0 py36_0
        - readline 6.2 0
        - certifi 2017.4.17 py36_0
        - ncurses 5.9 10
        - pycparser 2.17 py36_0
        - zlib 1.2.11 0
        - tk 8.5.19 1
        - xz 5.2.2 0
    run:
        - python
        - six
        - cffi
test:
    commands:
        - pytest
    requires:
        - pytest
        - pretend
    source_files:
        - tests/
about:
    description: 'PyNaCl is a Python binding to the Networking and Cryptography library,
        a crypto library with the stated goal of improving usability, security and
        speed. It supports Python 2.7 and 3.3+ as well as PyPy 2.6+.

        '
    dev_url: https://github.com/pyca/pynacl
    doc_url: https://pynacl.readthedocs.io/en/latest/
    home: https://github.com/pyca/pynacl
    license: Apache-2.0
    license_family: Apache
    license_file: LICENSE
    summary: PyNaCl is a Python binding to the Networking and Cryptography library,
        a crypto library with the stated goal of improving usability, security and
        speed.
extra:
    final: true
    recipe-maintainers:
        - CJ-Wright
