# This file created by conda-build 2.1.17
# meta.yaml template originally from:
# /recipe_root, last modified Mon Nov 27 12:52:25 2017
# ------------------------------------------------

package:
    name: graphviz
    version: 2.38.0
source:
    fn: graphviz-2.38.0.tar.gz
    md5: 5b6a829b2ac94efcd5fa3c223ed6d3ae
    patches:
        - gvconfig_libdir.patch
    url: http://www.graphviz.org/pub/graphviz/stable/SOURCES/graphviz-2.38.0.tar.gz
build:
    detect_binary_files_with_prefix: 'True'
    noarch: ''
    noarch_python: false
    number: '7'
    string: '7'
requirements:
    build:
        - libiconv 1.15 0
        - libtool 2.4.6 0
        - graphite2 1.3.10 0
        - libpng 1.6.34 0
        - pixman 0.34.0 1
        - zlib 1.2.11 0
        - glib 2.55.0 0
        - harfbuzz 1.7.1 0
        - xz 5.2.3 0
        - libtiff 4.0.9 0
        - gettext 0.19.7 1
        - fontconfig 2.12.6 0
        - icu 58.2 0
        - pango 1.40.14 0
        - libxml2 2.9.5 2
        - cairo 1.14.10 0
        - pcre 8.39 0
        - expat 2.2.5 0
        - freetype 2.8.1 0
        - jpeg 9b 2
        - libffi 3.2.1 3
    run:
        - cairo 1.14.*
        - expat 2.2.*
        - libpng >=1.6.32,<1.6.35
        - libtiff >=4.0.8,<4.0.10
        - libtool
        - freetype 2.8.1
        - jpeg 9*
        - pango 1.40.*
        - zlib 1.2.11
test:
    commands:
        - dot -V
        - neato -?
        - conda inspect linkages $PKG_NAME
    files:
        - sample.dot
about:
    description: 'Graphviz is an open source graph visualization software. Graph visualization

        is a way of representing structural information as diagrams of abstract

        graphs and networks.

        '
    dev_url: https://github.com/ellson/graphviz
    doc_url: http://www.graphviz.org/Documentation.php
    home: http://www.graphviz.org/
    license: EPL v1.0
    license_family: Other
    license_file: COPYING
    summary: Open Source graph visualization software.
extra:
    final: true
    recipe-maintainers:
        - jakirkham
        - ccordoba12
        - ocefpaf
