# This file created by conda-build 3.10.9
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sun Jul  1 10:40:17 2018
# ------------------------------------------------

package:
    name: libtiff
    version: 4.0.9
source:
    patches:
        - 0001-CVE-2017-9935.patch
        - 0002-CVE-2017-18013.patch
        - 0003-CVE-2018-5784.patch
        - 0004-CVE-2017-11613_part1.patch
        - 0005-CVE-2017-11613_part2.patch
        - 0006-CVE-2018-7456.patch
        - 0007-CVE-2017-17095.patch
    sha256: 6e7bdeec2c310734e734d19aae3a71ebe37a4d842e0e23dbb1b8921c0026cfcd
    url: http://download.osgeo.org/libtiff/tiff-4.0.9.tar.gz
build:
    number: '1'
    run_exports:
        - libtiff >=4.0.9,<5.0a0
    string: he6b73bb_1
requirements:
    build:
        - toolchain 2.1.5 0
        - toolchain_c_linux-64 2.1.5 0
        - toolchain_cxx_linux-64 2.1.5 0
    host:
        - jpeg 9b h470a237_3
        - libgcc-ng 7.2.0 hdf63c60_3
        - libstdcxx-ng 7.2.0 hdf63c60_3
        - xz 5.2.3 0
        - zlib 1.2.11 h470a237_3
    run:
        - jpeg >=9b,<10a
        - jpeg >=9b,<10a
        - libgcc-ng >=4.9
        - libstdcxx-ng >=4.9
        - xz >=5.2.3,<5.3.0a0
        - zlib >=1.2.11,<1.3.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - test -f ${PREFIX}/lib/libtiff.a
        - test -f ${PREFIX}/lib/libtiffxx.a
        - test -f ${PREFIX}/lib/libtiff${SHLIB_EXT}
        - test -f ${PREFIX}/lib/libtiffxx${SHLIB_EXT}
        - conda inspect linkages -p $PREFIX $PKG_NAME
about:
    home: http://www.remotesensing.org/libtiff/
    license: HPND
    license_file: COPYRIGHT
    summary: Support for the Tag Image File Format (TIFF).
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - msarahan
        - ocefpaf
        - stuarteberg
