# This file created by conda-build 3.10.9
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Jul 10 06:43:31 2018
# ------------------------------------------------

package:
    name: seaborn
    version: 0.8.1
source:
    fn: seaborn-0.8.1.tar.gz
    sha256: 6702978b903d0284446e935916b980dfebae4063c18ad8eb6e8f9e76d0257eae
    url: https://pypi.io/packages/source/s/seaborn/seaborn-0.8.1.tar.gz
build:
    noarch: python
    number: '1'
    script: python -m pip install --no-deps --ignore-installed .
    string: py_1
requirements:
    host:
        - ca-certificates 2018.4.16 0
        - certifi 2018.4.16 py27_0
        - libgcc-ng 7.2.0 hdf63c60_3
        - ncurses 5.9 10
        - openssl 1.0.2o 0
        - pip 9.0.3 py27_0
        - python 2.7.15 0
        - readline 7.0 0
        - setuptools 40.0.0 py27_0
        - sqlite 3.20.1 2
        - tk 8.6.7 0
        - wheel 0.31.1 py27_0
        - zlib 1.2.11 h470a237_3
    run:
        - matplotlib
        - numpy
        - pandas
        - patsy
        - python
        - scipy
        - statsmodels
test:
    imports:
        - seaborn
about:
    description: 'Seaborn is a Python visualization library based on matplotlib. It

        provides a high-level interface for drawing attractive statistical graphics.

        '
    dev_url: https://github.com/mwaskom/seaborn
    doc_url: http://stanford.edu/~mwaskom/software/seaborn/
    home: http://stanford.edu/~mwaskom/software/seaborn/
    license: BSD 3-Clause
    license_family: BSD
    license_file: LICENSE
    summary: Statistical data visualization
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - croth1
        - msarahan
        - r-jain1
