# This file created by conda-build 3.10.9
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Thu Jun 21 19:03:54 2018
# ------------------------------------------------

package:
    name: shapely
    version: 1.6.4
source:
    sha256: 30df7572d311514802df8dc0e229d1660bc4cbdcf027a8281e79c5fc2fcf02f2
    url: https://pypi.io/packages/source/S/Shapely/Shapely-1.6.4.post1.tar.gz
build:
    number: '1'
    string: py36h164cb2d_1
requirements:
    build:
        - toolchain 2.1.5 0
        - toolchain_c_linux-64 2.1.5 0
    host:
        - blas 1.1 openblas
        - ca-certificates 2018.4.16 0
        - certifi 2018.4.16 py36_0
        - cython 0.28.3 py36_0
        - geos 3.6.2 hfc679d8_2
        - libgcc-ng 7.2.0 hdf63c60_3
        - libgfortran 3.0.0 1
        - libstdcxx-ng 7.2.0 hdf63c60_3
        - ncurses 5.9 10
        - numpy 1.9.3 py36_blas_openblas_203
        - openblas 0.2.20 8
        - openssl 1.0.2o 0
        - pip 9.0.3 py36_0
        - python 3.6.5 1
        - readline 7.0 0
        - setuptools 39.2.0 py36_0
        - sqlite 3.20.1 2
        - tk 8.6.7 0
        - wheel 0.31.0 py36_0
        - xz 5.2.3 0
        - zlib 1.2.11 h470a237_3
    run:
        - geos >=3.6.2,<3.6.3.0a0
        - libgcc-ng >=4.9
        - numpy >=1.9.3,<2.0a0
        - python >=3.6,<3.7.0a0
test:
    commands:
        - py.test tests --with-speedups
        - conda inspect linkages -p $PREFIX $PKG_NAME
    imports:
        - shapely
        - shapely.speedups._speedups
        - shapely.vectorized._vectorized
    requires:
        - pytest
    source_files:
        - tests
about:
    home: https://github.com/Toblerity/Shapely
    license: BSD 3-Clause
    license_file: LICENSE.txt
    summary: Python package for manipulation and analysis of geometric objects in
        the Cartesian plane.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ocefpaf
        - pelson
        - phobson
