# This file created by conda-build 2.1.18
# meta.yaml template originally from:
# /recipe_root, last modified Thu Dec 21 16:40:41 2017
# ------------------------------------------------

package:
    name: python-irodsclient
    version: 0.7.0
source:
    fn: python-irodsclient-0.7.0.tar.gz
    sha256: 81dd6718722c357b37dfd197f6d7b51f40adc52048dd2adfc9b53846c1f1a39c
    url: https://pypi.io/packages/source/p/python-irodsclient/python-irodsclient-0.7.0.tar.gz
build:
    noarch: python
    noarch_python: false
    number: '0'
    script: python setup.py install --single-version-externally-managed --record record.txt
    string: py_0
requirements:
    build:
        - xz 5.2.3 0
        - ca-certificates 2017.11.5 0
        - openssl 1.0.2n 0
        - readline 7.0 0
        - zlib 1.2.11 0
        - certifi 2017.11.5 py36_0
        - tk 8.6.7 0
        - python 3.6.3 4
        - sqlite 3.20.1 0
        - setuptools 38.2.4 py36_0
        - ncurses 5.9 10
    run:
        - python
        - six >=1.10.0
        - prettytable >=0.7.2
        - xmlrunner >=1.7.7
test:
    imports:
        - irods
        - irods.message
        - irods.manager
about:
    description: 'iRODS is an open-source distributed data management system. This
        is a

        client API implemented in python.

        '
    dev_url: https://github.com/irods/python-irodsclient
    doc_url: https://github.com/irods/python-irodsclient
    home: https://github.com/irods/python-irodsclient
    license: BSD-3-Clause
    summary: A python API for iRODS
extra:
    final: true
    recipe-maintainers:
        - stolpeo
