# This file created by conda-build 2.1.17
# meta.yaml template originally from:
# /recipe_root, last modified Wed Sep 20 15:55:21 2017
# ------------------------------------------------

package:
    name: zict
    version: 0.1.3
source:
    fn: zict-0.1.3.tar.gz
    sha256: 63377f063086fc92e5c16e4d02162c571f6470b9e796cf3411ef9e815c96b799
    url: https://pypi.io/packages/source/z/zict/zict-0.1.3.tar.gz
build:
    noarch: python
    noarch_python: false
    number: '0'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py_0
requirements:
    build:
        - ncurses 5.9 10
        - readline 6.2 0
        - tk 8.5.19 2
        - ca-certificates 2017.7.27.1 0
        - setuptools 36.3.0 py36_0
        - zlib 1.2.11 0
        - xz 5.2.3 0
        - certifi 2017.7.27.1 py36_0
        - python 3.6.2 0
        - sqlite 3.13.0 1
        - openssl 1.0.2l 0
    run:
        - python
        - heapdict
test:
    imports:
        - zict
about:
    home: http://github.com/mrocklin/zict
    license: BSD 3-Clause
    license_file: LICENSE.txt
    summary: Composable Dictionary Classes
extra:
    final: true
    recipe-maintainers:
        - mrocklin
        - pitrou
