# This file created by conda-build 2.1.18
# meta.yaml template originally from:
# /recipe_root, last modified Fri Apr  6 13:28:32 2018
# ------------------------------------------------

package:
    name: ipython
    version: 6.3.1
source:
    fn: ipython-6.3.1.tar.gz
    sha256: a6ac981381b3f5f604b37a293369963485200e3639fb0404fa76092383c10c41
    url: https://pypi.io/packages/source/i/ipython/ipython-6.3.1.tar.gz
build:
    entry_points:
        - ipython = IPython:start_ipython
        - ipython3 = IPython:start_ipython
    noarch: ''
    noarch_python: false
    number: '0'
    script: python -m pip install --no-deps .
    string: py36_0
requirements:
    build:
        - certifi 2018.1.18 py36_0
        - xz 5.2.3 0
        - openssl 1.0.2n 0
        - readline 7.0 0
        - zlib 1.2.11 0
        - tk 8.6.7 0
        - setuptools 39.0.1 py36_0
        - pip 9.0.3 py36_0
        - wheel 0.31.0 py36_0
        - ca-certificates 2018.1.18 0
        - ncurses 5.9 10
        - python 3.6.5 0
        - sqlite 3.20.1 2
    run:
        - python
        - pickleshare
        - simplegeneric >0.8
        - prompt_toolkit >=1.0.4,<2.0.0
        - pygments
        - decorator
        - traitlets >=4.2
        - jedi >=0.10
        - pexpect
        - backcall
test:
    commands:
        - ipython -h
        - ipython3 -h
    imports:
        - IPython
about:
    home: https://ipython.org/
    license: BSD 3-clause
    license_file: COPYING.rst
    summary: 'IPython: Productive Interactive Computing'
extra:
    final: true
    recipe-maintainers:
        - Carreau
        - jakirkham
        - minrk
        - ocefpaf
        - pelson
        - takluyver
