# This file created by conda-build 2.1.18
# meta.yaml template originally from:
# /recipe_root, last modified Tue Apr  3 17:01:33 2018
# ------------------------------------------------

package:
    name: krb5
    version: 1.14.6
source:
    fn: krb5-1.14.6.tar.gz
    patches: ''
    sha256: 34c7d6dfdd03d3c6827676a4c8e8fc590727ce396487da8d1b761ad39d728d9a
    url: https://github.com/krb5/krb5/archive/krb5-1.14.6-final.tar.gz
build:
    features: ''
    noarch: ''
    noarch_python: false
    number: '0'
    string: '0'
requirements:
    build:
        - xz 5.2.3 0
        - openssl 1.0.2n 0
        - bison 3.0.4 1
        - readline 7.0 0
        - autoconf 2.69 pl5.22.2.1_5
        - zlib 1.2.11 0
        - tk 8.6.7 0
        - perl 5.22.2.1 0
        - ca-certificates 2018.1.18 0
        - ncurses 5.9 10
        - python 3.6.5 0
        - m4 1.4.18 0
        - sqlite 3.20.1 2
    run: ''
test:
    commands:
        - conda inspect linkages -p $PREFIX krb5
about:
    home: http://web.mit.edu/kerberos/
    license: MIT
    license_file: doc/notice.rst
    summary: A network authentication protocol.
extra:
    final: true
    recipe-maintainers:
        - pelson
        - ocefpaf
