# This file created by conda-build 2.1.18
# meta.yaml template originally from:
# /recipe_root, last modified Tue Dec 19 17:26:48 2017
# ------------------------------------------------

package:
    name: xmlrunner
    version: 1.7.7
source:
    fn: xmlrunner-1.7.7.tar.gz
    sha256: 5a6113d049eca7646111ee657266966e5bbfb0b5ceb2e83ee0772e16d7110f39
    url: https://pypi.io/packages/source/x/xmlrunner/xmlrunner-1.7.7.tar.gz
build:
    noarch: python
    noarch_python: false
    number: '0'
    script: python setup.py install --single-version-externally-managed --record record.txt
    string: py_0
requirements:
    build:
        - xz 5.2.3 0
        - ca-certificates 2017.11.5 0
        - openssl 1.0.2n 0
        - readline 7.0 0
        - zlib 1.2.11 0
        - certifi 2017.11.5 py36_0
        - tk 8.6.7 0
        - python 3.6.3 4
        - sqlite 3.20.1 0
        - setuptools 38.2.4 py36_0
        - ncurses 5.9 10
    run:
        - python
test:
    imports:
        - xmlrunner
about:
    description: 'unittest-xml-reporting is a unittest test runner that can save test
        results

        to XML files that can be consumed by a wide range of tools, such as build

        systems, IDEs and continuous integration servers.

        '
    dev_url: https://github.com/pycontribs/xmlrunner
    doc_url: https://github.com/pycontribs/xmlrunner
    home: https://github.com/pycontribs/xmlrunner
    license: LGPL-3.0
    license_file: /recipe_root/LICENSE
    summary: PyUnit-based test runner with JUnit like XML reporting.
extra:
    final: true
    recipe-maintainers:
        - stolpeo
