# This file created by conda-build 3.13.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sun Aug 26 14:46:22 2018
# ------------------------------------------------

package:
    name: pyyaml
    version: '3.13'
source:
    patches:
        - 0001-Ensure-we-do-not-end-up-wih-CRLF-line-endings-on-tes.patch
    sha256: 3ef3092145e9b70e3ddd2c7ad59bdd0252a94dfe3949721633e41344de00a6bf
    url: https://pypi.io/packages/source/P/PyYAML/PyYAML-3.13.tar.gz
build:
    number: '0'
    script:
        - python setup.py --with-libyaml build_ext --include-dirs="${PREFIX}/include"
            --library-dirs="${PREFIX}/lib"
        - python setup.py install
        - python setup.py test
    string: py36h470a237_0
requirements:
    build:
        - toolchain 2.1.6 0
        - toolchain_c_linux-64 2.1.6 0
    host:
        - bzip2 1.0.6 h470a237_2
        - ca-certificates 2018.8.24 ha4d7672_0
        - libffi 3.2.1 hfc679d8_4
        - libgcc-ng 7.2.0 hdf63c60_3
        - libstdcxx-ng 7.2.0 hdf63c60_3
        - ncurses 6.1 hfc679d8_1
        - openssl 1.0.2o h470a237_1
        - python 3.6.6 h5001a0f_0
        - readline 7.0 haf1bffa_1
        - sqlite 3.24.0 h2f33b56_0
        - tk 8.6.8 0
        - xz 5.2.4 h470a237_1
        - yaml 0.1.7 h470a237_1
        - zlib 1.2.11 h470a237_3
    run:
        - cython
        - libgcc-ng >=4.9
        - python >=3.6,<3.7.0a0
        - yaml >=0.1.7,<0.2.0a0
test:
    imports:
        - _yaml
        - yaml
about:
    dev_url: https://github.com/yaml/pyyaml
    doc_url: http://pyyaml.org/wiki/PyYAML
    home: http://pyyaml.org/wiki/PyYAML
    license: MIT
    license_family: MIT
    license_file: LICENSE
    summary: YAML parser and emitter for Python
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - msarahan
        - ocefpaf
        - pelson
