# This file created by conda-build 2.1.18
# meta.yaml template originally from:
# /recipe_root, last modified Sun Dec 10 17:01:27 2017
# ------------------------------------------------

package:
    name: html5lib
    version: 1.0.1
source:
    fn: html5lib-1.0.1.tar.gz
    sha256: 66cb0dcfdbbc4f9c3ba1a63fdb511ffdbd4f513b2b6d81b80cd26ce6b3fb3736
    url: https://pypi.io/packages/source/h/html5lib/html5lib-1.0.1.tar.gz
build:
    noarch: python
    noarch_python: false
    number: '0'
    script: pip install --no-deps .
    string: py_0
requirements:
    build:
        - pip 9.0.1 py36_0
        - xz 5.2.3 0
        - ca-certificates 2017.11.5 0
        - openssl 1.0.2n 0
        - readline 7.0 0
        - zlib 1.2.11 0
        - certifi 2017.11.5 py36_0
        - tk 8.6.7 0
        - python 3.6.3 4
        - sqlite 3.20.1 0
        - setuptools 38.2.4 py36_0
        - wheel 0.30.0 py_1
        - ncurses 5.9 10
    run:
        - python
        - six >=1.9
        - webencodings
test:
    imports:
        - html5lib
        - html5lib._trie
        - html5lib.filters
        - html5lib.treeadapters
        - html5lib.treebuilders
        - html5lib.treewalkers
about:
    description: 'html5lib is a pure-python library for parsing HTML. It is designed
        to

        conform to the WHATWG HTML specification, as is implemented by all major

        web browsers.

        '
    dev_url: https://github.com/html5lib/html5lib-python
    doc_source_url: https://github.com/html5lib/html5lib-python/blob/master/doc/index.rst
    doc_url: http://html5lib.readthedocs.org/
    home: https://github.com/html5lib/html5lib-python
    license: MIT
    license_family: MIT
    license_file: LICENSE
    summary: HTML parser based on the WHATWG HTML specification
extra:
    final: true
    recipe-maintainers:
        - jakirkham
        - minrk
