# This file created by conda-build 3.12.1
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Aug 14 18:25:57 2018
# ------------------------------------------------

package:
    name: libprotobuf
    version: 3.6.0
source:
    -   sha256: 50a5753995b3142627ac55cfd496cebc418a2e575ca0236e29033c67bd5665f4
        url: https://github.com/google/protobuf/archive/v3.6.0/libprotobuf-v3.6.0.tar.gz
    -   folder: third_party/benchmark
        sha256: 866d3c8cadb3323251d4fe0e989ea0df51f30660badb73dad0f2d11e5bf1770f
        url: https://github.com/google/benchmark/archive/5b7683f49e1e9223cf9927b24f6fd3d6bd82e3f8.zip
    -   folder: third_party/googletest
        sha256: 8f282e6bf68956bc40bad8ac9743b9ee5c0bf3cd9a91f830fb5749a5ba8d5f76
        url: https://github.com/google/googletest/archive/c3bb0ee2a63279a803aaad956b9b26d74bf9e6e2.zip
build:
    number: '0'
    run_exports:
        - libprotobuf >=3.6.0,<3.6.1.0a0
    string: hd28b015_0
requirements:
    build:
        - autoconf 2.69 pl526_7
        - automake 1.15.1 pl526_1
        - libgcc-ng 7.2.0 hdf63c60_3
        - libtool 2.4.6 h470a237_1
        - m4 1.4.18 0
        - make 4.2.1 h470a237_0
        - perl 5.26.2 h470a237_0
        - pkg-config 0.29.2 h470a237_3
        - toolchain 2.1.6 0
        - toolchain_c_linux-64 2.1.6 0
        - toolchain_cxx_linux-64 2.1.6 0
        - unzip 6.0 0
    host:
        - libgcc-ng 7.2.0 hdf63c60_3
        - libstdcxx-ng 7.2.0 hdf63c60_3
        - zlib 1.2.11 h470a237_3
    run:
        - libgcc-ng >=4.9
        - libstdcxx-ng >=4.9
        - zlib >=1.2.11,<1.3.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - protoc --help
        - test -f ${PREFIX}/lib/libprotobuf.a
        - test -f ${PREFIX}/lib/libprotobuf.so
about:
    description: 'Protocol buffers are Google''s language-neutral,

        platform-neutral, extensible mechanism for serializing structured data-

        think XML, but smaller, faster, and simpler.

        '
    doc_source_url: https://github.com/google/protobuf/releases
    doc_url: https://developers.google.com/protocol-buffers/
    home: https://developers.google.com/protocol-buffers/
    license: BSD 3-Clause
    license_family: BSD
    license_file: LICENSE
    summary: Protocol Buffers - Google's data interchange format. C++ Libraries
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - dopplershift
        - hajapy
        - jakirkham
        - jjhelmus
        - ocefpaf
        - wesm
