# This file created by conda-build 2.1.17
# meta.yaml template originally from:
# /recipe_root, last modified Thu Sep 21 14:04:48 2017
# ------------------------------------------------

package:
    name: six
    version: 1.11.0
source:
    sha256: 70e8a77beed4562e7f14fe23a786b54f6296e34344c23bc42f07b15018ff98e9
    url: https://pypi.io/packages/source/s/six/six-1.11.0.tar.gz
build:
    noarch: ''
    noarch_python: false
    number: '1'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py36_1
requirements:
    build:
        - ncurses 5.9 10
        - readline 6.2 0
        - tk 8.5.19 2
        - ca-certificates 2017.7.27.1 0
        - setuptools 36.3.0 py36_0
        - zlib 1.2.11 0
        - xz 5.2.3 0
        - certifi 2017.7.27.1 py36_0
        - python 3.6.2 0
        - sqlite 3.13.0 1
        - openssl 1.0.2l 0
    run:
        - python
test:
    imports:
        - six
about:
    description: 'Six provides simple utilities for wrapping over differences between

        Python 2 and Python 3. It is intended to support codebases that work on

        both Python 2 and 3 without modification. six consists of only one Python

        file, so it is painless to copy into a project.

        '
    dev_url: https://github.com/benjaminp/six
    doc_url: http://pythonhosted.org/six/
    home: http://pypi.python.org/pypi/six/
    license: MIT
    license_family: MIT
    license_file: LICENSE
    summary: Python 2 and 3 compatibility utilities
extra:
    final: true
    recipe-maintainers:
        - jakirkham
        - msarahan
        - ocefpaf
