# This file created by conda-build 3.10.1
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sat May  5 13:23:44 2018
# ------------------------------------------------

package:
    name: monotonic
    version: '1.5'
source:
    fn: monotonic-1.5.tar.gz
    sha256: 23953d55076df038541e648a53676fb24980f7a1be290cdda21300b3bc21dfb0
    url: https://pypi.io/packages/source/m/monotonic/monotonic-1.5.tar.gz
build:
    noarch: python
    number: '0'
    script: python -m pip install --no-deps --ignore-installed .
    string: py_0
requirements:
    build:
        - ca-certificates 2018.4.16 0
        - certifi 2018.4.16 py27_0
        - ncurses 5.9 10
        - openssl 1.0.2o 0
        - pip 9.0.3 py27_0
        - python 2.7.14 5
        - readline 7.0 0
        - setuptools 39.1.0 py27_0
        - sqlite 3.20.1 2
        - tk 8.6.7 0
        - wheel 0.31.0 py27_0
        - zlib 1.2.11 0
    run:
        - python
test:
    imports:
        - monotonic
about:
    home: https://github.com/atdt/monotonic
    license: Apache 2.0
    license_file: LICENSE
    summary: An implementation of time.monotonic() for Python 2 & Python 3.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - alimanfoo
        - anguslees
        - sodre
