# This file created by conda-build 3.11.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Jul 23 02:58:28 2018
# ------------------------------------------------

package:
    name: xorg-libxau
    version: 1.0.8
source:
    fn: xorg-libXau-1.0.8.tar.bz2
    sha256: fdd477320aeb5cdd67272838722d6b7d544887dfe7de46e1e7cc0c27c2bea4f2
    url: https://www.x.org/releases/individual/lib/libXau-1.0.8.tar.bz2
build:
    detect_binary_files_with_prefix: true
    number: '6'
    string: h470a237_6
requirements:
    build:
        - libgcc-ng 7.2.0 hdf63c60_3
        - pkg-config 0.29.2 hf5063d0_2
        - toolchain 2.1.6 0
        - toolchain_c_linux-64 2.1.6 0
        - zlib 1.2.11 h470a237_3
    host:
        - libgcc-ng 7.2.0 hdf63c60_3
        - xorg-util-macros 1.19.2 h470a237_1
        - xorg-xproto 7.0.31 h470a237_7
    run:
        - libgcc-ng >=4.9
test:
    commands:
        - test -f $PREFIX/lib/libXau.so
        - conda inspect linkages -p $PREFIX $PKG_NAME
about:
    home: https://www.x.org/
    license: MIT
    license_family: MIT
    license_file: COPYING
    summary: A simple X Windows authentication protocol.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - pkgw
