# This file created by conda-build 2.1.17
# meta.yaml template originally from:
# /recipe_root, last modified Sat Nov 25 17:20:09 2017
# ------------------------------------------------

package:
    name: cairo
    version: 1.14.10
source:
    sha256: 7e87878658f2c9951a14fc64114d4958c0e65ac47530b8ac3078b2ce41b66a09
    url: http://cairographics.org/releases/cairo-1.14.10.tar.xz
build:
    features: ''
    noarch: ''
    noarch_python: false
    number: '0'
    string: '0'
requirements:
    build:
        - libiconv 1.15 0
        - libtool 2.4.6 0
        - libpng 1.6.34 0
        - pixman 0.34.0 1
        - zlib 1.2.11 0
        - glib 2.55.0 0
        - xz 5.2.3 0
        - gettext 0.19.7 1
        - fontconfig 2.12.6 0
        - icu 58.2 0
        - libxml2 2.9.5 2
        - pcre 8.39 0
        - freetype 2.8.1 0
        - pkg-config 0.29.1 2
        - libffi 3.2.1 3
    run:
        - freetype 2.8.1
        - fontconfig 2.12.*
        - libpng >=1.6.32,<1.6.35
        - glib 2.55.*
        - pixman 0.34.*
        - zlib 1.2.11
        - icu 58.*
test:
    commands:
        - cairo-trace --help
        - test -f $PREFIX/lib/libcairo.a
        - test -f $PREFIX/lib/libcairo.so
        - test -f $PREFIX/lib/libcairo-gobject.a
        - test -f $PREFIX/lib/libcairo-gobject.so
        - test -f $PREFIX/lib/libcairo-script-interpreter.a
        - test -f $PREFIX/lib/libcairo-script-interpreter.so
        - conda inspect linkages -p $PREFIX $PKG_NAME
about:
    home: http://cairographics.org/
    license: LGPL 2.1 or MPL 1.1
    summary: Cairo is a 2D graphics library with support for multiple output devices.
extra:
    final: true
    recipe-maintainers:
        - ccordoba12
        - jakirkham
        - ocefpaf
        - pkgw
