# This file created by conda-build 3.10.5
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed May 30 05:34:11 2018
# ------------------------------------------------

package:
    name: zlib
    version: 1.2.11
source:
    fn: zlib-1.2.11.tar.gz
    sha256: c3e5e9fdd5004dcb542feda5ee4f0ff0744628baf8ed2dd5d66f8ca1197cb1a1
    url: http://zlib.net/zlib-1.2.11.tar.gz
build:
    number: '3'
    run_exports:
        - zlib >=1.2.11,<1.3.0a0
    string: h470a237_3
requirements:
    build:
        - toolchain 2.1.4 0
        - toolchain_c_linux-64 2.1.4 0
    host:
        - libgcc-ng 7.2.0 hdf63c60_3
    run:
        - libgcc-ng >=4.9
test:
    commands:
        - test -f ${PREFIX}/lib/libz.a
        - conda inspect linkages -p ${PREFIX} zlib
about:
    description: 'zlib is designed to be a free, general-purpose, lossless data-compression

        library for use on virtually any computer hardware and operating system.

        '
    dev_url: https://github.com/madler/zlib
    doc_url: http://zlib.net/manual.html
    home: http://zlib.net/
    license: zlib
    license_family: Other
    license_file: license.txt
    summary: Massively spiffy yet delicately unobtrusive compression library
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - groutr
        - mingwandroid
        - msarahan
        - ocefpaf
