# This file created by conda-build 2.1.18
# meta.yaml template originally from:
# /recipe_root, last modified Wed Feb 28 20:20:11 2018
# ------------------------------------------------

package:
    name: packaging
    version: '17.1'
source:
    sha256: f019b770dd64e585a99714f1fd5e01c7a8f11b45635aa953fd41c689a657375b
    url: https://pypi.io/packages/source/p/packaging/packaging-17.1.tar.gz
build:
    noarch: python
    noarch_python: false
    number: '0'
    script: python -m pip install --no-deps --ignore-installed .
    string: py_0
requirements:
    build:
        - certifi 2018.1.18 py36_0
        - python 3.6.4 0
        - xz 5.2.3 0
        - openssl 1.0.2n 0
        - pip 9.0.1 py36_1
        - readline 7.0 0
        - setuptools 38.5.1 py36_0
        - zlib 1.2.11 0
        - tk 8.6.7 0
        - ca-certificates 2018.1.18 0
        - ncurses 5.9 10
        - six 1.11.0 py36_1
        - pyparsing 2.2.0 py36_0
        - wheel 0.30.0 py36_2
        - sqlite 3.20.1 2
    run:
        - python
        - pyparsing
        - six
test:
    imports:
        - packaging
about:
    home: https://github.com/pypa/packaging
    license: Apache 2.0 or BSD 2-Clause
    license_file: LICENSE
    summary: Core utilities for Python packages
extra:
    final: true
    recipe-maintainers:
        - jakirkham
        - nicoddemus
