# This file created by conda-build 3.10.9
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sat Jul 14 16:36:05 2018
# ------------------------------------------------

package:
    name: bzip2
    version: 1.0.6
source:
    fn: bzip2-1.0.6.tar.gz
    md5: 00b516f4704d4a7cb50a1d97e6e8e15b
    url: http://www.bzip.org/1.0.6/bzip2-1.0.6.tar.gz
build:
    number: '2'
    run_exports:
        - bzip2 >=1.0.6,<2.0a0
    string: h470a237_2
requirements:
    build:
        - toolchain 2.1.6 0
        - toolchain_c_linux-64 2.1.6 0
    host:
        - libgcc-ng 7.2.0 hdf63c60_3
    run:
        - libgcc-ng >=4.9
test:
    commands:
        - bzip2 --help
        - test -f ${PREFIX}/bin/bunzip2
        - test -f ${PREFIX}/bin/bzcat
        - test -f ${PREFIX}/bin/bzcmp
        - test -f ${PREFIX}/bin/bzdiff
        - test -f ${PREFIX}/bin/bzegrep
        - test -f ${PREFIX}/bin/bzfgrep
        - test -f ${PREFIX}/bin/bzgrep
        - test -f ${PREFIX}/bin/bzip2recover
        - test -f ${PREFIX}/bin/bzip2
        - test -f ${PREFIX}/bin/bzless
        - test -f ${PREFIX}/bin/bzmore
        - test -f ${PREFIX}/include/bzlib.h
        - test -f ${PREFIX}/lib/libbz2.a
        - test -f ${PREFIX}/lib/libbz2.so
about:
    description: 'Bzip2 is a freely available high-quality data compressor. It typically

        compresses files to within 10% to 15% of the best available techniques,

        whilst being around twice as fast at compression and six times faster

        at decompression.

        '
    doc_url: http://www.bzip.org/docs.html
    home: http://www.bzip.org/
    license: bzip2
    license_family: BSD
    license_file: LICENSE
    summary: high-quality data compressor
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - jlanga
        - pelson
