# This file created by conda-build 3.13.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sat Aug 25 23:28:06 2018
# ------------------------------------------------

package:
    name: markupsafe
    version: '1.0'
source:
    sha256: a6be69091dac236ea9c6bc7d012beab42010fa914c459791d627dad4910eb665
    url: https://pypi.io/packages/source/M/MarkupSafe/MarkupSafe-1.0.tar.gz
build:
    number: '1'
    script: /home/conda/feedstock_root/build_artifacts/markupsafe_1535239789758/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/python
        -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
    string: py36h470a237_1
requirements:
    build:
        - toolchain 2.1.6 0
        - toolchain_c_linux-64 2.1.6 0
    host:
        - bzip2 1.0.6 h470a237_2
        - ca-certificates 2018.8.24 ha4d7672_0
        - certifi 2018.8.24 py36_1
        - libffi 3.2.1 hfc679d8_4
        - libgcc-ng 7.2.0 hdf63c60_3
        - libstdcxx-ng 7.2.0 hdf63c60_3
        - ncurses 6.1 hfc679d8_1
        - openssl 1.0.2o h470a237_1
        - pip 18.0 py36_1
        - python 3.6.6 h5001a0f_0
        - readline 7.0 haf1bffa_1
        - setuptools 40.2.0 py36_0
        - sqlite 3.24.0 h2f33b56_0
        - tk 8.6.8 0
        - wheel 0.31.1 py36_1
        - xz 5.2.4 h470a237_1
        - zlib 1.2.11 h470a237_3
    run:
        - libgcc-ng >=4.9
        - python >=3.6,<3.7.0a0
test:
    imports:
        - markupsafe
about:
    dev_url: https://github.com/pallets/markupsafe
    home: https://www.palletsprojects.com/p/markupsafe
    license: BSD-3-Clause
    license_family: BSD
    license_file: LICENSE
    summary: A Python module that implements the jinja2.Markup string
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ocefpaf
        - pelson
        - scopatz
