# This file created by conda-build 3.12.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sun Aug  5 01:25:43 2018
# ------------------------------------------------

package:
    name: chardet
    version: 3.0.4
source:
    sha256: 84ab92ed1c4d4f16916e05906b6b75a6c0fb5db821cc65e70cbd64a3e2a5eaae
    url: https://pypi.io/packages/source/c/chardet/chardet-3.0.4.tar.gz
build:
    entry_points:
        - chardetect = chardet.cli.chardetect:main
    number: '3'
    script: /home/conda/feedstock_root/build_artifacts/chardet_1533432411718/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python
        -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
    string: py36_3
requirements:
    host:
        - atomicwrites 1.1.5 py36_0
        - attrs 18.1.0 py_1
        - bzip2 1.0.6 h470a237_2
        - ca-certificates 2018.4.16 0
        - certifi 2018.4.16 py36_0
        - libffi 3.2.1 3
        - libgcc-ng 7.2.0 hdf63c60_3
        - libstdcxx-ng 7.2.0 hdf63c60_3
        - more-itertools 4.2.0 py36_1
        - ncurses 6.1 hfc679d8_1
        - openssl 1.0.2o h470a237_1
        - pip 18.0 py36_1
        - pluggy 0.7.1 py_0
        - py 1.5.4 py_0
        - pytest 3.7.1 py36_0
        - pytest-runner 4.2 py_1
        - python 3.6.6 h5001a0f_0
        - readline 7.0 haf1bffa_1
        - setuptools 40.0.0 py36_1
        - six 1.11.0 py36_1
        - sqlite 3.24.0 h2f33b56_0
        - tk 8.6.8 0
        - wheel 0.31.1 py36_1
        - xz 5.2.4 h470a237_0
        - zlib 1.2.11 h470a237_3
    run:
        - python >=3.6,<3.7.0a0
test:
    commands:
        - chardetect --help
    imports:
        - chardet
about:
    description: 'chardet is a character encoding auto-detector in Python.

        '
    dev_url: https://github.com/chardet/chardet
    doc_source_url: https://github.com/chardet/chardet/blob/master/docs/index.rst
    doc_url: http://chardet.readthedocs.org/
    home: https://github.com/chardet/chardet
    license: LGPL2
    license_family: GPL
    license_file: LICENSE
    summary: Universal character encoding detector
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - dan-blanchard
        - jschueller
        - nehaljwani
        - sigmavirus24
