# This file created by conda-build 3.10.9
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Fri Jul 20 10:52:09 2018
# ------------------------------------------------

package:
    name: bokeh
    version: 0.13.0
source:
    sha256: d0cf59774d7c74b7173b82ce36bde35b8fe9da0f960364ba3c4df0d1fbd874d6
    url: https://pypi.io/packages/source/b/bokeh/bokeh-0.13.0.tar.gz
build:
    entry_points:
        - bokeh = bokeh.__main__:main
    number: '0'
    script: python -m pip install --no-deps --ignore-installed .
    string: py36_0
requirements:
    build:
        - ca-certificates 2018.4.16 0
        - certifi 2018.4.16 py36_0
        - libgcc-ng 7.2.0 hdf63c60_3
        - ncurses 5.9 10
        - openssl 1.0.2o 0
        - pip 9.0.3 py36_0
        - python 3.6.5 1
        - readline 7.0 0
        - setuptools 40.0.0 py36_0
        - sqlite 3.20.1 2
        - tk 8.6.8 0
        - wheel 0.31.1 py36_0
        - xz 5.2.3 0
        - zlib 1.2.11 h470a237_3
    run:
        - jinja2 >=2.7
        - numpy >=1.7.1
        - packaging >=16.8
        - python >=3.6,<3.7.0a0
        - python-dateutil >=2.1
        - pyyaml >=3.10
        - six >=1.5.2
        - tornado >=4.3
test:
    commands:
        - bokeh --help
    imports:
        - bokeh
        - bokeh.application
        - bokeh.application.handlers
        - bokeh.client
        - bokeh.command
        - bokeh.command.subcommands
        - bokeh.core
        - bokeh.core.property
        - bokeh.core.validation
        - bokeh.models
        - bokeh.models.widgets
        - bokeh.plotting
        - bokeh.protocol
        - bokeh.protocol.messages
        - bokeh.sampledata
        - bokeh.server
        - bokeh.server.views
        - bokeh.sphinxext
        - bokeh.themes
        - bokeh.util
about:
    description: 'Bokeh is a Python interactive visualization library that targets

        modern web browsers for presentation. Its goal is to provide elegant,

        concise  construction of novel graphics in the style of D3.js, and to

        extend this capability with high-performance interactivity over very

        large or streaming datasets. Bokeh can help anyone who would like to

        quickly and easily create interactive plots, dashboards, and data

        applications.

        '
    dev_url: http://github.com/bokeh/bokeh
    doc_url: http://bokeh.pydata.org/en/latest/docs/user_guide.html
    home: http://bokeh.pydata.org/
    license: BSD 3-Clause
    license_family: BSD
    license_file: LICENSE.txt
    summary: Statistical and novel interactive HTML plots for Python
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - almarklein
        - jakirkham
        - ocefpaf
