# This file created by conda-build 3.12.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Thu Jul 26 10:49:05 2018
# ------------------------------------------------

package:
    name: zeromq
    version: 4.2.5
source:
    fn: zeromq-4.2.5.tar.gz
    patches:
        - 0003-windows-install.patch
        - rm-clang-format.patch
    sha256: cc9090ba35713d59bb2f7d7965f877036c49c5558ea0c290b0dcc6f2a17e489f
    url: https://github.com/zeromq/libzmq/releases/download/v4.2.5/zeromq-4.2.5.tar.gz
build:
    number: '5'
    string: hfc679d8_5
requirements:
    build:
        - libgcc-ng 7.2.0 hdf63c60_3
        - pkg-config 0.29.2 hf5063d0_2
        - toolchain 2.1.6 0
        - toolchain_c_linux-64 2.1.6 0
        - toolchain_cxx_linux-64 2.1.6 0
        - zlib 1.2.11 h470a237_3
    host:
        - libgcc-ng 7.2.0 hdf63c60_3
        - libsodium 1.0.16 0
        - libstdcxx-ng 7.2.0 hdf63c60_3
    run:
        - libgcc-ng >=4.9
        - libsodium >=1.0.16,<1.0.17.0a0
        - libstdcxx-ng >=4.9
test:
    commands:
        - test -f ${PREFIX}/lib/libzmq.a
        - test -f ${PREFIX}/lib/libzmq.so
        - test -f ${PREFIX}/lib/libzmq.so.5
        - ldd ${PREFIX}/lib/libzmq.so | grep sodium
        - test -f ${PREFIX}/lib/cmake/ZeroMQ/ZeroMQConfig.cmake
        - test -f ${PREFIX}/lib/cmake/ZeroMQ/ZeroMQConfigVersion.cmake
        - ${PREFIX}/bin/curve_keygen
about:
    home: http://zeromq.org
    license: LGPL 3
    summary: A high-performance asynchronous messaging library.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - JohanMabille
        - SylvainCorlay
        - jakirkham
        - minrk
