# This file created by conda-build 3.12.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sun Aug  5 01:23:06 2018
# ------------------------------------------------

package:
    name: cffi
    version: 1.11.5
source:
    patches:
        - setup-linux.patch
    sha256: e90f17980e6ab0f3c2f3730e56d1fe9bcba1891eeea58966e89d352492cc74f4
    url: https://pypi.io/packages/source/c/cffi/cffi-1.11.5.tar.gz
build:
    number: '1'
    script: /home/conda/feedstock_root/build_artifacts/cffi_1533432255747/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python
        -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
    string: py36h5e8e0c9_1
requirements:
    build:
        - toolchain 2.1.6 0
        - toolchain_c_linux-64 2.1.6 0
    host:
        - bzip2 1.0.6 h470a237_2
        - ca-certificates 2018.4.16 0
        - certifi 2018.4.16 py36_0
        - libffi 3.2.1 3
        - libgcc-ng 7.2.0 hdf63c60_3
        - libstdcxx-ng 7.2.0 hdf63c60_3
        - ncurses 6.1 hfc679d8_1
        - openssl 1.0.2o h470a237_1
        - pip 18.0 py36_1
        - pycparser 2.18 py_1
        - python 3.6.6 h5001a0f_0
        - readline 7.0 haf1bffa_1
        - setuptools 40.0.0 py36_1
        - sqlite 3.24.0 h2f33b56_0
        - tk 8.6.8 0
        - wheel 0.31.1 py36_1
        - xz 5.2.4 h470a237_0
        - zlib 1.2.11 h470a237_3
    run:
        - libffi >=3.2.1,<3.3.0a0
        - libgcc-ng >=4.9
        - pycparser
        - python >=3.6,<3.7.0a0
test:
    imports:
        - _cffi_backend
        - cffi
about:
    doc_url: http://cffi.readthedocs.org
    home: https://bitbucket.org/cffi/cffi
    license: MIT
    license_file: LICENSE
    summary: Foreign Function Interface for Python calling C code.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - goanpeca
        - inducer
        - jschueller
        - ocefpaf
