# This file created by conda-build 2.1.18
# meta.yaml template originally from:
# /recipe_root, last modified Wed May 30 10:34:13 2018
# ------------------------------------------------

package:
    name: msprime
    version: 0.5.0
source:
    fn: msprime-0.5.0.tar.gz
    sha256: e1ad0392608f23a66f2192bd052d161fb507aaaa85af5ae4bdd50504ef9b4fa7
    url: https://pypi.io/packages/source/m/msprime/msprime-0.5.0.tar.gz
build:
    entry_points:
        - mspms=msprime.cli:mspms_main
        - msp=msprime.cli:msp_main
    noarch: ''
    noarch_python: false
    number: '3'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py36_3
requirements:
    build:
        - svgwrite 1.1.12 py_0
        - hdf5 1.10.1 2
        - xz 5.2.3 0
        - certifi 2018.4.16 py36_0
        - readline 7.0 0
        - gsl 2.2.1 blas_openblas_4
        - setuptools 39.2.0 py36_0
        - tk 8.6.7 0
        - zlib 1.2.11 h470a237_3
        - setuptools_scm 2.1.0 py36_0
        - blas 1.1 openblas
        - python 3.6.5 1
        - libgfortran 3.0.0 1
        - openblas 0.2.20 8
        - ncurses 5.9 10
        - numpy 1.8.2 py36_blas_openblas_201
        - six 1.11.0 py36_1
        - ca-certificates 2018.4.16 0
        - pyparsing 2.2.0 py36_0
        - sqlite 3.20.1 2
        - openssl 1.0.2o 0
        - libgcc-ng 7.2.0 hdf63c60_3
    run:
        - python
        - svgwrite
        - six
        - numpy >=1.8
        - hdf5 1.10.1
        - h5py
        - gsl ==2.2.1
test:
    commands:
        - mspms --help
        - msp --help
    imports:
        - msprime
about:
    description: Coalescent simulator and library for working with succinct tree sequences.
    dev_url: https://github.com/jeromekelleher/msprime
    doc_url: http://msprime.readthedocs.io/en/stable
    home: http://pypi.python.org/pypi/msprime
    license: GPL-3.0
    license_family: GPL
    license_file: LICENSE
    summary: A fast and accurate coalescent simulator.
extra:
    final: true
    recipe-maintainers:
        - jeromekelleher
