# This file created by conda-build 3.12.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed Jul 25 18:44:39 2018
# ------------------------------------------------

package:
    name: libtool
    version: 2.4.6
source:
    fn: libtool-2.4.6.tar.gz
    sha256: e3bd4d5d3d025a36c21dd6af7ea818a2afcd4dfc1ea5a17b39d7854bcd0c06e3
    url: http://ftpmirror.gnu.org/libtool/libtool-2.4.6.tar.gz
build:
    number: '1'
    string: h470a237_1
requirements:
    build:
        - autoconf 2.69 pl526_7
        - automake 1.15.1 pl526_1
        - libgcc-ng 7.2.0 hdf63c60_3
        - m4 1.4.18 0
        - perl 5.26.2 h470a237_0
        - toolchain 2.1.6 0
        - toolchain_c_linux-64 2.1.6 0
    host:
        - libgcc-ng 7.2.0 hdf63c60_3
    run:
        - libgcc-ng >=4.9
test:
    commands:
        - libtool --help
about:
    home: http://www.gnu.org/software/libtool/
    license: GPL 3
    summary: The GNU Portable Library Tool
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - msarahan
        - ocefpaf
