# This file created by conda-build 3.10.1
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Thu May  3 23:04:10 2018
# ------------------------------------------------

package:
    name: distributed
    version: 1.21.8
source:
    fn: distributed-1.21.8.tar.gz
    sha256: d80c82fc402406703ad7756fc7ce630311c57d883c23ac0021fdfeb674995362
    url: https://pypi.io/packages/source/d/distributed/distributed-1.21.8.tar.gz
build:
    entry_points:
        - dask-mpi=distributed.cli.dask_mpi:go
        - dask-remote=distributed.cli.dask_remote:go
        - dask-scheduler=distributed.cli.dask_scheduler:go
        - dask-ssh=distributed.cli.dask_ssh:go
        - dask-submit=distributed.cli.dask_submit:go
        - dask-worker=distributed.cli.dask_worker:go
    number: '0'
    script: python -m pip install --no-deps --ignore-installed .
    string: py36_0
requirements:
    build:
        - ca-certificates 2018.4.16 0
        - certifi 2018.4.16 py36_0
        - ncurses 5.9 10
        - openssl 1.0.2o 0
        - pip 9.0.3 py36_0
        - python 3.6.5 1
        - readline 7.0 0
        - setuptools 39.1.0 py36_0
        - sqlite 3.20.1 2
        - tk 8.6.7 0
        - wheel 0.31.0 py36_0
        - xz 5.2.3 0
        - zlib 1.2.11 0
    run:
        - click >=6.6
        - cloudpickle >=0.2.2
        - cytoolz >=0.7.4
        - dask-core >=0.17.0
        - msgpack-python
        - psutil
        - python >=3.6,<3.7.0a0
        - pyyaml
        - six
        - sortedcontainers
        - tblib
        - toolz >=0.7.4
        - tornado >=4.5.1
        - zict >=0.1.3
test:
    commands:
        - dask-scheduler --help
        - dask-ssh --help
        - dask-worker --help
    imports:
        - distributed
        - distributed.cli
        - distributed.comm
        - distributed.deploy
        - distributed.diagnostics
        - distributed.protocol
about:
    home: http://distributed.readthedocs.io/en/latest/
    license: BSD 3-Clause
    license_file: LICENSE.txt
    summary: Distributed computing with Dask
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jcrist
        - martindurant
        - mrocklin
        - pitrou
