# This file created by conda-build 3.12.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Jul 30 11:46:14 2018
# ------------------------------------------------

package:
    name: gstreamer
    version: 1.12.5
source:
    sha256: 9f750d845a326880b24c1ccc913d07df8f38cd9e63009714795ae175b6c29c6a
    url: https://gstreamer.freedesktop.org/src/gstreamer/gstreamer-1.12.5.tar.xz
build:
    number: '0'
    run_exports:
        - gstreamer >=1.12.5,<1.13.0a0
    string: h61a6719_0
requirements:
    build:
        - bison 3.0.5 0
        - flex 2.6.4 0
        - libgcc-ng 7.2.0 hdf63c60_3
        - libiconv 1.15 h470a237_1
        - m4 1.4.18 0
        - perl 5.26.2 h470a237_0
        - toolchain 2.1.6 0
        - toolchain_c_linux-64 2.1.6 0
    host:
        - gettext 0.19.8.1 0
        - glib 2.55.0 h464dc38_2
        - libffi 3.2.1 3
        - libgcc-ng 7.2.0 hdf63c60_3
        - libiconv 1.15 h470a237_1
        - pcre 8.41 h470a237_2
        - xz 5.2.4 h470a237_0
        - zlib 1.2.11 h470a237_3
    run:
        - glib >=2.55.0,<2.56.0a0
        - libgcc-ng >=4.9
        - xz >=5.2.4,<5.3.0a0
test:
    commands:
        - gst-inspect-1.0 --version
        - gst-launch-1.0  --version
        - gst-stats-1.0 --version
        - gst-typefind-1.0 --version
about:
    dev_url: https://cgit.freedesktop.org/gstreamer/gstreamer/tree/
    doc_source_url: https://cgit.freedesktop.org/gstreamer/gstreamer/tree/docs
    doc_url: https://gstreamer.freedesktop.org/documentation/
    home: http://gstreamer.freedesktop.org/
    license: LGPL 2
    summary: Library for constructing graphs of media-handling components
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ccordoba12
        - mingwandroid
