# This file created by conda-build 2.1.18
# meta.yaml template originally from:
# /opt/recipe, last modified Sat Jan 27 12:57:20 2018
# ------------------------------------------------

package:
    name: htslib
    version: '1.7'
source:
    fn: htslib-1.7.tar.bz2
    sha256: be3d4e25c256acdd41bebb8a7ad55e89bb18e2fc7fc336124b1e2c82ae8886c6
    url: https://github.com/samtools/htslib/releases/download/1.7/htslib-1.7.tar.bz2
build:
    noarch: ''
    noarch_python: false
    number: '0'
    string: '0'
requirements:
    build:
        - mpfr 3.1.5 0
        - xz 5.2.3 0
        - ca-certificates 2017.11.5 0
        - cloog 0.18.0 0
        - isl 0.12.2 0
        - openssl 1.0.2n 0
        - mpc 1.0.3 4
        - bzip2 1.0.6 1
        - zlib 1.2.11 0
        - gmp 6.1.2 0
        - libssh2 1.8.0 2
        - gcc 4.8.5 7
        - krb5 1.14.2 0
        - curl 7.55.1 0
    run:
        - libgcc
        - curl
        - bzip2 1.0*
        - xz 5.2*
about:
    home: https://github.com/samtools/htslib
    license: MIT
    summary: C library for high-throughput sequencing data formats.
extra:
    final: true
