# This file created by conda-build 3.10.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed May 16 02:29:08 2018
# ------------------------------------------------

package:
    name: python-dateutil
    version: 2.7.3
source:
    sha256: e27001de32f627c22380a688bcc43ce83504a7bc5da472209b4c70f02829f0b8
    url: https://pypi.io/packages/source/p/python-dateutil/python-dateutil-2.7.3.tar.gz
build:
    noarch: python
    number: '0'
    script: python -m pip install --no-deps --ignore-installed .
    string: py_0
requirements:
    build:
        - ca-certificates 2018.4.16 0
        - certifi 2018.4.16 py27_0
        - ncurses 5.9 10
        - openssl 1.0.2o 0
        - pip 9.0.3 py27_0
        - python 2.7.15 0
        - readline 7.0 0
        - setuptools 39.1.0 py27_0
        - setuptools_scm 2.1.0 py27_0
        - sqlite 3.20.1 2
        - tk 8.6.7 0
        - wheel 0.31.0 py27_0
        - zlib 1.2.11 0
    run:
        - python
        - six
test:
    imports:
        - dateutil
        - dateutil.rrule
about:
    description: 'The dateutil module provides powerful extensions to the standard
        datetime

        module, available in Python.

        '
    dev_url: https://github.com/dateutil/dateutil/
    doc_url: https://dateutil.readthedocs.org/en/latest/
    home: https://dateutil.readthedocs.org/
    license: BSD 3 Clause
    license_file: LICENSE
    summary: Extensions to the standard Python datetime module.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - msarahan
        - ocefpaf
