# This file created by conda-build 2.1.17
# meta.yaml template originally from:
# /recipe_root, last modified Thu Nov 16 16:17:24 2017
# ------------------------------------------------

package:
    name: scikit-learn
    version: 0.19.1
source:
    sha256: 2947f531ad52e81b2436b26608d8198778ac0b4baa7d2925db8b3b3fcb39c8a2
    url: https://github.com/scikit-learn/scikit-learn/archive/0.19.1.tar.gz
build:
    features:
        - blas_openblas
    noarch: ''
    noarch_python: false
    number: '201'
    string: py36_blas_openblas_201
requirements:
    build:
        - ncurses 5.9 10
        - readline 6.2 0
        - tk 8.5.19 2
        - ca-certificates 2017.7.27.1 0
        - libgfortran 3.0.0 1
        - setuptools 36.6.0 py36_1
        - numpy 1.9.3 py36_blas_openblas_203
        - blas 1.1 openblas
        - zlib 1.2.11 0
        - scipy 1.0.0 py36_blas_openblas_201
        - xz 5.2.3 0
        - certifi 2017.7.27.1 py36_0
        - sqlite 3.13.0 1
        - openssl 1.0.2l 0
        - nose 1.3.7 py36_2
        - python 3.6.3 1
        - cython 0.27.3 py36_0
        - openblas 0.2.20 4
    run:
        - python
        - blas 1.1 openblas
        - openblas 0.2.20|0.2.20.*
        - numpy >=1.9
        - scipy
test:
    commands:
        - nosetests sklearn --exe
        - conda inspect linkages -p $PREFIX scikit-learn
    imports:
        - sklearn
    requires:
        - nose
about:
    home: http://scikit-learn.org/
    license: BSD 3-Clause
    license_file: COPYING
    summary: A set of python modules for machine learning and data mining
extra:
    final: true
    recipe-maintainers:
        - amueller
        - astaric
        - jakirkham
        - ogrisel
        - ocefpaf
        - lesteve
