# This file created by conda-build 2.1.18
# meta.yaml template originally from:
# /opt/recipe, last modified Tue Mar 13 18:47:32 2018
# ------------------------------------------------

package:
    name: snakemake
    version: 4.8.0
source:
    fn: snakemake-4.8.0.tar.gz
    sha256: 778b7edfc29fb45356e0ab1059ad3d3255baf074996a274f25a5e34f11580aee
    url: https://pypi.io/packages/source/s/snakemake/snakemake-4.8.0.tar.gz
build:
    entry_points:
        - snakemake = snakemake:main
        - snakemake-bash-completion = snakemake:bash_completion
    noarch: ''
    noarch_python: false
    number: '0'
    script: python setup.py install --single-version-externally-managed --record record.txt
    string: py36_0
requirements:
    build:
        - cffi 1.11.5 py36_0
        - datrie 0.7.1 py36_0
        - certifi 2018.1.18 py36_0
        - pyopenssl 17.5.0 py36_0
        - python 3.6.4 0
        - xz 5.2.3 0
        - cryptography 2.1.4 py36_0
        - openssl 1.0.2n 0
        - setuptools 38.5.2 py36_0
        - configargparse 0.12.0 py36_0
        - pip 9.0.1 py36_1
        - requests 2.18.4 py36_1
        - readline 7.0 0
        - chardet 3.0.4 py36_0
        - ratelimiter 1.2.0 py36_0
        - urllib3 1.22 py36_0
        - zlib 1.2.11 0
        - pycparser 2.18 py36_0
        - asn1crypto 0.24.0 py36_0
        - libffi 3.2.1 3
        - tk 8.6.7 0
        - pysocks 1.6.8 py36_1
        - idna 2.6 py36_1
        - appdirs 1.4.3 py_0
        - ca-certificates 2018.1.18 0
        - wrapt 1.10.11 py36_0
        - ncurses 5.9 10
        - six 1.11.0 py36_1
        - wheel 0.30.0 py36_2
        - sqlite 3.20.1 2
    run:
        - python
        - wrapt
        - requests
        - docutils
        - pyyaml
        - datrie
        - requests >=2.8.1
        - dropbox >=7.2.1
        - ftputil >=3.2
        - filechunkio >=1.6
        - pysftp >=0.2.8
        - psutil
        - aioeasywebdav
        - pandas
        - ratelimiter
        - configargparse
        - appdirs
        - python-irodsclient
        - google-cloud-storage
        - boto3
        - aioeasywebdav
test:
    commands:
        - snakemake --version
        - snakemake --version | grep "4.8.0"
    imports:
        - snakemake
about:
    home: https://snakemake.readthedocs.io
    license: MIT
    summary: Snakemake is a workflow management system that aims to reduce the complexity
        of creating workflows by providing a fast and comfortable execution environment,
        together with a clean and modern specification language in python style. Snakemake
        workflows are essentially Python scripts extended by declarative code to define
        rules. Rules describe how to create output files from input files.
extra:
    final: true
