# This file created by conda-build 2.1.18
# meta.yaml template originally from:
# /recipe_root, last modified Sun Mar 25 03:24:34 2018
# ------------------------------------------------

package:
    name: scipy
    version: 1.0.1
source:
    sha256: a0eaaa6b6958db9d89f8ef0ce23391fedebac3fb416e05bdd966e6895dd6cd3d
    url: https://github.com/scipy/scipy/archive/v1.0.1.tar.gz
build:
    features:
        - blas_openblas
    noarch: ''
    noarch_python: false
    number: '200'
    string: py36_blas_openblas_200
requirements:
    build:
        - certifi 2018.1.18 py36_0
        - python 3.6.4 0
        - xz 5.2.3 0
        - openssl 1.0.2n 0
        - openblas 0.2.20 7
        - readline 7.0 0
        - zlib 1.2.11 0
        - tk 8.6.7 0
        - setuptools 39.0.1 py36_0
        - blas 1.1 openblas
        - numpy 1.9.3 py36_blas_openblas_203
        - cython 0.28.1 py36_0
        - libgfortran 3.0.0 1
        - ca-certificates 2018.1.18 0
        - ncurses 5.9 10
        - sqlite 3.20.1 2
        - toolchain 2.1.2 0
    run:
        - python
        - blas 1.1 openblas
        - libgfortran
        - openblas 0.2.20|0.2.20*
        - numpy >=1.9
test:
    commands:
        - conda inspect linkages -p $PREFIX scipy
    requires:
        - pytest
        - mpmath
about:
    description: 'SciPy is a Python-based ecosystem of open-source software for mathematics,

        science, and engineering.

        '
    dev_url: https://github.com/scipy/scipy
    doc_url: http://www.scipy.org/docs.html
    home: http://www.scipy.org/
    license: BSD 3-Clause
    license_file: LICENSE.txt
    summary: Scientific Library for Python
extra:
    final: true
    recipe-maintainers:
        - jakirkham
        - msarahan
        - rgommers
        - ocefpaf
