# This file created by conda-build 2.1.18
# meta.yaml template originally from:
# /recipe_root, last modified Fri Jan  5 03:51:37 2018
# ------------------------------------------------

package:
    name: click
    version: '6.7'
source:
    fn: click-6.7.tar.gz
    sha256: f15516df478d5a56180fbf80e68f206010e6d160fc39fa508b65e035fd75130b
    url: https://pypi.io/packages/source/c/click/click-6.7.tar.gz
build:
    noarch: python
    noarch_python: false
    number: '1'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py_1
requirements:
    build:
        - python 3.6.4 0
        - xz 5.2.3 0
        - ca-certificates 2017.11.5 0
        - openssl 1.0.2n 0
        - readline 7.0 0
        - zlib 1.2.11 0
        - certifi 2017.11.5 py36_0
        - tk 8.6.7 0
        - setuptools 38.2.4 py36_0
        - ncurses 5.9 10
        - sqlite 3.20.1 2
    run:
        - python
test:
    imports:
        - click
about:
    dev_url: https://github.com/pallets/click
    doc_url: http://click.pocoo.org/
    home: http://click.pocoo.org/
    license: BSD 3-Clause
    license_family: BSD
    license_file: LICENSE
    summary: A simple wrapper around optparse for powerful command line utilities.
extra:
    final: true
    recipe-maintainers:
        - pmlandwehr
