# This file created by conda-build 3.10.9
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed Jul 18 21:17:24 2018
# ------------------------------------------------

package:
    name: pandoc
    version: 2.2.2
source:
    sha256: 7d74d96f231960fde9a611803dd9b5047128d9f264062ec02c38c4a3dbf520e2
    url: https://github.com/jgm/pandoc/releases/download/2.2.2/pandoc-2.2.2-1-amd64.deb
build:
    number: '1'
    string: '1'
requirements:
    run:
        - gmp
        - zlib 1.2.11.*
test:
    commands:
        - pandoc --help
        - pandoc --version
about:
    home: http://pandoc.org/
    license: GPL-2.0
    summary: Universal markup converter (repackaged binaries).
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - dhimmel
        - jankatins
        - ocefpaf
