# This file created by conda-build 2.1.18
# meta.yaml template originally from:
# /recipe_root, last modified Mon Apr  2 13:43:56 2018
# ------------------------------------------------

package:
    name: backcall
    version: 0.1.0
source:
    fn: backcall-0.1.0.tar.gz
    sha256: 38ecd85be2c1e78f77fd91700c76e14667dc21e2713b63876c0eb901196e01e4
    url: https://pypi.io/packages/source/b/backcall/backcall-0.1.0.tar.gz
build:
    noarch: python
    noarch_python: false
    number: '0'
    script: python -m pip install --no-deps --ignore-installed .
    string: py_0
requirements:
    build:
        - certifi 2018.1.18 py36_0
        - xz 5.2.3 0
        - openssl 1.0.2n 0
        - readline 7.0 0
        - zlib 1.2.11 0
        - tk 8.6.7 0
        - setuptools 39.0.1 py36_0
        - pip 9.0.3 py36_0
        - ca-certificates 2018.1.18 0
        - ncurses 5.9 10
        - python 3.6.5 0
        - wheel 0.30.0 py36_2
        - sqlite 3.20.1 2
    run:
        - python
test:
    imports:
        - backcall
about:
    description: 'Backcall provides a way of specifying the parameters that callback
        functions

        need to accept, and adapting callbacks that take fewer parameters, so you

        can add parameters to your callback API without breaking code that doesn''t

        know about them.

        '
    home: https://github.com/takluyver/backcall/
    license: BSD-3-Clause
    license_family: BSD
    summary: Specifications for callback functions passed in to an API
extra:
    final: true
    recipe-maintainers:
        - takluyver
