# This file created by conda-build 3.7.0
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/cffi-1.11.5-python_3.6-on-linux_64, last modified Tue Mar  6 18:18:33 2018
# ------------------------------------------------

package:
    name: cffi
    version: 1.11.5
source:
    patches:
        - 0001-Link-to-dl-library.patch
        - setup-linux.patch
    sha256: e90f17980e6ab0f3c2f3730e56d1fe9bcba1891eeea58966e89d352492cc74f4
    url: https://pypi.io/packages/source/c/cffi/cffi-1.11.5.tar.gz
build:
    number: '0'
    script: python -m pip install --no-deps --ignore-installed .
    string: py36h9745a5d_0
requirements:
    build:
        - binutils_impl_linux-64 2.28.1 h04c84fa_2
        - binutils_linux-64 7.2.0 25
        - gcc_impl_linux-64 7.2.0 hc5ce805_2
        - gcc_linux-64 7.2.0 25
        - libstdcxx-ng 7.2.0 h7a57d05_2
    host:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2018.1.18 py36_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - ncurses 6.0 h9df7e31_2
        - openssl 1.0.2n hb7f436b_0
        - pip 9.0.1 py36_5
        - pycparser 2.18 py36hf9f622e_1
        - python 3.6.4 hc3d631a_1
        - readline 7.0 ha6073c6_4
        - setuptools 38.5.1 py36_0
        - sqlite 3.22.0 h1bed415_0
        - tk 8.6.7 hc745277_3
        - wheel 0.30.0 py36hfd4bba0_1
        - xz 5.2.3 h55aa19d_2
        - zlib 1.2.11 ha838bed_2
    run:
        - libffi
        - libffi >=3.2.1,<4.0a0
        - libgcc-ng >=7.2.0
        - pycparser
        - python >=3.6,<3.7.0a0
test:
    imports:
        - _cffi_backend
        - cffi
about:
    description: 'Cffi aims to allow users to call C code from Python without having
        to

        learn a 3rd language. It provides a convenient and reliable way to call

        compiled C code from Python using interface declarations written in C.

        '
    dev_url: https://bitbucket.org/cffi/cffi/overview
    doc_source_url: https://bitbucket.org/cffi/cffi/src/default/doc/?at=default
    doc_url: http://cffi.readthedocs.org
    home: https://bitbucket.org/cffi/cffi
    license: MIT
    license_file: LICENSE
    summary: Foreign Function Interface for Python calling C code.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - goanpeca
        - inducer
        - jschueller
        - mingwandroid
        - ocefpaf
