# This file created by conda-build 2.1.6
# meta.yaml template originally from:
# /recipe_root, last modified Wed Mar 15 16:19:45 2017
# ------------------------------------------------

package:
    name: traitlets
    version: 4.3.2
source:
    fn: traitlets-4.3.2.tar.gz
    sha256: 9c4bd2d267b7153df9152698efb1050a5d84982d3384a37b2c1f7723ba3e7835
    url: https://pypi.io/packages/source/t/traitlets/traitlets-4.3.2.tar.gz
build:
    noarch: ''
    noarch_python: false
    number: '0'
    script: pip install --no-deps .
    string: py36_0
requirements:
    build:
        - xz 5.2.2 0
        - certifi 2017.1.23 py36_0
        - ncurses 5.9 10
        - pip 9.0.1 py36_0
        - wheel 0.29.0 py36_0
        - zlib 1.2.11 0
        - setuptools 33.1.0 py36_0
        - tk 8.5.19 1
        - python 3.6.0 2
        - openssl 1.0.2h 3
        - readline 6.2 0
        - ca-certificates 2017.1.23 0
        - sqlite 3.13.0 1
    run:
        - python
        - ipython_genutils
        - six
        - decorator
test:
    imports:
        - traitlets
        - traitlets.config
about:
    home: http://ipython.org/
    license: BSD 3-clause
    summary: Configuration system for Python applications
extra:
    final: true
    recipe-maintainers:
        - jakirkham
        - pelson
        - minrk
        - SylvainCorlay
