# This file created by conda-build 2.1.18
# meta.yaml template originally from:
# /recipe_root, last modified Wed Feb 28 03:39:18 2018
# ------------------------------------------------

package:
    name: idna_ssl
    version: 1.0.0
source:
    fn: idna_ssl-1.0.0.tar.gz
    sha256: 1227e44039bd31e02adaeafdbba61281596d623d222643fb021f87f2144ea147
    url: https://pypi.io/packages/source/i/idna_ssl/idna_ssl-1.0.0.tar.gz
build:
    noarch: python
    noarch_python: false
    number: '0'
    script: python -m pip install --no-deps --ignore-installed .
    string: '0'
requirements:
    build:
        - certifi 2018.1.18 py36_0
        - python 3.6.4 0
        - xz 5.2.3 0
        - openssl 1.0.2n 0
        - pip 9.0.1 py36_1
        - readline 7.0 0
        - setuptools 38.5.1 py36_0
        - zlib 1.2.11 0
        - tk 8.6.7 0
        - ca-certificates 2018.1.18 0
        - ncurses 5.9 10
        - wheel 0.30.0 py36_2
        - sqlite 3.20.1 2
    run:
        - python >=3.5,<3.7
        - idna
test:
    imports:
        - idna_ssl
about:
    dev_url: https://github.com/aio-libs/idna-ssl
    home: https://github.com/aio-libs/idna-ssl
    license: MIT
    license_family: MIT
    license_file: LICENSE
    summary: Patch ssl.match_hostname for Unicode(idna) domains support
extra:
    final: true
    recipe-maintainers:
        - sodre
