# This file created by conda-build 2.1.18
# meta.yaml template originally from:
# /recipe_root, last modified Thu Mar  1 18:52:48 2018
# ------------------------------------------------

package:
    name: ftputil
    version: '3.4'
source:
    fn: ftputil-3.4.tar.gz
    md5: 244fc130a445ac3c4d38545479379af2
    url: https://pypi.io/packages/source/f/ftputil/ftputil-3.4.tar.gz
build:
    noarch: python
    noarch_python: false
    number: '0'
    script: python -m pip install --no-deps --ignore-installed .
    string: py_0
requirements:
    build:
        - certifi 2018.1.18 py36_0
        - python 3.6.4 0
        - xz 5.2.3 0
        - openssl 1.0.2n 0
        - pip 9.0.1 py36_1
        - readline 7.0 0
        - setuptools 38.5.1 py36_0
        - zlib 1.2.11 0
        - tk 8.6.7 0
        - ca-certificates 2018.1.18 0
        - ncurses 5.9 10
        - wheel 0.30.0 py36_2
        - sqlite 3.20.1 2
    run:
        - python
test:
    commands:
        - python -c "from ftputil import FTPHost"
    imports:
        - ftputil
about:
    description: 'ftputil is a high-level FTP client library for the Python programming

        language. ftputil implements a virtual file system for accessing FTP

        servers, that is, it can generate file-like objects for remote files.

        The library supports many functions similar to those in the os, os.path

        and shutil modules. ftputil has convenience functions for conditional

        uploads and downloads, and handles FTP clients and servers in different

        timezones.

        '
    doc_url: http://ftputil.sschwarzer.net/trac/wiki/Documentation
    home: http://ftputil.sschwarzer.net/
    license: BSD 3-Clause
    summary: High-level FTP client library (virtual file system and more)
extra:
    final: true
    recipe-maintainers:
        - edisongustavo
        - nicoddemus
        - tadeu
