# This file created by conda-build 2.1.18
# meta.yaml template originally from:
# /opt/recipe, last modified Thu Mar  1 17:47:59 2018
# ------------------------------------------------

package:
    name: samtools
    version: '1.7'
source:
    fn: samtools-1.7.tar.bz2
    sha256: e7b09673176aa32937abd80f95f432809e722f141b5342186dfef6a53df64ca1
    url: https://github.com/samtools/samtools/releases/download/1.7/samtools-1.7.tar.bz2
build:
    noarch: ''
    noarch_python: false
    number: '2'
    string: '2'
requirements:
    build:
        - mpfr 3.1.5 0
        - xz 5.2.3 0
        - cloog 0.18.0 0
        - isl 0.12.2 0
        - openssl 1.0.2n 0
        - mpc 1.0.3 4
        - bzip2 1.0.6 1
        - zlib 1.2.11 0
        - gmp 6.1.2 0
        - libssh2 1.8.0 2
        - gcc 4.8.5 7
        - krb5 1.14.2 0
        - ca-certificates 2018.1.18 0
        - ncurses 5.9 10
        - curl 7.55.1 0
    run:
        - libgcc
        - ncurses 5.9*
        - zlib 1.2.11*
        - bzip2 1.0*
        - curl
        - xz 5.2*
test:
    commands:
        - samtools --help
about:
    home: https://github.com/samtools/samtools
    license: MIT
    summary: Tools for dealing with SAM, BAM and CRAM files
extra:
    final: true
