# This file created by conda-build 3.10.9
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Jul  9 11:15:07 2018
# ------------------------------------------------

package:
    name: jupyter_client
    version: 5.2.3
source:
    fn: jupyter_client-5.2.3.tar.gz
    sha256: 27befcf0446b01e29853014d6a902dd101ad7d7f94e2252b1adca17c3466b761
    url: https://pypi.io/packages/source/j/jupyter_client/jupyter_client-5.2.3.tar.gz
build:
    entry_points:
        - jupyter-kernelspec = jupyter_client.kernelspecapp:KernelSpecApp.launch_instance
        - jupyter-run = jupyter_client.runapp:main
    noarch: python
    number: '1'
    script: python -m pip install --no-deps --ignore-installed .
    string: py_1
requirements:
    host:
        - ca-certificates 2018.4.16 0
        - certifi 2018.4.16 py27_0
        - libgcc-ng 7.2.0 hdf63c60_3
        - ncurses 5.9 10
        - openssl 1.0.2o 0
        - pip 9.0.3 py27_0
        - python 2.7.15 0
        - readline 7.0 0
        - setuptools 39.2.0 py27_0
        - sqlite 3.20.1 2
        - tk 8.6.7 0
        - wheel 0.31.1 py27_0
        - zlib 1.2.11 h470a237_3
    run:
        - jupyter_core
        - python
        - python-dateutil >=2.1
        - pyzmq >=13
        - tornado
        - traitlets
test:
    commands:
        - jupyter kernelspec list
        - jupyter run -h
    imports:
        - jupyter_client
about:
    home: http://jupyter.org
    license: BSD 3-clause
    license_file: COPYING.md
    summary: jupyter_client contains the reference implementation of the Jupyter protocol.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - carreau
        - jakirkham
        - minrk
        - ocefpaf
        - pelson
