# This file created by conda-build 3.10.9
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sun Jun 24 16:32:06 2018
# ------------------------------------------------

package:
    name: icu
    version: '58.2'
source:
    sha256: 2b0a4410153a9b20de0e20c7d8b66049a72aef244b53683d0d7521371683da0c
    url: http://download.icu-project.org/files/icu4c/58.2/icu4c-58_2-src.tgz
build:
    number: '0'
    string: hfc679d8_0
requirements:
    build:
        - toolchain 2.1.5 0
        - toolchain_c_linux-64 2.1.5 0
        - toolchain_cxx_linux-64 2.1.5 0
    host:
        - libgcc-ng 7.2.0 hdf63c60_3
        - libstdcxx-ng 7.2.0 hdf63c60_3
    run:
        - libgcc-ng >=4.9
        - libstdcxx-ng >=4.9
test:
    commands:
        - test -f $PREFIX/lib/libicudata.a
        - test -f $PREFIX/lib/libicudata.so.58.2
        - test -f $PREFIX/lib/libicui18n.a
        - test -f $PREFIX/lib/libicui18n.so.58.2
        - test -f $PREFIX/lib/libicuio.a
        - test -f $PREFIX/lib/libicuio.so.58.2
        - test -f $PREFIX/lib/libicutest.a
        - test -f $PREFIX/lib/libicutest.so.58.2
        - test -f $PREFIX/lib/libicutu.a
        - test -f $PREFIX/lib/libicutu.so.58.2
        - test -f $PREFIX/lib/libicuuc.a
        - test -f $PREFIX/lib/libicuuc.so.58.2
        - genbrk --help
        - gencfu --help
        - gencnval --help
        - gendict --help
        - icuinfo --help
        - icu-config --help
        - makeconv gb-18030-2000.ucm
        - conda inspect linkages -p $PREFIX $PKG_NAME
    files:
        - de.txt
        - gb-18030-2000.ucm
about:
    home: http://site.icu-project.org/
    license: MIT
    license_file: LICENSE
    summary: International Components for Unicode.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ccordoba12
        - jakirkham
        - msarahan
        - ocefpaf
