# This file created by conda-build 3.13.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Thu Aug 30 21:30:43 2018
# ------------------------------------------------

package:
    name: botocore
    version: 1.11.5
source:
    fn: botocore-1.11.5.tar.gz
    sha256: 4a2d4fc68fdc7113957cfc51b733a9900a9ba35e19e6d841a8b11fd6c20732f9
    url: https://pypi.org/packages/source/b/botocore/botocore-1.11.5.tar.gz
build:
    noarch: python
    number: '0'
    script: python -m pip install --no-deps --ignore-installed .
    string: py_0
requirements:
    host:
        - bzip2 1.0.6 h470a237_2
        - ca-certificates 2018.8.24 ha4d7672_0
        - certifi 2018.8.24 py27_1
        - libgcc-ng 7.2.0 hdf63c60_3
        - libstdcxx-ng 7.2.0 hdf63c60_3
        - ncurses 6.1 hfc679d8_1
        - openssl 1.0.2p h470a237_0
        - pip 18.0 py27_1
        - python 2.7.15 h9fef7bc_0
        - readline 7.0 haf1bffa_1
        - setuptools 40.2.0 py27_0
        - sqlite 3.24.0 h2f33b56_0
        - tk 8.6.8 0
        - wheel 0.31.1 py27_1
        - zlib 1.2.11 h470a237_3
    run:
        - docutils >=0.10
        - jmespath >=0.7.1,<1.0.0
        - python
        - python-dateutil >=2.1,<3.0.0
        - urllib3 >=1.20,<1.24
test:
    imports:
        - botocore
        - botocore.docs
        - botocore.docs.bcdoc
        - botocore.vendored
        - botocore.vendored.requests
        - botocore.vendored.requests.packages
        - botocore.vendored.requests.packages.chardet
        - botocore.vendored.requests.packages.urllib3
        - botocore.vendored.requests.packages.urllib3.contrib
        - botocore.vendored.requests.packages.urllib3.packages
        - botocore.vendored.requests.packages.urllib3.packages.ssl_match_hostname
        - botocore.vendored.requests.packages.urllib3.util
about:
    description: 'Provides the core functionality of Boto3, the AWS SDK for Python

        '
    dev_url: https://github.com/boto/botocore
    doc_url: https://botocore.readthedocs.io/en/latest/
    home: http://aws.amazon.com/sdk-for-python/
    license: Apache 2.0
    license_family: Apache
    license_file: LICENSE.txt
    license_url: http://aws.amazon.com/apache2.0/
    summary: Low-level, data-driven core of boto 3.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - hajapy
        - pmlandwehr
        - tkelman
