# This file created by conda-build 2.1.17
# meta.yaml template originally from:
# /recipe_root, last modified Tue Aug 15 02:20:52 2017
# ------------------------------------------------

package:
    name: wrapt
    version: 1.10.11
source:
    fn: wrapt-1.10.11.tar.gz
    sha256: d4d560d479f2c21e1b5443bbd15fe7ec4b37fe7e53d335d3b9b0a7b1226fe3c6
    url: https://pypi.io/packages/source/w/wrapt/wrapt-1.10.11.tar.gz
build:
    noarch: ''
    noarch_python: false
    number: '0'
    script: python setup.py install
    string: py36_0
requirements:
    build:
        - ncurses 5.9 10
        - readline 6.2 0
        - tk 8.5.19 2
        - ca-certificates 2017.7.27.1 0
        - zlib 1.2.11 0
        - python 3.6.2 0
        - sqlite 3.13.0 1
        - openssl 1.0.2l 0
        - xz 5.2.2 0
    run:
        - python
test:
    imports:
        - wrapt
about:
    description: 'The aim of the wrapt module is to provide a transparent object proxy
        for

        Python, which can be used as the basis for the construction of function

        wrappers and decorator functions.

        '
    dev_url: https://github.com/GrahamDumpleton/wrapt
    doc_source_url: https://github.com/GrahamDumpleton/wrapt/blob/master/docs/index.rst
    doc_url: http://wrapt.readthedocs.org/en/latest/
    home: https://github.com/GrahamDumpleton/wrapt
    license: BSD 2-Clause
    license_file: LICENSE
    summary: Module for decorators, wrappers and monkey patching.
extra:
    final: true
    recipe-maintainers:
        - jakirkham
        - nehaljwani
