# This file created by conda-build 2.1.18
# meta.yaml template originally from:
# /recipe_root, last modified Tue Apr  3 17:29:25 2018
# ------------------------------------------------

package:
    name: pillow
    version: 5.1.0
source:
    sha256: cee9bc75bff455d317b6947081df0824a8f118de2786dc3d74a3503fd631f4ef
    url: https://pypi.io/packages/source/P/Pillow/Pillow-5.1.0.tar.gz
build:
    noarch: ''
    noarch_python: false
    number: '0'
    string: py36_0
requirements:
    build:
        - freetype 2.8.1 0
        - certifi 2018.1.18 py36_0
        - libpng 1.6.34 0
        - xz 5.2.3 0
        - openssl 1.0.2n 0
        - readline 7.0 0
        - zlib 1.2.11 0
        - tk 8.6.7 0
        - jpeg 9b 2
        - setuptools 39.0.1 py36_0
        - ca-certificates 2018.1.18 0
        - ncurses 5.9 10
        - python 3.6.5 0
        - sqlite 3.20.1 2
        - libtiff 4.0.9 0
    run:
        - python
        - jpeg 9*
        - zlib 1.2.11
        - freetype 2.8.1
        - libtiff >=4.0.8,<4.0.10
        - olefile
        - tk 8.6.*
test:
    commands:
        - conda inspect linkages -p $PREFIX $PKG_NAME
    imports:
        - PIL
        - PIL.Image
about:
    home: https://pillow.readthedocs.io
    license: PIL
    license_file: LICENSE
    summary: Pillow is the friendly PIL fork by Alex Clark and Contributors.
extra:
    final: true
    recipe-maintainers:
        - jakirkham
        - patricksnape
        - pelson
        - ocefpaf
