# This file created by conda-build 3.13.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sun Aug 26 15:15:29 2018
# ------------------------------------------------

package:
    name: prompt_toolkit
    version: 1.0.15
source:
    sha256: 858588f1983ca497f1cf4ffde01d978a3ea02b01c8a26a8bbc5cd2e66d816917
    url: https://pypi.io/packages/source/p/prompt_toolkit/prompt_toolkit-1.0.15.tar.gz
build:
    noarch: python
    number: '1'
    script: /home/conda/feedstock_root/build_artifacts/prompt_toolkit_1535296643838/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python
        -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
    string: py_1
requirements:
    host:
        - bzip2 1.0.6 h470a237_2
        - ca-certificates 2018.8.24 ha4d7672_0
        - certifi 2018.8.24 py27_1
        - libgcc-ng 7.2.0 hdf63c60_3
        - libstdcxx-ng 7.2.0 hdf63c60_3
        - ncurses 6.1 hfc679d8_1
        - openssl 1.0.2o h470a237_1
        - pip 18.0 py27_1
        - python 2.7.15 h9fef7bc_0
        - readline 7.0 haf1bffa_1
        - setuptools 40.2.0 py27_0
        - sqlite 3.24.0 h2f33b56_0
        - tk 8.6.8 0
        - wheel 0.31.1 py27_1
        - zlib 1.2.11 h470a237_3
    run:
        - pygments
        - python
        - six >=1.9.0
        - wcwidth
test:
    imports:
        - prompt_toolkit
        - prompt_toolkit.clipboard
        - prompt_toolkit.contrib
        - prompt_toolkit.contrib.completers
        - prompt_toolkit.contrib.regular_languages
        - prompt_toolkit.eventloop
        - prompt_toolkit.filters
        - prompt_toolkit.key_binding
        - prompt_toolkit.key_binding.bindings
        - prompt_toolkit.layout
about:
    description: 'prompt_toolkit is a library for building powerful interactive command

        lines and terminal applications in Python. It can be a pure Python

        replacement for GNU readline, but it can be much more than that.

        '
    dev_url: https://github.com/jonathanslenders/python-prompt-toolkit
    doc_url: http://python-prompt-toolkit.readthedocs.io
    home: https://github.com/jonathanslenders/python-prompt-toolkit
    license: BSD 3-clause
    license_file: LICENSE
    summary: Library for building powerful interactive command lines in Python
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - asmeurer
        - jakirkham
        - ocefpaf
        - scopatz
