# This file created by conda-build 3.10.9
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sun Jul  8 17:16:31 2018
# ------------------------------------------------

package:
    name: partd
    version: 0.3.8
source:
    fn: partd-0.3.8.tar.gz
    sha256: 67291f1c4827cde3e0148b3be5d69af64b6d6169feb9ba88f0a6cfe77089400f
    url: https://pypi.io/packages/source/p/partd/partd-0.3.8.tar.gz
build:
    noarch: python
    number: '1'
    script: python -m pip install --no-deps --ignore-installed .
    string: py_1
requirements:
    host:
        - ca-certificates 2018.4.16 0
        - certifi 2018.4.16 py27_0
        - libgcc-ng 7.2.0 hdf63c60_3
        - locket 0.2.0 py27_1
        - ncurses 5.9 10
        - openssl 1.0.2o 0
        - pip 9.0.3 py27_0
        - python 2.7.15 0
        - readline 7.0 0
        - setuptools 39.2.0 py27_0
        - sqlite 3.20.1 2
        - tk 8.6.7 0
        - toolz 0.9.0 py_0
        - wheel 0.31.1 py27_0
        - zlib 1.2.11 h470a237_3
    run:
        - locket
        - python
        - toolz
test:
    imports:
        - partd
about:
    home: https://github.com/dask/partd
    license: BSD 3-Clause
    summary: Data structure for on-disk shuffle operations
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jcrist
        - koverholt
        - mrocklin
