# This file created by conda-build 3.12.1
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed Aug  8 18:01:34 2018
# ------------------------------------------------

package:
    name: libiconv
    version: '1.15'
source:
    patches:
        - glibc.patch
    sha256: ccf536620a45458d26ba83887a983b96827001e92a13847b45e4925cc8913178
    url: http://ftp.gnu.org/pub/gnu/libiconv/libiconv-1.15.tar.gz
build:
    number: '2'
    run_exports:
        - libiconv >=1.15,<2.0a0
    string: h470a237_2
requirements:
    build:
        - toolchain 2.1.6 0
        - toolchain_c_linux-64 2.1.6 0
    host:
        - libgcc-ng 7.2.0 hdf63c60_3
    run:
        - libgcc-ng >=4.9
test:
    commands:
        - iconv --help
        - conda inspect linkages -p $PREFIX $PKG_NAME
about:
    home: https://www.gnu.org/software/libiconv/
    license: GPL and LGPL
    summary: Provides iconv for systems which don't have one (or that cannot convert
        from/to Unicode.)
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jhamman
        - ocefpaf
        - scopatz
