# This file created by conda-build 3.8.0
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/cryptography-2.2.2-python_3.6-on-linux_64, last modified Mon Apr  2 15:41:23 2018
# ------------------------------------------------

package:
    name: cryptography
    version: 2.2.2
source:
    fn: cryptography-2.2.2.tar.gz
    sha256: 9fc295bf69130a342e7a19a39d7bbeb15c0bcaabc7382ec33ef3b2b7d18d2f63
    url: https://pypi.io/packages/source/c/cryptography/cryptography-2.2.2.tar.gz
build:
    number: '0'
    script:
        - export CFLAGS="-I${PREFIX}/include ${CFLAGS}"
        - export LDFLAGS="-L${PREFIX}/lib ${LDFLAGS}"
        - python setup.py install --single-version-externally-managed --record=record.txt
    string: py36h14c3975_0
requirements:
    build:
        - binutils_impl_linux-64 2.28.1 had2808c_3
        - binutils_linux-64 7.2.0 26
        - gcc_impl_linux-64 7.2.0 habb00fd_3
        - gcc_linux-64 7.2.0 26
        - libstdcxx-ng 7.2.0 hdf63c60_3
    host:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2018.1.18 py36_0
        - cffi 1.11.5 py36h9745a5d_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 7.2.0 hdf63c60_3
        - libstdcxx-ng 7.2.0 hdf63c60_3
        - ncurses 6.0 h9df7e31_2
        - openssl 1.0.2o h20670df_0
        - pycparser 2.18 py36hf9f622e_1
        - python 3.6.5 hc3d631a_0
        - readline 7.0 ha6073c6_4
        - setuptools 39.0.1 py36_0
        - sqlite 3.22.0 h1bed415_0
        - tk 8.6.7 hc745277_3
        - xz 5.2.3 h55aa19d_2
        - zlib 1.2.11 ha838bed_2
    run:
        - asn1crypto >=0.21.0
        - cffi >=1.7
        - idna >=2.1
        - libgcc-ng >=7.2.0
        - openssl 1.0.*
        - openssl >=1.0.2o,<1.0.3a
        - python >=3.6,<3.7.0a0
        - six >=1.4.1
test:
    commands:
        - pytest
    imports:
        - cryptography
        - cryptography.fernet
        - cryptography.hazmat
        - cryptography.hazmat.backends
        - cryptography.hazmat.backends.openssl
        - cryptography.hazmat.bindings
        - cryptography.hazmat.bindings.openssl
        - cryptography.hazmat.primitives
        - cryptography.hazmat.primitives.asymmetric
        - cryptography.hazmat.primitives.ciphers
        - cryptography.hazmat.primitives.kdf
        - cryptography.hazmat.primitives.twofactor
        - cryptography.x509
    requires:
        - cryptography-vectors 2.2.2.*
        - hypothesis >=1.11.4
        - iso8601
        - pretend
        - pytest >=3.2.1,!=3.3.0
        - pytz
    source_files:
        - tests
about:
    description: 'Cryptography is a package which provides cryptographic recipes and

        primitives to Python developers. Our goal is for it to be your

        "cryptographic standard library". It supports Python 2.6-2.7, Python 3.3+,

        and PyPy 2.6+. Cryptography includes both high level recipes, and low level

        interfaces to common cryptographic algorithms such as symmetric ciphers,

        message digests and key derivation functions.

        '
    dev_url: https://github.com/pyca/cryptography
    doc_source_url: https://github.com/pyca/cryptography/tree/master/docs
    doc_url: http://cryptography.readthedocs.io/
    home: https://github.com/pyca/cryptography
    license: Apache 2.0 or BSD 3-Clause, PSF 2
    license_family: BSD
    license_file: LICENSE
    summary: Provides cryptographic recipes and primitives to Python developers
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jschueller
        - mingwandroid
