# This file created by conda-build 3.10.9
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sun Jul  1 19:58:18 2018
# ------------------------------------------------

package:
    name: libpng
    version: 1.6.34
source:
    sha256: 574623a4901a9969080ab4a2df9437026c8a87150dfd5c235e28c94b212964a7
    url: http://download.sourceforge.net/libpng/libpng-1.6.34.tar.gz
build:
    number: '1'
    run_exports:
        - libpng >=1.6.34,<1.7.0a0
    string: ha92aebf_1
requirements:
    build:
        - autoconf 2.69 pl5.22.2.1_5
        - automake 1.15.1 pl5.22.2.1_0
        - libtool 2.4.6 0
        - m4 1.4.18 0
        - perl 5.22.2.1 0
        - toolchain 2.1.5 0
        - toolchain_c_linux-64 2.1.5 0
    host:
        - libgcc-ng 7.2.0 hdf63c60_3
        - zlib 1.2.11 h470a237_3
    run:
        - libgcc-ng >=4.9
        - zlib >=1.2.11,<1.3.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - test -f ${PREFIX}/lib/libpng.a
        - test -f ${PREFIX}/lib/libpng${SHLIB_EXT}
        - libpng-config --version
        - conda inspect linkages -p $PREFIX $PKG_NAME
about:
    description: 'libpng is the official PNG reference library. It supports almost
        all PNG

        features, is extensible, and has been extensively tested for over 20 years.

        '
    dev_url: https://sourceforge.net/p/libpng/code/ci/libpng16/tree/
    doc_url: http://www.libpng.org/pub/png/libpng.html
    home: http://www.libpng.org/pub/png/libpng.html
    license: zlib/libpng
    license_file: LICENSE
    license_url: http://www.libpng.org/pub/png/src/libpng-LICENSE.txt
    summary: PNG reference library
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - msarahan
        - ocefpaf
