# This file created by conda-build 3.12.1
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Aug 14 19:14:57 2018
# ------------------------------------------------

package:
    name: cryptography-vectors
    version: 2.3.1
source:
    sha256: bf4d9b61dce69c49e830950aa36fad194706463b0b6dfe81425b9e0bc6644d46
    url: https://pypi.io/packages/source/c/cryptography_vectors/cryptography_vectors-2.3.1.tar.gz
build:
    number: '0'
    script: /home/conda/feedstock_root/build_artifacts/cryptography-vectors_1534274160071/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/python
        -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
    string: py36_0
requirements:
    host:
        - bzip2 1.0.6 h470a237_2
        - ca-certificates 2018.4.16 0
        - certifi 2018.8.13 py36_0
        - libffi 3.2.1 hfc679d8_4
        - libgcc-ng 7.2.0 hdf63c60_3
        - libstdcxx-ng 7.2.0 hdf63c60_3
        - ncurses 6.1 hfc679d8_1
        - openssl 1.0.2o h470a237_1
        - pip 18.0 py36_1
        - python 3.6.6 h5001a0f_0
        - readline 7.0 haf1bffa_1
        - setuptools 40.0.0 py36_1
        - sqlite 3.24.0 h2f33b56_0
        - tk 8.6.8 0
        - wheel 0.31.1 py36_1
        - xz 5.2.4 h470a237_1
        - zlib 1.2.11 h470a237_3
    run:
        - python >=3.6,<3.7.0a0
test:
    imports:
        - cryptography_vectors
about:
    dev_url: https://github.com/pyca/cryptography/tree/master/vectors
    doc_url: https://cryptography.io
    home: https://github.com/pyca/cryptography
    license: Apache 2.0 or BSD 3-Clause
    summary: Test vectors for the cryptography package.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
