# This file created by conda-build 3.10.9
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sun Jun 24 11:19:57 2018
# ------------------------------------------------

package:
    name: libssh2
    version: 1.8.0
source:
    sha256: 39f34e2f6835f4b992cafe8625073a88e5a28ba78f83e8099610a7b3af4676d4
    url: https://www.libssh2.org/download/libssh2-1.8.0.tar.gz
build:
    number: '2'
    string: h5b517e9_2
requirements:
    build:
        - toolchain 2.1.5 0
        - toolchain_c_linux-64 2.1.5 0
    host:
        - ca-certificates 2018.4.16 0
        - cmake-binary 3.9.1 h2f8e2a0_1
        - libgcc-ng 7.2.0 hdf63c60_3
        - openssl 1.0.2o 0
        - zlib 1.2.11 h470a237_3
    run:
        - libgcc-ng >=4.9
        - openssl >=1.0.2o,<1.0.3a
        - zlib >=1.2.11,<1.3.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - test -f $PREFIX/include/libssh2.h
        - test -f $PREFIX/include/libssh2_publickey.h
        - test -f $PREFIX/include/libssh2_sftp.h
        - test -f $PREFIX/lib/libssh2.a
        - test -f $PREFIX/lib/libssh2.so
        - conda inspect linkages -p $PREFIX $PKG_NAME
about:
    description: 'libssh2 is a library implementing the SSH2 protocol, available under
        the revised BSD license.

        '
    dev_url: https://github.com/libssh2/libssh2
    home: https://www.libssh2.org/
    license: BSD 3-Clause
    license_family: BSD
    license_file: COPYING
    summary: the SSH library
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - nehaljwani
        - ocefpaf
        - shadowwalkersb
