# This file created by conda-build 2.1.18
# meta.yaml template originally from:
# /recipe_root, last modified Wed Feb 21 01:51:17 2018
# ------------------------------------------------

package:
    name: s3transfer
    version: 0.1.13
source:
    fn: s3transfer-0.1.13.tar.gz
    sha256: 90dc18e028989c609146e241ea153250be451e05ecc0c2832565231dacdf59c1
    url: https://pypi.io/packages/source/s/s3transfer/s3transfer-0.1.13.tar.gz
build:
    noarch: ''
    noarch_python: false
    number: '0'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py36_0
requirements:
    build:
        - certifi 2018.1.18 py36_0
        - python 3.6.4 0
        - xz 5.2.3 0
        - openssl 1.0.2n 0
        - readline 7.0 0
        - setuptools 38.5.1 py36_0
        - zlib 1.2.11 0
        - tk 8.6.7 0
        - ca-certificates 2018.1.18 0
        - ncurses 5.9 10
        - sqlite 3.20.1 2
    run:
        - python
        - botocore >=1.3.0,<2.0.0
test:
    imports:
        - s3transfer
about:
    dev_url: https://github.com/boto/s3transfer
    home: https://github.com/boto/s3transfer
    license: Apache 2.0
    license_family: Apache
    license_file: LICENSE.txt
    summary: An Amazon S3 Transfer Manager
extra:
    final: true
    recipe-maintainers:
        - pmlandwehr
        - proinsias
        - tkelman
