# This file created by conda-build 3.13.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Thu Aug 30 16:40:13 2018
# ------------------------------------------------

package:
    name: boto3
    version: 1.8.4
source:
    fn: boto3-1.8.4.tar.gz
    sha256: 06ecdf57cc4a44ed2f7d555390aca2f3bab6b244abd000ee2d55bfb408ff90c8
    url: https://pypi.io/packages/source/b/boto3/boto3-1.8.4.tar.gz
build:
    noarch: python
    number: '0'
    script: python -m pip install --no-deps --ignore-installed .
    string: py_0
requirements:
    host:
        - bzip2 1.0.6 h470a237_2
        - ca-certificates 2018.8.24 ha4d7672_0
        - certifi 2018.8.24 py27_1
        - libgcc-ng 7.2.0 hdf63c60_3
        - libstdcxx-ng 7.2.0 hdf63c60_3
        - ncurses 6.1 hfc679d8_1
        - openssl 1.0.2p h470a237_0
        - pip 18.0 py27_1
        - python 2.7.15 h9fef7bc_0
        - readline 7.0 haf1bffa_1
        - setuptools 40.2.0 py27_0
        - sqlite 3.24.0 h2f33b56_0
        - tk 8.6.8 0
        - wheel 0.31.1 py27_1
        - zlib 1.2.11 h470a237_3
    run:
        - botocore >=1.11.4,<1.12.0
        - jmespath >=0.7.1,<1.0.0
        - python
        - s3transfer >=0.1.10,<0.2.0
test:
    imports:
        - boto3
        - boto3.docs
        - boto3.dynamodb
        - boto3.ec2
        - boto3.resources
        - boto3.s3
about:
    description: 'Boto3 makes it easy to integrate you Python application, library
        or script

        with AWS services. It allows Python developers to write softare that makes

        use of services like Amazon S3 and Amazon EC2.

        '
    dev_url: https://github.com/boto/boto3
    doc_source_url: https://github.com/boto/boto3/blob/develop/README.rst
    doc_url: https://boto3.readthedocs.org
    home: http://aws.amazon.com/sdk-for-python/
    license: Apache 2.0
    license_family: Apache
    license_file: LICENSE
    summary: Amazon Web Services SDK for Python
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - proinsias
        - tkelman
