# This file created by conda-build 3.10.9
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sat Jul  7 23:03:16 2018
# ------------------------------------------------

package:
    name: pygments
    version: 2.2.0
source:
    fn: Pygments-2.2.0.tar.gz
    sha256: dbae1046def0efb574852fab9e90209b23f556367b5a320c0bcb871c77c3e8cc
    url: https://pypi.io/packages/source/P/Pygments/Pygments-2.2.0.tar.gz
build:
    entry_points:
        - pygmentize = pygments.cmdline:main
    noarch: python
    number: '1'
    script: python -m pip install --no-deps --ignore-installed .
    string: py_1
requirements:
    host:
        - ca-certificates 2018.4.16 0
        - certifi 2018.4.16 py27_0
        - libgcc-ng 7.2.0 hdf63c60_3
        - ncurses 5.9 10
        - openssl 1.0.2o 0
        - pip 9.0.3 py27_0
        - python 2.7.15 0
        - readline 7.0 0
        - setuptools 39.2.0 py27_0
        - sqlite 3.20.1 2
        - tk 8.6.7 0
        - wheel 0.31.1 py27_0
        - zlib 1.2.11 h470a237_3
    run:
        - python
        - setuptools
test:
    commands:
        - pygmentize -h
    imports:
        - pygments
        - pygments.filters
        - pygments.formatters
        - pygments.lexers
        - pygments.plugin
        - pygments.styles
about:
    home: http://pygments.org/
    license: BSD 2-clause
    license_file: LICENSE
    summary: Pygments is a generic syntax highlighter suitable for use in code hosting,
        forums, wikis or other applications that need to prettify source code.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - ocefpaf
        - pelson
        - scopatz
