# This file created by conda-build 3.12.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sat Jul 28 12:22:42 2018
# ------------------------------------------------

package:
    name: freetype
    version: 2.8.1
source:
    sha256: e5435f02e02d2b87bb8e4efdcaa14b1f78c9cf3ab1ed80f94b6382fb6acc7d78
    url: http://download.savannah.gnu.org/releases/freetype/freetype-2.8.1.tar.bz2
build:
    number: '1'
    string: hfa320df_1
requirements:
    build:
        - toolchain 2.1.6 0
        - toolchain_c_linux-64 2.1.6 0
        - toolchain_cxx_linux-64 2.1.6 0
    host:
        - libgcc-ng 7.2.0 hdf63c60_3
        - libpng 1.6.34 ha92aebf_1
        - libstdcxx-ng 7.2.0 hdf63c60_3
        - zlib 1.2.11 h470a237_3
    run:
        - libgcc-ng >=4.9
        - libpng >=1.6.34,<1.7.0a0
        - libpng >=1.6.34,<1.7.0a0
        - libstdcxx-ng >=4.9
        - zlib >=1.2.11,<1.3.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - freetype-config --version
        - conda inspect linkages -p $PREFIX $PKG_NAME
about:
    home: https://www.freetype.org/
    license: GPL-2.0 and FreeType (http://freetype.sourceforge.net/FTL.TXT)
    summary: A TrueType Font Library.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ccordoba12
        - msarahan
        - ocefpaf
