# This file created by conda-build 2.1.18
# meta.yaml template originally from:
# /recipe_root, last modified Fri Apr  6 13:36:18 2018
# ------------------------------------------------

package:
    name: python
    version: 3.6.5
source:
    patches:
        - mingw-w64--DMS_WINXX.patch
        - win-msc_ver-1900.patch
        - fix-ABI-issue29943.patch
        - 0015-Fix-find_library-so-that-it-looks-in-sys.prefix-lib-.patch
    sha256: 53a3e17d77cd15c5230192b6a8c1e031c07cd9f34a2f089a731c6f6bd343d5c6
    url: https://www.python.org/ftp/python/3.6.5/Python-3.6.5.tgz
build:
    no_link:
        - bin/python3.6
    noarch: ''
    noarch_python: false
    number: '1'
    script_env:
        - python_branding
    string: '1'
    track_features: ''
requirements:
    build:
        - xz 5.2.3 0
        - openssl 1.0.2n 0
        - readline 7.0 0
        - bzip2 1.0.6 1
        - zlib 1.2.11 0
        - tk 8.6.7 0
        - ca-certificates 2018.1.18 0
        - ncurses 5.9 10
        - sqlite 3.20.1 2
    run:
        - openssl 1.0.*
        - readline 7.0
        - sqlite 3.20.*
        - tk 8.6.*
        - xz 5.2.*
        - zlib 1.2.11
        - ncurses 5.9
test:
    commands:
        - python -V
        - python3 -V
        - 2to3 -h
        - pydoc -h
        - python3-config --help
        - conda inspect linkages -p $PREFIX $PKG_NAME
about:
    home: http://www.python.org/
    license: PSF
    license_file: LICENSE
    summary: General purpose programming language.
extra:
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - msarahan
        - pelson
        - ocefpaf
