# This file created by conda-build 2.1.18
# meta.yaml template originally from:
# /recipe_root, last modified Sat Mar 17 16:43:32 2018
# ------------------------------------------------

package:
    name: harfbuzz
    version: 1.7.6
source:
    sha256: da7bed39134826cd51e57c29f1dfbe342ccedb4f4773b1c951ff05ff383e2e9b
    url: https://www.freedesktop.org/software/harfbuzz/release/harfbuzz-1.7.6.tar.bz2
build:
    detect_binary_files_with_prefix: 'true'
    noarch: ''
    noarch_python: false
    number: '0'
    string: '0'
requirements:
    build:
        - freetype 2.8.1 0
        - libpng 1.6.34 0
        - xz 5.2.3 0
        - openssl 1.0.2n 0
        - gobject-introspection 1.55.0 py27_0
        - readline 7.0 0
        - autoconf 2.69 pl5.22.2.1_5
        - zlib 1.2.11 0
        - fontconfig 2.12.6 0
        - pkg-config 0.29.1 2
        - libiconv 1.15 0
        - libffi 3.2.1 3
        - tk 8.6.7 0
        - cairo 1.14.10 0
        - python 2.7.14 4
        - graphite2 1.3.11 0
        - pcre 8.41 1
        - glib 2.55.0 0
        - gettext 0.19.8.1 0
        - perl 5.22.2.1 0
        - icu 58.2 0
        - automake 1.15.1 pl5.22.2.1_0
        - ca-certificates 2018.1.18 0
        - ncurses 5.9 10
        - pixman 0.34.0 1
        - libtool 2.4.6 0
        - m4 1.4.17 1
        - libxml2 2.9.7 0
        - sqlite 3.20.1 2
    run:
        - cairo 1.14.*
        - glib 2.55.*
        - freetype 2.8.1
        - icu 58.*
        - graphite2 1.3.*
test:
    commands:
        - test -f $PREFIX/lib/libharfbuzz-icu.so
        - test -f $PREFIX/lib/libharfbuzz.so
        - test -f $PREFIX/include/harfbuzz/hb-ft.h
        - hb-view --version
        - conda inspect linkages -p $PREFIX $PKG_NAME
about:
    description: 'HarfBuzz is a text shaping library. New Harbuzz targets various
        font

        technologies while Old HarfBuzz targets only OpenType fonts.

        '
    dev_url: https://github.com/behdad/harfbuzz
    doc_url: https://www.freedesktop.org/wiki/Software/HarfBuzz/
    home: http://www.freedesktop.org/wiki/Software/HarfBuzz/
    license: MIT
    license_file: COPYING
    summary: An OpenType text shaping engine.
extra:
    final: true
    recipe-maintainers:
        - ocefpaf
        - pkgw
