# This file created by conda-build 2.1.15
# meta.yaml template originally from:
# /opt/recipe, last modified Mon Jun 26 09:51:23 2017
# ------------------------------------------------

package:
    name: pysam
    version: 0.11.2.2
source:
    fn: pysam-0.11.2.2.tar.gz
    md5: 56230cd5f55b503845915b76c22d620a
    url: https://pypi.python.org/packages/a4/1b/b6dfd92aea876647d20d9a8bd8618e4f2af6300539426be83c8bb0912d6f/pysam-0.11.2.2.tar.gz
build:
    binary_relocation: 'False'
    noarch: ''
    noarch_python: false
    number: '1'
    skip: 'False'
    string: py36_1
requirements:
    build:
        - ncurses 5.9 10
        - isl 0.12.2 0
        - wheel 0.29.0 py36_0
        - pip 9.0.1 py36_0
        - mpc 1.0.3 4
        - sqlite 3.13.0 1
        - cloog 0.18.0 0
        - readline 6.2 0
        - samtools 1.5 0
        - htslib 1.5 0
        - ca-certificates 2017.4.17 0
        - bzip2 1.0.6 1
        - curl 7.52.1 0
        - xz 5.2.2 0
        - openssl 1.0.2k 0
        - mpfr 3.1.5 0
        - certifi 2017.4.17 py36_0
        - gmp 6.1.2 0
        - setuptools 33.1.1 py36_0
        - tk 8.5.19 1
        - gcc 4.8.5 7
        - cython 0.25.2 py36_1
        - zlib 1.2.11 0
        - libgcc 5.2.0 0
        - bcftools 1.5 0
        - python 3.6.1 3
    run:
        - libgcc
        - htslib >=1.4.1
        - samtools >=1.4.1
        - bcftools >=1.4.1
        - python
        - zlib
        - curl
test:
    imports:
        - pysam
about:
    home: https://github.com/pysam-developers/pysam
    license: MIT
    summary: Pysam is a python module for reading and manipulating Samfiles. It is
        a lightweight wrapper of the samtools C-API. Pysam also includes an interface
        for tabix.
extra:
    final: true
