# This file created by conda-build 3.12.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sat Aug  4 09:23:46 2018
# ------------------------------------------------

package:
    name: lxml
    version: 4.2.4
source:
    sha256: e2afbe403090f5893e254958d02875e0732975e73c4c0cdd33c1f009a61963ca
    url: https://pypi.io/packages/source/l/lxml/lxml-4.2.4.tar.gz
build:
    number: '0'
    script:
        - python -m pip install --no-deps --ignore-installed . --global-option="--with-xslt-config=$PREFIX/bin/xslt-config"
    string: py36hc9114bc_0
requirements:
    build:
        - toolchain 2.1.6 0
        - toolchain_c_linux-64 2.1.6 0
    host:
        - bzip2 1.0.6 h470a237_2
        - ca-certificates 2018.4.16 0
        - certifi 2018.4.16 py36_0
        - cython 0.28.5 py36hfc679d8_0
        - icu 58.2 hfc679d8_0
        - libffi 3.2.1 3
        - libgcc-ng 7.2.0 hdf63c60_3
        - libiconv 1.15 h470a237_1
        - libstdcxx-ng 7.2.0 hdf63c60_3
        - libxml2 2.9.8 h422b904_2
        - libxslt 1.1.32 h88dbc4e_1
        - ncurses 6.1 hfc679d8_1
        - openssl 1.0.2o h470a237_1
        - pip 18.0 py36_1
        - python 3.6.6 h5001a0f_0
        - readline 7.0 haf1bffa_1
        - setuptools 40.0.0 py36_1
        - sqlite 3.24.0 h2f33b56_0
        - tk 8.6.8 0
        - wheel 0.31.1 py36_1
        - xz 5.2.4 h470a237_0
        - zlib 1.2.11 h470a237_3
    run:
        - libgcc-ng >=4.9
        - libxml2 >=2.9.8,<2.10.0a0
        - libxslt >=1.1.32,<2.0a0
        - python >=3.6,<3.7.0a0
test:
    commands:
        - conda inspect linkages -p $PREFIX lxml
    imports:
        - lxml
        - lxml.etree
        - lxml.objectify
about:
    description: 'The lxml XML toolkit is a Pythonic binding for the C libraries libxml2
        and

        libxslt. It is unique in that it combines the speed and XML feature

        completeness of these libraries with the simplicity of a native Python API,

        mostly compatible but superior to the well-known ElementTree API.

        '
    dev_url: https://github.com/lxml/lxml
    doc_source_url: https://github.com/lxml/lxml/tree/master/doc
    doc_url: http://lxml.de/index.html#documentation
    home: http://lxml.de/
    license: BSD 3-Clause, GPL-2.0, ZPL-2.0, and ElementTree
    license_file: LICENSES.txt
    summary: Pythonic binding for the C libraries libxml2 and libxslt.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jjhelmus
        - ocefpaf
