# This file created by conda-build 2.1.17
# meta.yaml template originally from:
# /recipe_root, last modified Thu Sep  7 15:07:04 2017
# ------------------------------------------------

package:
    name: nbconvert
    version: 5.3.1
source:
    fn: nbconvert-5.3.1.tar.gz
    sha256: 12b1a4671d4463ab73af6e4cbcc965b62254e05d182cd54995dda0d0ef9e2db9
    url: https://pypi.io/packages/source/n/nbconvert/nbconvert-5.3.1.tar.gz
build:
    entry_points:
        - jupyter-nbconvert = nbconvert.nbconvertapp:main
    noarch: python
    noarch_python: false
    number: '1'
    script: pip install --no-deps .
    string: py_1
requirements:
    build:
        - ncurses 5.9 10
        - readline 6.2 0
        - tk 8.5.19 2
        - ca-certificates 2017.7.27.1 0
        - pip 9.0.1 py36_0
        - setuptools 36.3.0 py36_0
        - zlib 1.2.11 0
        - xz 5.2.3 0
        - certifi 2017.7.27.1 py36_0
        - python 3.6.2 0
        - sqlite 3.13.0 1
        - openssl 1.0.2l 0
        - wheel 0.29.0 py36_0
    run:
        - bleach
        - entrypoints >=0.2.2
        - jinja2
        - jupyter_core
        - jupyter_client >=4.2
        - mistune >=0.7.4
        - nbformat >=4.4
        - pandoc
        - pandocfilters >=1.4.1
        - python
        - pygments
        - testpath
        - traitlets
test:
    commands:
        - jupyter nbconvert --help
        - jupyter nbconvert nbconvert/tests/files/notebook1.ipynb
    imports:
        - nbconvert
        - nbconvert.exporters
        - nbconvert.filters
        - nbconvert.postprocessors
        - nbconvert.preprocessors
        - nbconvert.resources
        - nbconvert.tests
        - nbconvert.utils
        - nbconvert.writers
    source_files:
        - nbconvert/tests/files/notebook1.ipynb
about:
    home: http://jupyter.org
    license: BSD 3-Clause
    summary: Converting Jupyter Notebooks
extra:
    final: true
    recipe-maintainers:
        - jakirkham
        - mpacer
        - minrk
        - pelson
        - takluyver
