# This file created by conda-build 3.10.9
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed Jul 11 05:56:57 2018
# ------------------------------------------------

package:
    name: rsa
    version: 3.4.2
source:
    fn: rsa-3.4.2.tar.gz
    sha256: 25df4e10c263fb88b5ace923dd84bf9aa7f5019687b5e55382ffcdb8bede9db5
    url: https://pypi.org/packages/source/r/rsa/rsa-3.4.2.tar.gz
build:
    entry_points:
        - pyrsa-decrypt = rsa.cli:decrypt
        - pyrsa-decrypt-bigfile = rsa.cli:decrypt_bigfile
        - pyrsa-encrypt = rsa.cli:encrypt
        - pyrsa-encrypt-bigfile = rsa.cli:encrypt_bigfile
        - pyrsa-keygen = rsa.cli:keygen
        - pyrsa-priv2pub = rsa.util:private_to_public
        - pyrsa-sign = rsa.cli:sign
        - pyrsa-verify = rsa.cli:verify
    noarch: python
    number: '1'
    script: python -m pip install --no-deps --ignore-installed .
    string: py_1
requirements:
    host:
        - ca-certificates 2018.4.16 0
        - certifi 2018.4.16 py27_0
        - libgcc-ng 7.2.0 hdf63c60_3
        - ncurses 5.9 10
        - openssl 1.0.2o 0
        - pip 9.0.3 py27_0
        - pyasn1 0.4.3 py_0
        - python 2.7.15 0
        - readline 7.0 0
        - setuptools 40.0.0 py27_0
        - sqlite 3.20.1 2
        - tk 8.6.7 0
        - wheel 0.31.1 py27_0
        - zlib 1.2.11 h470a237_3
    run:
        - pyasn1 >=0.1.3
        - python
test:
    commands:
        - pyrsa-priv2pub --help
        - pyrsa-keygen --help
        - pyrsa-encrypt --help
        - pyrsa-decrypt --help
        - pyrsa-sign --help
        - pyrsa-verify --help
        - pyrsa-encrypt-bigfile --help
        - pyrsa-decrypt-bigfile --help
    imports:
        - rsa
about:
    home: https://stuvel.eu/rsa
    license: Apache 2.0
    summary: Pure-Python RSA implementation
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - pmlandwehr
