# This file created by conda-build 3.13.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sun Aug 26 21:12:44 2018
# ------------------------------------------------

package:
    name: matplotlib-venn
    version: 0.11.5
source:
    sha256: be017a6821bce410db3314099649f1a0fcf4c0fbf7be0c1190b102187988838f
    url: https://pypi.org/packages/source/m/matplotlib-venn/matplotlib-venn-0.11.5.zip
build:
    noarch: python
    number: '1'
    script: /home/conda/feedstock_root/build_artifacts/matplotlib-venn_1535318076058/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
        -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
    string: py_1
requirements:
    host:
        - bzip2 1.0.6 h470a237_2
        - ca-certificates 2018.8.24 ha4d7672_0
        - certifi 2018.8.24 py27_1
        - libgcc-ng 7.2.0 hdf63c60_3
        - libstdcxx-ng 7.2.0 hdf63c60_3
        - ncurses 6.1 hfc679d8_1
        - openssl 1.0.2o h470a237_1
        - pip 18.0 py27_1
        - python 2.7.15 h9fef7bc_0
        - readline 7.0 haf1bffa_1
        - setuptools 40.2.0 py27_0
        - sqlite 3.24.0 h2f33b56_0
        - tk 8.6.8 0
        - wheel 0.31.1 py27_1
        - zlib 1.2.11 h470a237_3
    run:
        - matplotlib
        - numpy
        - python
        - scipy
test:
    imports:
        - matplotlib_venn
about:
    dev_url: https://github.com/konstantint/matplotlib-venn
    home: https://github.com/konstantint/matplotlib-venn
    license: MIT
    license_family: MIT
    summary: Functions for plotting area-proportional two- and three-way Venn diagrams
        in matplotlib.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - pmlandwehr
