# This file created by conda-build 3.10.9
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sat Jul 21 01:39:31 2018
# ------------------------------------------------

package:
    name: fasteners
    version: 0.14.1
source:
    fn: fasteners-0.14.1.tar.gz
    md5: fcb13261c9b0039d9b1c4feb9bc75e04
    url: https://pypi.io/packages/source/f/fasteners/fasteners-0.14.1.tar.gz
build:
    noarch: python
    number: '3'
    script: python -m pip install --no-deps --ignore-installed .
    string: py_3
requirements:
    host:
        - ca-certificates 2018.4.16 0
        - certifi 2018.4.16 py27_0
        - libgcc-ng 7.2.0 hdf63c60_3
        - monotonic 1.5 py_0
        - ncurses 5.9 10
        - openssl 1.0.2o 0
        - pip 9.0.3 py27_0
        - python 2.7.15 0
        - readline 7.0 0
        - setuptools 40.0.0 py27_0
        - six 1.11.0 py27_1
        - sqlite 3.20.1 2
        - tk 8.6.8 0
        - wheel 0.31.1 py27_0
        - zlib 1.2.11 h470a237_3
    run:
        - monotonic >=0.1
        - python
        - six
test:
    imports:
        - fasteners
        - fasteners.tests
about:
    home: https://github.com/harlowja/fasteners
    license: Apache 2.0
    license_file: LICENSE
    summary: A python package that provides useful locks.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - alimanfoo
