# This file created by conda-build 3.10.9
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sat Jul  7 12:39:34 2018
# ------------------------------------------------

package:
    name: olefile
    version: 0.45.1
source:
    sha256: 2b6575f5290de8ab1086f8c5490591f7e0885af682c7c1793bdaf6e64078d385
    url: https://pypi.io/packages/source/o/olefile/olefile-0.45.1.zip
build:
    noarch: python
    number: '1'
    script: python -m pip install --no-deps --ignore-installed .
    string: py_1
requirements:
    host:
        - ca-certificates 2018.4.16 0
        - certifi 2018.4.16 py27_0
        - libgcc-ng 7.2.0 hdf63c60_3
        - ncurses 5.9 10
        - openssl 1.0.2o 0
        - pip 9.0.3 py27_0
        - python 2.7.15 0
        - readline 7.0 0
        - setuptools 39.2.0 py27_0
        - sqlite 3.20.1 2
        - tk 8.6.7 0
        - wheel 0.31.0 py27_0
        - zlib 1.2.11 h470a237_3
    run:
        - python
test:
    imports:
        - olefile
about:
    dev_url: https://bitbucket.org/decalage/olefileio_pl/src
    home: http://www.decalage.info/python/olefileio
    license: BSD 2-Clause
    license_family: BSD
    summary: 'Python package to parse, read and write Microsoft OLE2 files (Structured
        Storage or Compound Document, Microsoft Office) - Improved version of the
        OleFileIO module from PIL, the Python Image Library.

        '
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - decarlof
        - dgursoy
        - ericdill
        - licode
        - ocefpaf
        - ravescovi
        - tacaswell
