# This file created by conda-build 3.0.27
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/six-1.11.0-python3.6-on-nwani-linux-64, last modified Sat Oct 21 18:26:30 2017
# ------------------------------------------------

package:
    name: six
    version: 1.11.0
source:
    sha256: 70e8a77beed4562e7f14fe23a786b54f6296e34344c23bc42f07b15018ff98e9
    url: https://pypi.io/packages/source/s/six/six-1.11.0.tar.gz
build:
    number: '1'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py36h372c433_1
requirements:
    build:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.7.27.1 py36h8b7b77e_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 h4deb6c0_3
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - ncurses 6.0 h06874d7_1
        - openssl 1.0.2l h077ae2c_5
        - python 3.6.3 hc9025b9_1
        - readline 7.0 hac23ff0_3
        - setuptools 36.5.0 py36he42e2e1_0
        - sqlite 3.20.1 h6d8b0f3_1
        - tk 8.6.7 h5979e9b_1
        - xz 5.2.3 h2bcbf08_1
        - zlib 1.2.11 hfbfcf68_1
    host:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.7.27.1 py36h8b7b77e_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 h4deb6c0_3
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - ncurses 6.0 h06874d7_1
        - openssl 1.0.2l h077ae2c_5
        - python 3.6.3 hc9025b9_1
        - readline 7.0 hac23ff0_3
        - setuptools 36.5.0 py36he42e2e1_0
        - sqlite 3.20.1 h6d8b0f3_1
        - tk 8.6.7 h5979e9b_1
        - xz 5.2.3 h2bcbf08_1
        - zlib 1.2.11 hfbfcf68_1
    run:
        - python >=3.6,<3.7.0a0
test:
    imports:
        - six
about:
    description: 'Six provides simple utilities for wrapping over differences between

        Python 2 and Python 3. It is intended to support codebases that work on

        both Python 2 and 3 without modification. six consists of only one Python

        file, so it is painless to copy into a project.

        '
    dev_url: https://github.com/benjaminp/six
    doc_url: http://pythonhosted.org/six/
    home: http://pypi.python.org/pypi/six/
    license: MIT
    license_family: MIT
    license_file: LICENSE
    summary: Python 2 and 3 compatibility utilities
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - mingwandroid
        - msarahan
        - ocefpaf
