# This file created by conda-build 2.1.18
# meta.yaml template originally from:
# /recipe_root, last modified Sun Mar 18 23:18:45 2018
# ------------------------------------------------

package:
    name: cython
    version: 0.28.1
source:
    sha256: 152ee5f345012ca3bb7cc71da2d3736ee20f52cd8476e4d49e5e25c5a4102b12
    url: https://pypi.io/packages/source/C/Cython/Cython-0.28.1.tar.gz
build:
    entry_points:
        - cython = Cython.Compiler.Main:setuptools_main
        - cythonize = Cython.Build.Cythonize:main
        - cygdb = Cython.Debugger.Cygdb:main
    noarch: ''
    noarch_python: false
    number: '0'
    script: python -m pip install --no-deps --ignore-installed .
    string: py36_0
requirements:
    build:
        - certifi 2018.1.18 py36_0
        - python 3.6.4 0
        - xz 5.2.3 0
        - openssl 1.0.2n 0
        - readline 7.0 0
        - zlib 1.2.11 0
        - pip 9.0.2 py36_0
        - tk 8.6.7 0
        - setuptools 39.0.1 py36_0
        - ca-certificates 2018.1.18 0
        - ncurses 5.9 10
        - wheel 0.30.0 py36_2
        - sqlite 3.20.1 2
        - toolchain 2.1.2 0
    run:
        - python
test:
    commands:
        - cython --version
    files:
        - fib.pyx
about:
    description: 'Cython is an optimising static compiler for both the Python programming

        language and the extended Cython programming language. It makes writing C

        extensions for Python as easy as Python itself.

        '
    dev_url: https://github.com/cython/cython
    doc_url: http://cython.org/#documentation
    home: http://www.cython.org/
    license: Apache-2.0
    license_file: LICENSE.txt
    summary: The Cython compiler for writing C extensions for the Python language
extra:
    final: true
    recipe-maintainers:
        - jakirkham
        - msarahan
        - ocefpaf
        - synapticarbors
        - isuruf
        - scopatz
