# This file created by conda-build 3.12.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Thu Jul 26 21:06:44 2018
# ------------------------------------------------

package:
    name: curl
    version: 7.61.0
source:
    sha256: 5f6f336921cf5b84de56afbd08dfb70adeef2303751ffb3e570c936c6d656c9c
    url: http://curl.haxx.se/download/curl-7.61.0.tar.bz2
build:
    detect_binary_files_with_prefix: true
    number: '1'
    string: h93b3f91_1
requirements:
    build:
        - libgcc-ng 7.2.0 hdf63c60_3
        - perl 5.26.2 h470a237_0
        - pkg-config 0.29.2 hf5063d0_2
        - toolchain 2.1.6 0
        - toolchain_c_linux-64 2.1.6 0
        - toolchain_cxx_linux-64 2.1.6 0
        - zlib 1.2.11 h470a237_3
    host:
        - ca-certificates 2018.4.16 0
        - krb5 1.14.6 0
        - libgcc-ng 7.2.0 hdf63c60_3
        - libssh2 1.8.0 h5b517e9_2
        - libstdcxx-ng 7.2.0 hdf63c60_3
        - openssl 1.0.2o 0
        - zlib 1.2.11 h470a237_3
    run:
        - krb5 >=1.14.6,<1.15.0a0
        - libgcc-ng >=4.9
        - libssh2 >=1.8.0,<1.9.0a0
        - libstdcxx-ng >=4.9
        - openssl >=1.0.2o,<1.0.3a
        - zlib >=1.2.11,<1.3.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - curl --version
        - curl-config --features
        - curl-config --protocols
        - curl https://raw.githubusercontent.com/conda-forge/curl-feedstock/master/LICENSE
        - conda inspect linkages -p $PREFIX $PKG_NAME
        - nm $PREFIX/lib/libcurl$SHLIB_EXT | grep libssh2_scp_recv2
        - ldd $PREFIX/lib/libcurl.so
about:
    home: http://curl.haxx.se/
    license: MIT/X derivate (http://curl.haxx.se/docs/copyright.html)
    license_family: MIT
    license_file: COPYING
    summary: tool and library for transferring data with URL syntax
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - msarahan
        - ocefpaf
