# This file created by conda-build 3.10.9
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Thu Jul 12 06:37:54 2018
# ------------------------------------------------

package:
    name: idna
    version: '2.7'
source:
    fn: idna-2.7.tar.gz
    sha256: 684a38a6f903c1d71d6d5fac066b58d7768af4de2b832e426ec79c30daa94a16
    url: https://pypi.io/packages/source/i/idna/idna-2.7.tar.gz
build:
    number: '2'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py36_2
requirements:
    build:
        - ca-certificates 2018.4.16 0
        - certifi 2018.4.16 py36_0
        - libgcc-ng 7.2.0 hdf63c60_3
        - ncurses 5.9 10
        - openssl 1.0.2o 0
        - python 3.6.5 1
        - readline 7.0 0
        - setuptools 40.0.0 py36_0
        - sqlite 3.20.1 2
        - tk 8.6.7 0
        - xz 5.2.3 0
        - zlib 1.2.11 h470a237_3
    run:
        - python >=3.6,<3.7.0a0
test:
    imports:
        - idna
about:
    description: 'A library to support the Internationalised Domain Names in Applications

        (IDNA) protocol as specified in RFC 5891. This version of the protocol

        is often referred to as "IDNA2008".

        '
    home: https://github.com/kjd/idna
    license: BSD Like
    license_file: LICENSE.rst
    summary: Internationalized Domain Names in Applications (IDNA).
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - goanpeca
        - jschueller
