# This file created by conda-build 2.1.18
# meta.yaml template originally from:
# /recipe_root, last modified Wed Mar 14 20:29:51 2018
# ------------------------------------------------

package:
    name: paramiko
    version: 2.4.1
source:
    fn: paramiko-2.4.1.tar.gz
    sha256: 33e36775a6c71790ba7692a73f948b329cf9295a72b0102144b031114bd2a4f3
    url: https://pypi.io/packages/source/p/paramiko/paramiko-2.4.1.tar.gz
build:
    noarch: ''
    noarch_python: false
    number: '0'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py36_0
requirements:
    build:
        - certifi 2018.1.18 py36_0
        - python 3.6.4 0
        - xz 5.2.3 0
        - openssl 1.0.2n 0
        - setuptools 38.5.2 py36_0
        - readline 7.0 0
        - zlib 1.2.11 0
        - tk 8.6.7 0
        - ca-certificates 2018.1.18 0
        - ncurses 5.9 10
        - sqlite 3.20.1 2
    run:
        - python
        - bcrypt >=3.1.3
        - cryptography >=1.5
        - pynacl >=1.0.1
        - pyasn1 >=0.1.7
test:
    imports:
        - paramiko
about:
    dev_url: https://github.com/paramiko/paramiko/
    doc_url: http://docs.paramiko.org/
    home: http://www.paramiko.org/
    license: LGPL 2.1
    license_family: LGPL
    license_file: LICENSE
    summary: SSH2 protocol library
extra:
    final: true
    recipe-maintainers:
        - pmlandwehr
        - vamega
        - jakirkham
