# This file created by conda-build 3.2.1
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/asn1crypto-0.24.0-python3.6-on-linux_64, last modified Thu Jan 11 20:17:19 2018
# ------------------------------------------------

package:
    name: asn1crypto
    version: 0.24.0
source:
    fn: asn1crypto-0.24.0.tar.gz
    sha256: 9d5c20441baf0cb60a4ac34cc447c6c189024b6b4c6cd7877034f4965c464e49
    url: https://pypi.io/packages/source/a/asn1crypto/asn1crypto-0.24.0.tar.gz
build:
    number: '0'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py36_0
requirements:
    host:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.11.5 py36hf29ccca_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - ncurses 6.0 h9df7e31_2
        - openssl 1.0.2n hb7f436b_0
        - python 3.6.4 hc3d631a_0
        - readline 7.0 ha6073c6_4
        - setuptools 36.5.0 py36he42e2e1_0
        - sqlite 3.20.1 hb898158_2
        - tk 8.6.7 hc745277_3
        - xz 5.2.3 h55aa19d_2
        - zlib 1.2.11 ha838bed_2
    run:
        - python >=3.6,<3.7.0a0
test:
    imports:
        - asn1crypto
about:
    dev_url: https://github.com/wbond/asn1crypto
    doc_url: https://github.com/wbond/asn1crypto#documentation
    home: https://github.com/wbond/asn1crypto
    license: MIT
    license_file: LICENSE
    summary: Python ASN.1 library with a focus on performance and a pythonic API
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jschueller
