# This file created by conda-build 3.12.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Jul 31 08:07:40 2018
# ------------------------------------------------

package:
    name: cachetools
    version: 2.1.0
source:
    fn: cachetools-2.1.0.tar.gz
    sha256: 90f1d559512fc073483fe573ef5ceb39bf6ad3d39edc98dc55178a2b2b176fa3
    url: https://pypi.io/packages/source/c/cachetools/cachetools-2.1.0.tar.gz
build:
    noarch: python
    number: '0'
    script: python -m pip install --no-deps --ignore-installed .
    string: py_0
requirements:
    build:
        - bzip2 1.0.6 h470a237_2
        - ca-certificates 2018.4.16 0
        - certifi 2018.4.16 py27_0
        - libgcc-ng 7.2.0 hdf63c60_3
        - libstdcxx-ng 7.2.0 hdf63c60_3
        - ncurses 6.1 hfc679d8_1
        - openssl 1.0.2o h470a237_1
        - pip 18.0 py27_0
        - python 2.7.15 h9fef7bc_0
        - readline 7.0 haf1bffa_1
        - setuptools 40.0.0 py27_0
        - sqlite 3.24.0 h2f33b56_0
        - tk 8.6.8 0
        - wheel 0.31.1 py27_0
        - zlib 1.2.11 h470a237_3
    run:
        - python
test:
    imports:
        - cachetools
about:
    description: 'This module provides various memoizing collections and decorators,
        including variants of the Python 3 Standard Library @lru_cache function decorator.

        '
    dev_url: https://github.com/tkem/cachetools
    doc_url: http://pythonhosted.org/cachetools/
    home: https://github.com/tkem/cachetools
    license: MIT
    license_family: MIT
    license_file: LICENSE
    summary: Extensible memoizing collections and decorators
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - MaartenBreddels
