# This file created by conda-build 3.12.1
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sat Aug 11 15:51:55 2018
# ------------------------------------------------

package:
    name: libffi
    version: 3.2.1
source:
    patches:
        - configure_includedir_option.patch
    sha256: 96d08dee6f262beea1a18ac9a3801f64018dc4521895e9198d029d6850febe23
    url: https://github.com/libffi/libffi/archive/v3.2.1.tar.gz
build:
    number: '4'
    run_exports:
        - libffi >=3.2.1,<4.0a0
    string: hfc679d8_4
requirements:
    build:
        - autoconf 2.69 pl5.22.2.1_5
        - automake 1.15.1 pl5.22.2.1_0
        - libgcc-ng 7.2.0 hdf63c60_3
        - libtool 2.4.6 h470a237_1
        - m4 1.4.18 0
        - perl 5.22.2.1 0
        - texinfo 6.5 pl5.22.2.1_0
        - toolchain 2.1.6 0
        - toolchain_c_linux-64 2.1.6 0
        - toolchain_cxx_linux-64 2.1.6 0
    host:
        - libgcc-ng 7.2.0 hdf63c60_3
        - libstdcxx-ng 7.2.0 hdf63c60_3
    run:
        - libgcc-ng >=4.9
        - libstdcxx-ng >=4.9
test:
    commands:
        - test -e $PREFIX/lib/libffi${SHLIB_EXT}
        - test -e $PREFIX/lib/libffi.a
        - test -e $PREFIX/include/ffi.h
        - test -e $PREFIX/include/ffitarget.h
about:
    description: 'The libffi library provides a portable, high level programming interface

        to various calling conventions. This allows a programmer to call any

        function specified by a call interface description at run-time.

        '
    dev_url: https://github.com/libffi/libffi
    doc_url: https://sourceware.org/libffi/
    home: https://sourceware.org/libffi/
    license: Custom
    license_file: LICENSE
    summary: A Portable Foreign Function Interface Library.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - scopatz
        - stefan-balke
