# This file created by conda-build 3.0.27
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/bcolz-1.1.2-python3.6-on-nwani-linux-64, last modified Sat Oct 28 19:17:06 2017
# ------------------------------------------------

package:
    name: bcolz
    version: 1.1.2
source:
    fn: bcolz-1.1.2.tar.gz
    sha256: 42b733692cfb194df867f19168da1a9e468145a50c557758ecec911c6e5a4073
    url: https://pypi.io/packages/source/b/bcolz/bcolz-1.1.2.tar.gz
build:
    number: '0'
    script: python setup.py install --single-version-externally-managed --record record.txt
    string: py36h00f5784_0
requirements:
    build:
        - binutils_impl_linux-64 2.28.1 h04c84fa_2
        - binutils_linux-64 7.2.0 hc67e822_7
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.7.27.1 py36h8b7b77e_0
        - cython 0.26.1 py36h21c49d0_0
        - gcc_impl_linux-64 7.2.0 hc5ce805_2
        - gcc_linux-64 7.2.0 h22f992b_7
        - gxx_impl_linux-64 7.2.0 hd3faf3d_2
        - gxx_linux-64 7.2.0 h3aab023_7
        - intel-openmp 2018.0.0 h15fc484_7
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 h4deb6c0_3
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libgfortran-ng 7.2.0 h9f7466a_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - mkl 2018.0.0 hb491cac_4
        - ncurses 6.0 h06874d7_1
        - numpy 1.9.3 py36h35fcb08_3
        - openssl 1.0.2l h077ae2c_5
        - python 3.6.3 hefd0734_2
        - readline 7.0 hac23ff0_3
        - setuptools 36.5.0 py36he42e2e1_0
        - setuptools_scm 1.15.6 py36h9817af8_0
        - sqlite 3.20.1 h6d8b0f3_1
        - tk 8.6.7 h5979e9b_1
        - xz 5.2.3 h2bcbf08_1
        - zlib 1.2.11 hfbfcf68_1
    host:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2017.7.27.1 py36h8b7b77e_0
        - cython 0.26.1 py36h21c49d0_0
        - intel-openmp 2018.0.0 h15fc484_7
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 h4deb6c0_3
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libgfortran-ng 7.2.0 h9f7466a_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - mkl 2018.0.0 hb491cac_4
        - ncurses 6.0 h06874d7_1
        - numpy 1.9.3 py36h35fcb08_3
        - openssl 1.0.2l h077ae2c_5
        - python 3.6.3 hefd0734_2
        - readline 7.0 hac23ff0_3
        - setuptools 36.5.0 py36he42e2e1_0
        - setuptools_scm 1.15.6 py36h9817af8_0
        - sqlite 3.20.1 h6d8b0f3_1
        - tk 8.6.7 h5979e9b_1
        - xz 5.2.3 h2bcbf08_1
        - zlib 1.2.11 hfbfcf68_1
    run:
        - dask >=0.9.0
        - libgcc-ng 7.2.0.*
        - libstdcxx-ng 7.2.0.*
        - numexpr >=2.5.2
        - numpy  >=1.9.3,<2.0a0
        - pandas
        - pytables
        - python >=3.6,<3.7.0a0
test:
    commands:
        - python -c"import bcolz; bcolz.test(heavy=True)"
        - python -c"import bcolz; assert set(bcolz.blosc_compressor_list()) == set(['blosclz',
            'lz4', 'lz4hc', 'snappy', 'zlib', 'zstd'])"
    imports:
        - bcolz
    requires:
        - mock
about:
    dev_url: http://github.com/Blosc/bcolz
    doc_url: http://bcolz.blosc.org/
    home: http://github.com/Blosc/bcolz
    license: MIT
    license_family: MIT
    license_file: LICENSES/BCOLZ.txt
    summary: A columnar data container that can be compressed
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - CarstVaartjes
        - FrancescAlted
        - alimanfoo
