# This file created by conda-build 3.12.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Thu Aug  2 20:32:42 2018
# ------------------------------------------------

package:
    name: google-auth
    version: 1.5.1
source:
    fn: google-auth-1.5.1.tar.gz
    sha256: 9ca363facbf2622d9ba828017536ccca2e0f58bd15e659b52f312172f8815530
    url: https://pypi.io/packages/source/g/google-auth/google-auth-1.5.1.tar.gz
build:
    noarch: python
    number: '0'
    script: python -m pip install --no-deps --ignore-installed .
    string: py_0
requirements:
    build:
        - bzip2 1.0.6 h470a237_2
        - ca-certificates 2018.4.16 0
        - certifi 2018.4.16 py27_0
        - libgcc-ng 7.2.0 hdf63c60_3
        - libstdcxx-ng 7.2.0 hdf63c60_3
        - ncurses 6.1 hfc679d8_1
        - openssl 1.0.2o h470a237_1
        - pip 18.0 py27_1
        - python 2.7.15 h9fef7bc_0
        - readline 7.0 haf1bffa_1
        - setuptools 40.0.0 py27_1
        - sqlite 3.24.0 h2f33b56_0
        - tk 8.6.8 0
        - wheel 0.31.1 py27_1
        - zlib 1.2.11 h470a237_3
    run:
        - cachetools >=2.0.0,<3dev
        - pyasn1-modules >=0.2.1
        - python
        - rsa >=3.1.4,<4dev
        - six >=1.9.0,<2dev
test:
    imports:
        - google.auth
about:
    description: This library provides the ability to authenticate to Google APIs
        using various methods. It also provides integration with several HTTP libraries.
    dev_url: https://github.com/GoogleCloudPlatform/google-auth-library-python
    doc_url: https://google-auth.readthedocs.io/en/latest/
    home: https://github.com/GoogleCloudPlatform/google-auth-library-python
    license: Apache-2.0
    license_family: Apache
    license_file: LICENSE
    summary: Google authentication library for Python
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jreback
        - parthea
        - theacodes
        - tswast
