# This file created by conda-build 2.1.18
# meta.yaml template originally from:
# /recipe_root, last modified Tue Mar  6 04:58:45 2018
# ------------------------------------------------

package:
    name: toolz
    version: 0.9.0
source:
    fn: toolz-0.9.0.tar.gz
    sha256: 929f0a7ea7f61c178bd951bdae93920515d3fbdbafc8e6caf82d752b9b3b31c9
    url: https://pypi.io/packages/source/t/toolz/toolz-0.9.0.tar.gz
build:
    noarch: python
    noarch_python: false
    number: '0'
    script: python -m pip install --no-deps --ignore-installed .
    string: py_0
requirements:
    build:
        - certifi 2018.1.18 py36_0
        - python 3.6.4 0
        - xz 5.2.3 0
        - openssl 1.0.2n 0
        - pip 9.0.1 py36_1
        - readline 7.0 0
        - setuptools 38.5.1 py36_0
        - zlib 1.2.11 0
        - tk 8.6.7 0
        - ca-certificates 2018.1.18 0
        - ncurses 5.9 10
        - wheel 0.30.0 py36_2
        - sqlite 3.20.1 2
    run:
        - python
test:
    imports:
        - toolz
        - toolz.curried
        - toolz.sandbox
about:
    home: http://toolz.readthedocs.org/
    license: BSD 3-Clause
    license_file: LICENSE.txt
    summary: A functional standard library for Python.
extra:
    final: true
    recipe-maintainers:
        - mrocklin
        - eriknw
        - jcrist
        - jakirkham
