# This file created by conda-build 3.13.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Aug 28 22:41:35 2018
# ------------------------------------------------

package:
    name: pyproj
    version: 1.9.5.1
source:
    sha256: 0e19f02ebbf4c253813142ffe06e12489f3861877c3fab75b6c769c1a1960cac
    url: https://github.com/jswhit/pyproj/archive/v1.9.5.1rel.tar.gz
build:
    number: '2'
    script:
        - rm -d _proj.c
        - export PROJ_DIR="${PREFIX}"
        - cythonize -a -i _proj.pyx
        - /home/conda/feedstock_root/build_artifacts/pyproj_1535496203733/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
            -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
    string: py36h58270c7_2
requirements:
    build:
        - toolchain 2.1.6 0
        - toolchain_c_linux-64 2.1.6 0
    host:
        - bzip2 1.0.6 h470a237_2
        - ca-certificates 2018.8.24 ha4d7672_0
        - certifi 2018.8.24 py36_1
        - cython 0.28.5 py36hfc679d8_0
        - libffi 3.2.1 hfc679d8_4
        - libgcc-ng 7.2.0 hdf63c60_3
        - libstdcxx-ng 7.2.0 hdf63c60_3
        - ncurses 6.1 hfc679d8_1
        - openssl 1.0.2o h470a237_1
        - pip 18.0 py36_1
        - proj4 5.1.0 h470a237_1
        - python 3.6.6 h5001a0f_0
        - readline 7.0 haf1bffa_1
        - setuptools 40.2.0 py36_0
        - sqlite 3.24.0 h2f33b56_0
        - tk 8.6.8 0
        - wheel 0.31.1 py36_1
        - xz 5.2.4 h470a237_1
        - zlib 1.2.11 h470a237_3
    run:
        - libgcc-ng >=4.9
        - numpy
        - proj4 >=5.1.0,<5.1.1.0a0
        - python >=3.6,<3.7.0a0
test:
    imports:
        - pyproj
about:
    home: https://github.com/jswhit/pyproj
    license: OSI
    license_file: LICENSE
    summary: Python interface to PROJ.4 library
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - mingwandroid
        - ocefpaf
