# This file created by conda-build 2.1.17
# meta.yaml template originally from:
# /recipe_root, last modified Sun Aug 13 19:19:47 2017
# ------------------------------------------------

package:
    name: qtconsole
    version: 4.3.1
source:
    fn: qtconsole-4.3.1.tar.gz
    sha256: eff8c2faeda567a0bef5781f419a64e9977988db101652b312b9d74ec0a5109c
    url: https://pypi.io/packages/source/q/qtconsole/qtconsole-4.3.1.tar.gz
build:
    noarch: ''
    noarch_python: false
    number: '0'
    script: python setup.py install
    string: py36_0
requirements:
    build:
        - ncurses 5.9 10
        - python-dateutil 2.6.1 py36_0
        - readline 6.2 0
        - tk 8.5.19 2
        - expat 2.2.1 0
        - jedi 0.10.2 py36_0
        - ca-certificates 2017.7.27.1 0
        - libxml2 2.9.4 4
        - libiconv 1.14 4
        - fontconfig 2.12.1 4
        - traitlets 4.3.2 py36_0
        - qt 5.6.2 3
        - ipykernel 4.6.1 py36_0
        - libpng 1.6.28 0
        - libsodium 1.0.10 0
        - decorator 4.1.2 py36_0
        - zlib 1.2.11 0
        - xorg-libxdmcp 1.1.2 3
        - icu 58.1 1
        - sip 4.18 py36_1
        - gettext 0.19.7 1
        - gstreamer 1.8.0 2
        - jupyter_client 5.1.0 py36_0
        - ipython 6.1.0 py36_0
        - certifi 2017.7.27.1 py36_0
        - python 3.6.2 0
        - wcwidth 0.1.7 py36_0
        - six 1.10.0 py36_1
        - sqlite 3.13.0 1
        - setuptools 36.2.2 py36_0
        - gst-plugins-base 1.8.0 0
        - openssl 1.0.2l 0
        - jupyter_core 4.3.0 py36_0
        - xz 5.2.2 0
        - glib 2.51.4 0
        - pyzmq 16.0.2 py36_2
        - pyqt 5.6.0 py36_4
        - pcre 8.39 0
        - jpeg 9b 0
        - zeromq 4.2.1 1
        - tornado 4.5.1 py36_0
        - ptyprocess 0.5.2 py36_0
        - freetype 2.7 1
        - xorg-libxau 1.0.8 3
        - prompt_toolkit 1.0.15 py36_0
        - pickleshare 0.7.3 py36_0
        - dbus 1.10.10 3
        - ipython_genutils 0.2.0 py36_0
        - pexpect 4.2.1 py36_0
        - libffi 3.2.1 3
        - pygments 2.2.0 py36_0
        - simplegeneric 0.8.1 py36_0
        - libxcb 1.12 1
    run:
        - python
        - ipykernel >=4.1
        - jupyter_client >=4.1
        - jupyter_core
        - pygments
        - pyqt
        - traitlets
test:
    commands:
        - DISPLAY=localhost:1.0 xvfb-run -a bash -c 'jupyter qtconsole --help'
    imports:
        - qtconsole
        - qtconsole.tests
about:
    home: http://jupyter.org
    license: BSD 3-Clause
    license_file: COPYING.md
    summary: Jupyter Qt console
extra:
    final: true
    recipe-maintainers:
        - Carreau
        - ccordoba12
        - jakirkham
        - minrk
        - takluyver
        - ocefpaf
