# This file created by conda-build 2.1.18
# meta.yaml template originally from:
# /recipe_root, last modified Thu Feb 22 01:54:42 2018
# ------------------------------------------------

package:
    name: hdf5
    version: 1.10.1
source:
    fn: hdf5-1.10.1.tar.gz
    patches:
        - test_Makefile.in.patch
    sha256: 048a9d149fb99aaa1680a712963f5a78e9c43b588d0e79d55e06760ec377c172
    url: https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.1/src/hdf5-1.10.1.tar.gz
build:
    detect_binary_files_with_prefix: 'True'
    features: ''
    noarch: ''
    noarch_python: false
    number: '2'
    string: '2'
requirements:
    build:
        - xz 5.2.3 0
        - openssl 1.0.2n 0
        - bzip2 1.0.6 1
        - rhash 1.3.4 0
        - zlib 1.2.11 0
        - cmake 3.10.0 4
        - expat 2.2.5 0
        - libssh2 1.8.0 2
        - libuv 1.11.0 0
        - krb5 1.14.2 0
        - libgfortran 3.0.0 1
        - ca-certificates 2018.1.18 0
        - ncurses 5.9 10
        - curl 7.55.1 0
        - libtool 2.4.6 0
        - toolchain 2.1.2 0
    run:
        - zlib 1.2.11
        - libgfortran
test:
    commands:
        - command -v h5c++
        - command -v h5cc
        - command -v h5perf_serial
        - command -v h5redeploy
        - command -v h5fc
        - command -v gif2h5
        - command -v h52gif
        - command -v h5copy
        - command -v h5debug
        - command -v h5diff
        - command -v h5dump
        - command -v h5import
        - command -v h5jam
        - command -v h5ls
        - command -v h5mkgrp
        - command -v h5repack
        - command -v h5repart
        - command -v h5stat
        - command -v h5unjam
        - test -f $PREFIX/lib/libhdf5.a
        - test -f $PREFIX/lib/libhdf5.so
        - test -f $PREFIX/lib/libhdf5_cpp.a
        - test -f $PREFIX/lib/libhdf5_cpp.so
        - test -f $PREFIX/lib/libhdf5_hl.a
        - test -f $PREFIX/lib/libhdf5_hl.so
        - test -f $PREFIX/lib/libhdf5_hl_cpp.a
        - test -f $PREFIX/lib/libhdf5_hl_cpp.so
        - conda inspect linkages -p $PREFIX $PKG_NAME
    files:
        - h5_cmprss.c
        - h5tutr_cmprss.cpp
        - h5_cmprss.f90
        - compound_fortran2003.f90
    requires: ''
about:
    home: http://www.hdfgroup.org/HDF5/
    license: HDF5
    license_family: BSD
    license_file: COPYING
    summary: HDF5 is a data model, library, and file format for storing and managing
        data
extra:
    final: true
    recipe-maintainers:
        - jakirkham
        - gillins
        - groutr
        - ocefpaf
        - astrofrog-conda-forge
        - marqh
