# This file created by conda-build 3.13.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Aug 28 01:04:37 2018
# ------------------------------------------------

package:
    name: jupyter_console
    version: 5.2.0
source:
    sha256: 545dedd3aaaa355148093c5609f0229aeb121b4852995c2accfa64fe3e0e55cd
    url: https://pypi.io/packages/source/j/jupyter_console/jupyter_console-5.2.0.tar.gz
build:
    entry_points:
        - jupyter-console = jupyter_console.app:main
    number: '1'
    script: /home/conda/feedstock_root/build_artifacts/jupyter_console_1535418386254/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
        -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
    string: py36_1
requirements:
    host:
        - bzip2 1.0.6 h470a237_2
        - ca-certificates 2018.8.24 ha4d7672_0
        - certifi 2018.8.24 py36_1
        - libffi 3.2.1 hfc679d8_4
        - libgcc-ng 7.2.0 hdf63c60_3
        - libstdcxx-ng 7.2.0 hdf63c60_3
        - ncurses 6.1 hfc679d8_1
        - openssl 1.0.2o h470a237_1
        - pip 18.0 py36_1
        - python 3.6.6 h5001a0f_0
        - readline 7.0 haf1bffa_1
        - setuptools 40.2.0 py36_0
        - sqlite 3.24.0 h2f33b56_0
        - tk 8.6.8 0
        - wheel 0.31.1 py36_1
        - xz 5.2.4 h470a237_1
        - zlib 1.2.11 h470a237_3
    run:
        - ipykernel
        - ipython
        - jupyter_client
        - pexpect
        - prompt_toolkit >=1.0.0,<2.0.0
        - pygments
        - python >=3.6,<3.7.0a0
test:
    commands:
        - jupyter-console -h
    imports:
        - jupyter_console
about:
    home: http://jupyter.org
    license: BSD-3-Clause
    license_file: COPYING.md
    summary: Jupyter terminal console
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - minrk
        - ocefpaf
        - pelson
        - takluyver
