# This file created by conda-build 3.10.1
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed May  2 15:56:36 2018
# ------------------------------------------------

package:
    name: pandas
    version: 0.22.0
source:
    sha256: 44a94091dd71f05922eec661638ec1a35f26d573c119aa2fad964f10a2880e6c
    url: https://pypi.io/packages/source/p/pandas/pandas-0.22.0.tar.gz
build:
    number: '1'
    script: python -m pip install --no-deps --ignore-installed .
    string: py36_1
requirements:
    build:
        - blas 1.1 openblas
        - ca-certificates 2018.4.16 0
        - certifi 2018.4.16 py36_0
        - cython 0.28.2 py36_0
        - libgfortran 3.0.0 1
        - ncurses 5.9 10
        - numpy 1.11.3 py36_blas_openblas_203
        - openblas 0.2.20 7
        - openssl 1.0.2o 0
        - pip 9.0.3 py36_0
        - python 3.6.5 1
        - readline 7.0 0
        - setuptools 39.1.0 py36_0
        - sqlite 3.20.1 2
        - tk 8.6.7 0
        - wheel 0.31.0 py36_0
        - xz 5.2.3 0
        - zlib 1.2.11 0
    run:
        - numpy >=1.11.*
        - python >=3.6,<3.7.0a0
        - python-dateutil
        - pytz
test:
    commands:
        - conda inspect linkages -p $PREFIX $PKG_NAME
    imports:
        - pandas
about:
    home: http://pandas.pydata.org
    license: BSD 3-clause
    license_file: LICENSE
    summary: High-performance, easy-to-use data structures and data analysis tools.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - TomAugspurger
        - jorisvandenbossche
        - jreback
        - msarahan
        - ocefpaf
