# This file created by conda-build 3.5.0
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/pysocks-1.6.8-python3.6-on-linux_64, last modified Tue Feb 27 16:32:17 2018
# ------------------------------------------------

package:
    name: pysocks
    version: 1.6.8
source:
    fn: PySocks-1.6.8.tar.gz
    sha256: 3fe52c55890a248676fd69dc9e3c4e811718b777834bcaab7a8125cf9deac672
    url: https://pypi.io/packages/source/P/PySocks/PySocks-1.6.8.tar.gz
build:
    number: '0'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py36_0
requirements:
    host:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - certifi 2018.1.18 py36_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - ncurses 6.0 h9df7e31_2
        - openssl 1.0.2n hb7f436b_0
        - python 3.6.4 hc3d631a_1
        - readline 7.0 ha6073c6_4
        - setuptools 38.5.1 py36_0
        - sqlite 3.22.0 h1bed415_0
        - tk 8.6.7 hc745277_3
        - xz 5.2.3 h55aa19d_2
        - zlib 1.2.11 ha838bed_2
    run:
        - python >=3.6,<3.7.0a0
test:
    imports:
        - socks
about:
    dev_url: https://github.com/Anorov/PySocks
    doc_url: https://github.com/Anorov/PySocks/blob/master/README.md
    home: https://github.com/Anorov/PySocks
    license: BSD 3-Clause
    license_family: BSD
    license_file: LICENSE
    summary: A Python SOCKS client module. See https://github.com/Anorov/PySocks for
        more information.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - pmlandwehr
