# This file created by conda-build 3.13.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Fri Aug 24 11:52:27 2018
# ------------------------------------------------

package:
    name: ca-certificates
    version: 2018.8.24
source:
    fn: certifi-2018.8.24.tar.gz
    sha256: 376690d6f16d32f9d1fe8932551d80b23e9d393a8578c5633a2ed39a64861638
    url: https://pypi.io/packages/source/c/certifi/certifi-2018.8.24.tar.gz
build:
    number: '0'
    string: ha4d7672_0
test:
    commands:
        - test -f "${PREFIX}/ssl/cacert.pem"
        - test -f "${PREFIX}/ssl/cert.pem"
        - curl --cacert "${PREFIX}/ssl/cacert.pem" https://www.google.com
    requires:
        - curl
about:
    home: https://github.com/conda-forge/ca-certificates-feedstock
    license: ISC
    license_file: LICENSE
    summary: Certificates for use with other packages.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - msarahan
        - mwcraig
        - ocefpaf
        - patricksnape
        - pelson
        - scopatz
