# This file created by conda-build 3.12.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Thu Jul 26 10:57:27 2018
# ------------------------------------------------

package:
    name: mistune
    version: 0.8.3
source:
    sha256: bc10c33bfdcaa4e749b779f62f60d6e12f8215c46a292d05e486b869ae306619
    url: https://pypi.io/packages/source/m/mistune/mistune-0.8.3.tar.gz
build:
    number: '2'
    script: python -m pip install --no-deps --ignore-installed .
    string: py36h470a237_2
requirements:
    build:
        - toolchain 2.1.6 0
        - toolchain_c_linux-64 2.1.6 0
    host:
        - bzip2 1.0.6 h470a237_2
        - ca-certificates 2018.4.16 0
        - certifi 2018.4.16 py36_0
        - cython 0.28.4 py36hfc679d8_0
        - libffi 3.2.1 3
        - libgcc-ng 7.2.0 hdf63c60_3
        - libstdcxx-ng 7.2.0 hdf63c60_3
        - ncurses 6.1 0
        - openssl 1.0.2o 0
        - pip 18.0 py36_0
        - python 3.6.6 h5001a0f_0
        - readline 7.0 haf1bffa_1
        - setuptools 40.0.0 py36_0
        - sqlite 3.24.0 h2f33b56_0
        - tk 8.6.8 0
        - wheel 0.31.1 py36_0
        - xz 5.2.3 0
        - zlib 1.2.11 h470a237_3
    run:
        - libgcc-ng >=4.9
        - python >=3.6,<3.7.0a0
test:
    commands:
        - nosetests
    imports:
        - mistune
    requires:
        - nose
        - python >=3.6,<3.7.0a0
    source_files:
        - tests
about:
    dev_url: https://github.com/lepture/mistune
    doc_url: https://mistune.readthedocs.io/
    home: https://github.com/lepture/mistune
    license: BSD 3-Clause
    license_family: BSD
    license_file: LICENSE
    summary: The fastest markdown parser in pure Python.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - bollwyvl
        - ocefpaf
        - pelson
