# This file created by conda-build 3.13.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed Aug 29 11:13:37 2018
# ------------------------------------------------

package:
    name: openssl
    version: 1.0.2p
source:
    fn: openssl-1.0.2p.tar.gz
    sha256: 50a98e07b1a89eb8f6a99477f262df71c6fa7bef77df4dc83025a2845c827d00
    url: http://www.openssl.org/source/openssl-1.0.2p.tar.gz
build:
    has_prefix_files:
        - bin/c_rehash
        - include/openssl/opensslconf.h
        - lib/pkgconfig/libcrypto.pc
        - lib/pkgconfig/libssl.pc
        - lib/pkgconfig/openssl.pc
    no_link: lib/libcrypto.so.1.0.0
    number: '0'
    run_exports:
        - openssl >=1.0.2p,<1.0.3a
    string: h470a237_0
requirements:
    build:
        - libgcc-ng 7.2.0 hdf63c60_3
        - make 4.2.1 h470a237_1002
        - perl 5.26.2 h470a237_0
        - toolchain 2.1.6 0
        - toolchain_c_linux-64 2.1.6 0
    host:
        - libgcc-ng 7.2.0 hdf63c60_3
    run:
        - ca-certificates
        - libgcc-ng >=4.9
test:
    commands:
        - touch checksum.txt
        - openssl sha256 checksum.txt
about:
    dev_url: https://github.com/openssl/openssl
    doc_url: https://www.openssl.org/docs/man1.0.2/
    home: http://www.openssl.org/
    license: OpenSSL
    license_family: Apache
    license_file: LICENSE
    summary: OpenSSL is an open-source implementation of the SSL and TLS protocols
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - msarahan
        - ocefpaf
        - pelson
