# This file created by conda-build 3.10.9
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Jul 10 15:22:11 2018
# ------------------------------------------------

package:
    name: pycparser
    version: '2.18'
source:
    fn: pycparser-2.18.tar.gz
    sha256: 99a8ca03e29851d96616ad0404b4aad7d9ee16f25c9f9708a11faf2810f7b226
    url: https://pypi.io/packages/source/p/pycparser/pycparser-2.18.tar.gz
build:
    noarch: python
    number: '1'
    script: python -m pip install --no-deps --ignore-installed .
    string: py_1
requirements:
    host:
        - ca-certificates 2018.4.16 0
        - certifi 2018.4.16 py27_0
        - libgcc-ng 7.2.0 hdf63c60_3
        - ncurses 5.9 10
        - openssl 1.0.2o 0
        - pip 9.0.3 py27_0
        - python 2.7.15 0
        - readline 7.0 0
        - setuptools 40.0.0 py27_0
        - sqlite 3.20.1 2
        - tk 8.6.7 0
        - wheel 0.31.1 py27_0
        - zlib 1.2.11 h470a237_3
    run:
        - python
test:
    imports:
        - pycparser
        - pycparser.ply
about:
    description: 'pycparser is a complete parser of the C language, written in pure
        Python using the PLY parsing library.

        It parses C code into an AST and can serve as a front-end for C compilers
        or analysis tools.

        '
    dev_url: https://github.com/eliben/pycparser
    home: https://github.com/eliben/pycparser
    license: BSD 3-clause
    license_file: LICENSE
    summary: Complete C99 parser in pure Python
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - synapticarbors
