# This file created by conda-build 2.1.10
# meta.yaml template originally from:
# /recipe_root, last modified Sat Jun  3 13:10:12 2017
# ------------------------------------------------

package:
    name: lmfit
    version: 0.9.7
source:
    fn: lmfit-0.9.7.tar.gz
    sha256: 3cb3240be8f116a9924f0d0e6717f7db13d437d8fa2984fa17992b019e16a678
    url: https://github.com/lmfit/lmfit-py/archive/0.9.7.tar.gz
build:
    noarch: ''
    noarch_python: false
    number: '0'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py36_0
requirements:
    build:
        - sqlite 3.13.0 1
        - certifi 2017.4.17 py36_0
        - tk 8.5.19 1
        - openblas 0.2.19 2
        - setuptools 33.1.1 py36_0
        - ca-certificates 2017.4.17 0
        - six 1.10.0 py36_1
        - zlib 1.2.11 0
        - libgfortran 3.0.0 1
        - ncurses 5.9 10
        - xz 5.2.2 0
        - blas 1.1 openblas
        - numpy 1.12.1 py36_blas_openblas_200
        - scipy 0.19.0 np112py36_blas_openblas_200
        - openssl 1.0.2k 0
        - readline 6.2 0
        - python 3.6.1 3
    run:
        - python
        - numpy
        - scipy
        - six
test:
    imports:
        - lmfit
about:
    home: http://lmfit.github.io/lmfit-py/
    license: lmfit
    license_family: BSD
    summary: 'Non-Linear Least Squares Minimization, with flexible Parameter settings,
        based on scipy.optimize.leastsq, and with many additional classes and methods
        for curve fitting http:/lmfit.github.io/lmfit-py/

        '
extra:
    final: true
    recipe-maintainers:
        - ericdill
        - tacaswell
        - licode
        - newville
        - danielballan
        - tritemio
