# This file created by conda-build 3.13.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Thu Aug 30 19:56:47 2018
# ------------------------------------------------

package:
    name: cartopy
    version: 0.16.0
source:
    sha256: cadf62434492c965220b37f0548bc58180466ad6894a1db57dbc51cd43467e5c
    url: https://github.com/SciTools/cartopy/archive/v0.16.0.tar.gz
build:
    number: '1'
    string: py36hf1a2d64_1
requirements:
    build:
        - toolchain 2.1.6 0
        - toolchain_c_linux-64 2.1.6 0
        - toolchain_cxx_linux-64 2.1.6 0
    host:
        - blas 1.1 openblas
        - bzip2 1.0.6 h470a237_2
        - ca-certificates 2018.8.24 ha4d7672_0
        - certifi 2018.8.24 py36_1
        - cython 0.28.5 py36hfc679d8_0
        - geos 3.6.2 hfc679d8_2
        - libffi 3.2.1 hfc679d8_4
        - libgcc-ng 7.2.0 hdf63c60_3
        - libgfortran 3.0.0 1
        - libstdcxx-ng 7.2.0 hdf63c60_3
        - ncurses 6.1 hfc679d8_1
        - numpy 1.9.3 py36_blas_openblashd3ea46f_206
        - openblas 0.2.20 8
        - openssl 1.0.2p h470a237_0
        - pip 18.0 py36_1
        - proj4 5.1.0 h470a237_1
        - python 3.6.6 h5001a0f_0
        - readline 7.0 haf1bffa_1
        - setuptools 40.2.0 py36_0
        - sqlite 3.24.0 h2f33b56_0
        - tk 8.6.8 0
        - wheel 0.31.1 py36_1
        - xz 5.2.4 h470a237_1
        - zlib 1.2.11 h470a237_3
    run:
        - geos >=3.6.2,<3.6.3.0a0
        - geos >=3.6.2,<3.6.3.0a0
        - libgcc-ng >=4.9
        - libstdcxx-ng >=4.9
        - matplotlib
        - numpy >=1.9.3,<2.0a0
        - owslib
        - pillow
        - proj4 >=5.1.0,<5.1.1.0a0
        - proj4 >=5.1.0,<5.1.1.0a0
        - pyepsg
        - pyshp
        - python >=3.6,<3.7.0a0
        - scipy
        - shapely
        - six
test:
    imports:
        - cartopy
        - cartopy.crs
        - cartopy.mpl.geoaxes
about:
    home: http://scitools.org.uk/cartopy
    license: GNU LGPL
    license_file: COPYING
    summary: A library providing cartographic tools for python.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - dopplershift
        - marqh
        - ocefpaf
        - pelson
