# This file created by conda-build 2.1.18
# meta.yaml template originally from:
# /recipe_root, last modified Fri Mar  2 13:21:28 2018
# ------------------------------------------------

package:
    name: peakutils
    version: 1.1.1
source:
    sha256: 8e06b7a2f793fffd8ab144b15c218097072f07285f567c8c021e35d9d96d6de1
    url: https://pypi.io/packages/source/P/PeakUtils/PeakUtils-1.1.1.tar.gz
build:
    noarch: python
    noarch_python: false
    number: '0'
    script: python -m pip install --no-deps --ignore-installed .
    string: py_0
requirements:
    build:
        - certifi 2018.1.18 py36_0
        - python 3.6.4 0
        - xz 5.2.3 0
        - openssl 1.0.2n 0
        - pip 9.0.1 py36_1
        - readline 7.0 0
        - setuptools 38.5.1 py36_0
        - zlib 1.2.11 0
        - tk 8.6.7 0
        - ca-certificates 2018.1.18 0
        - ncurses 5.9 10
        - wheel 0.30.0 py36_2
        - sqlite 3.20.1 2
    run:
        - python
        - numpy >=1.8
        - scipy >=0.14
test:
    imports:
        - peakutils
about:
    description: 'This package provides utilities related to the detection of peaks
        on

        1D data. Includes functions to estimate baselines, finding the

        indexes of peaks in the data and performing Gaussian fitting or centroid

        computation to further increase the resolution of the peak detection.

        '
    dev_url: https://bitbucket.org/lucashnegri/peakutils/
    doc_url: http://pythonhosted.org/PeakUtils/
    home: https://bitbucket.org/lucashnegri/peakutils
    license: MIT
    license_family: MIT
    license_file: LICENSE.txt
    summary: Peak detection utilities for 1D data
extra:
    final: true
    recipe-maintainers:
        - xmnlab
