# This file created by conda-build 2.1.2
# meta.yaml template originally from:
# /recipe_root, last modified Thu Feb  9 13:52:52 2017
# ------------------------------------------------

package:
    name: readline
    version: '7.0'
source:
    fn: readline-7.0.tar.gz
    patches:
        - patches/readline70-001
    sha256: 750d437185286f40a369e1e4f4764eda932b9459b5ec9a731628393dd3d32334
    url: ftp://ftp.gnu.org/gnu/readline/readline-7.0.tar.gz
build:
    number: '0'
    string: '0'
requirements:
    build: []
    run:
        - ncurses 5.9*
test:
    commands:
        - test -f ${PREFIX}/lib/libreadline.a
        - test -f ${PREFIX}/lib/libreadline.so
        - test -f ${PREFIX}/lib/libhistory.a
        - test -f ${PREFIX}/lib/libhistory.so
about:
    home: https://cnswww.cns.cwru.edu/php/chet/readline/rltop.html
    license: GPL3
    summary: library for editing command lines as they are typed in
extra:
    recipe-maintainers:
        - croth1
        - jakirkham
        - jjhelmus
        - pelson
        - msarahan
        - asmeurer
