# This file created by conda-build 3.10.8
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Thu Jun 14 23:29:01 2018
# ------------------------------------------------

package:
    name: yarl
    version: 1.2.6
source:
    fn: yarl-1.2.6.tar.gz
    sha256: c8cbc21bbfa1dd7d5386d48cc814fe3d35b80f60299cdde9279046f399c3b0d8
    url: https://pypi.io/packages/source/y/yarl/yarl-1.2.6.tar.gz
build:
    number: '0'
    script: python -m pip install --no-deps --ignore-installed .
    string: py36h470a237_0
requirements:
    build:
        - toolchain 2.1.5 0
        - toolchain_c_linux-64 2.1.5 0
    host:
        - ca-certificates 2018.4.16 0
        - certifi 2018.4.16 py36_0
        - libgcc-ng 7.2.0 hdf63c60_3
        - ncurses 5.9 10
        - openssl 1.0.2o 0
        - pip 9.0.3 py36_0
        - python 3.6.5 1
        - readline 7.0 0
        - setuptools 39.2.0 py36_0
        - sqlite 3.20.1 2
        - tk 8.6.7 0
        - wheel 0.31.0 py36_0
        - xz 5.2.3 0
        - zlib 1.2.11 h470a237_3
    run:
        - idna >=2.0
        - libgcc-ng >=4.9
        - multidict >=4.0
        - python >=3.6,<3.7.0a0
test:
    commands:
        - py.test tests
    requires:
        - pytest
    source_files:
        - tests
about:
    dev_url: https://github.com/aio-libs/yarl
    doc_source_url: https://github.com/aio-libs/yarl/tree/master/docs
    doc_url: http://yarl.readthedocs.io
    home: https://github.com/aio-libs/yarl
    license: Apache 2.0
    license_family: Apache
    license_file: LICENSE
    summary: Yet another URL library
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - sodre
