# This file created by conda-build 3.8.1
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/sqlite-3.23.1-on-linux_64, last modified Fri Apr 20 02:58:26 2018
# ------------------------------------------------

package:
    name: sqlite
    version: 3.23.1
source:
    fn: sqlite-autoconf-3230100.tar.gz
    sha1: 0edbfd75ececb95e8e6448d6ff33df82774c9646
    url: https://www.sqlite.org/2018/sqlite-autoconf-3230100.tar.gz
build:
    number: '0'
    run_exports:
        - sqlite >=3.23.1,<4.0a0
    string: he433501_0
requirements:
    build:
        - binutils_impl_linux-64 2.28.1 had2808c_3
        - binutils_linux-64 7.2.0 26
        - gcc_impl_linux-64 7.2.0 habb00fd_3
        - gcc_linux-64 7.2.0 26
        - libgcc-ng 7.2.0 hdf63c60_3
        - libstdcxx-ng 7.2.0 hdf63c60_3
        - make 4.2.1 h1bed415_1
    commands:
        - sqlite3 --version
    host:
        - libedit 3.1 heed3624_0
        - libgcc-ng 7.2.0 hdf63c60_3
        - libstdcxx-ng 7.2.0 hdf63c60_3
        - ncurses 6.0 h9df7e31_2
    run:
        - libedit
        - libgcc-ng >=7.2.0
about:
    description: 'SQLite is a self-contained, high-reliability, embedded, full-featured,

        public-domain, SQL database engine.It is the most used database engine

        in the world.

        '
    dev_url: https://github.com/mackyle/sqlite
    doc_source_url: https://github.com/mackyle/sqlite/tree/master/doc
    doc_url: http://www.sqlite.org/docs.html
    home: http://www.sqlite.org/
    license: Public-Domain (http://www.sqlite.org/copyright.html)
    license_url: http://www.sqlite.org/copyright.html
    summary: Implements a self-contained, zero-configuration, SQL database engine.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - mingwandroid
        - msarahan
        - ocefpaf
