# This file created by conda-build 3.13.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Fri Aug 24 15:02:37 2018
# ------------------------------------------------

package:
    name: cloudpickle
    version: 0.5.5
source:
    fn: cloudpickle-0.5.5.tar.gz
    sha256: 6ea4b548f61a4f616b065182716318c7dced8c053517f35ac59cec22802daf3d
    url: https://pypi.io/packages/source/c/cloudpickle/cloudpickle-0.5.5.tar.gz
build:
    noarch: python
    number: '0'
    script: python -m pip install --no-deps --ignore-installed .
    string: py_0
requirements:
    build:
        - bzip2 1.0.6 h470a237_2
        - ca-certificates 2018.8.24 ha4d7672_0
        - certifi 2018.8.24 py27_1
        - libgcc-ng 7.2.0 hdf63c60_3
        - libstdcxx-ng 7.2.0 hdf63c60_3
        - ncurses 6.1 hfc679d8_1
        - openssl 1.0.2o h470a237_1
        - pip 18.0 py27_1
        - python 2.7.15 h9fef7bc_0
        - readline 7.0 haf1bffa_1
        - setuptools 40.2.0 py27_0
        - sqlite 3.24.0 h2f33b56_0
        - tk 8.6.8 0
        - wheel 0.31.1 py27_1
        - zlib 1.2.11 h470a237_3
    run:
        - python
test:
    imports:
        - cloudpickle
about:
    description: 'cloudpickle is extended pickling support for Python objects.

        cloudpickle makes it possible to serialize Python constructs not

        supported by the default pickle module from the Python standard library.

        '
    dev_url: https://github.com/cloudpipe/cloudpickle
    doc_source_url: https://github.com/cloudpipe/cloudpickle/blob/master/README.md
    doc_url: https://pypi.python.org/pypi/cloudpickle/0.5.5
    home: https://github.com/cloudpipe/cloudpickle
    license: BSD 3-Clause
    license_file: LICENSE
    summary: Extended pickling support for Python objects
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - mrocklin
        - nehaljwani
        - ogrisel
        - rgbkrk
