# This file created by conda-build 2.1.18
# meta.yaml template originally from:
# /recipe_root, last modified Thu Mar 29 21:19:31 2018
# ------------------------------------------------

package:
    name: matplotlib
    version: 2.2.2
source:
    patches:
        - cfg_qt5agg.patch
    sha256: 3a8236e6747dbb48c342ee194a8ced2805205cbd718899b284e4d617189cd397
    url: https://github.com/matplotlib/matplotlib/archive/v2.2.2.tar.gz
build:
    noarch: ''
    noarch_python: false
    number: '1'
    string: py36_1
requirements:
    build:
        - freetype 2.8.1 0
        - gst-plugins-base 1.8.0 0
        - certifi 2018.1.18 py36_0
        - python 3.6.4 0
        - libpng 1.6.34 0
        - xz 5.2.3 0
        - openssl 1.0.2n 0
        - cycler 0.10.0 py36_0
        - openblas 0.2.20 7
        - xorg-libxdmcp 1.1.2 3
        - readline 7.0 0
        - gstreamer 1.8.0 1
        - zlib 1.2.11 0
        - fontconfig 2.12.6 0
        - dbus 1.10.22 0
        - sip 4.18 py36_1
        - pytz 2018.3 py_0
        - libiconv 1.15 0
        - xorg-libxau 1.0.8 3
        - libffi 3.2.1 3
        - libxcb 1.13 0
        - qt 5.6.2 7
        - tk 8.6.7 0
        - expat 2.2.5 0
        - jpeg 9b 2
        - setuptools 39.0.1 py36_0
        - libxml2 2.9.8 0
        - pcre 8.41 1
        - nose 1.3.7 py36_2
        - glib 2.55.0 0
        - gettext 0.19.8.1 0
        - icu 58.2 0
        - blas 1.1 openblas
        - pkg-config 0.29.2 1
        - libgfortran 3.0.0 1
        - pyqt 5.6.0 py36_4
        - ca-certificates 2018.1.18 0
        - ncurses 5.9 10
        - numpy 1.8.2 py36_blas_openblas_201
        - six 1.11.0 py36_1
        - pyparsing 2.2.0 py36_0
        - python-dateutil 2.7.2 py_0
        - sqlite 3.20.1 2
    run:
        - python
        - setuptools
        - numpy >=1.8
        - setuptools
        - cycler >=0.10
        - python-dateutil
        - freetype 2.8.*
        - pytz
        - pyparsing
        - libpng >=1.6.32,<1.6.35
        - pyqt 5.6.*
        - tk 8.6.*
        - icu 58.*
        - tornado
        - kiwisolver
test:
    commands:
        - conda inspect linkages -p $PREFIX $PKG_NAME
    imports:
        - matplotlib
        - matplotlib.pyplot
        - matplotlib._image
        - matplotlib._path
        - matplotlib._png
        - matplotlib._tri
        - matplotlib.backends._backend_agg
        - matplotlib.ft2font
        - matplotlib.ttconv
        - matplotlib.backends._tkagg
        - mpl_toolkits
        - pylab
about:
    description: 'matplotlib is a python 2D plotting library which produces publication

        quality figures in a variety of hardcopy formats and interactive

        environments across platforms. matplotlib can be used in Python scripts,

        the Python and IPython shell (ala MATLAB or Mathematica), web

        application servers, and six graphical user interface toolkits.

        '
    dev_url: https://github.com/matplotlib/matplotlib/
    doc_url: http://matplotlib.org/contents.html
    home: http://matplotlib.org/
    license: PSF-based
    license_family: PSF
    license_file: LICENSE/LICENSE
    license_url: http://matplotlib.sourceforge.net/users/license.html
    summary: Publication quality figures in Python
extra:
    final: true
    recipe-maintainers:
        - mdboom
        - ocefpaf
        - pelson
        - tacaswell
        - dopplershift
