# This file created by conda-build 2.1.18
# meta.yaml template originally from:
# /recipe_root, last modified Wed Mar 21 14:47:27 2018
# ------------------------------------------------

package:
    name: dask-core
    version: 0.17.2
source:
    fn: dask-0.17.2.tar.gz
    sha256: 27e470b8cfdd0516189e641b1213fceec0ddc4f37ead1fbce733d3381134fccd
    url: https://pypi.io/packages/source/d/dask/dask-0.17.2.tar.gz
build:
    noarch: python
    noarch_python: false
    number: '0'
    script: python -m pip install --no-deps --ignore-installed .
    string: py_0
requirements:
    build:
        - certifi 2018.1.18 py36_0
        - python 3.6.4 0
        - xz 5.2.3 0
        - openssl 1.0.2n 0
        - pip 9.0.1 py36_1
        - readline 7.0 0
        - zlib 1.2.11 0
        - tk 8.6.7 0
        - setuptools 39.0.1 py36_0
        - ca-certificates 2018.1.18 0
        - ncurses 5.9 10
        - wheel 0.30.0 py36_2
        - sqlite 3.20.1 2
    run:
        - python
test:
    imports:
        - dask
about:
    dev_url: https://github.com/dask/dask
    doc_url: https://dask.pydata.org/
    home: http://github.com/dask/dask/
    license: BSD 3-Clause
    license_file: LICENSE.txt
    summary: Parallel Python with task scheduling
extra:
    final: true
    recipe-maintainers:
        - jakirkham
        - jcrist
        - martindurant
        - mrocklin
        - pitrou
        - shoyer
        - sinhrks
        - tomaugspurger
