# This file created by conda-build 3.12.1
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Aug  7 17:56:58 2018
# ------------------------------------------------

package:
    name: xz
    version: 5.2.4
source:
    patches:
        - 0001-Add-vs2008-support-via-cmake.patch
        - 0002-Add-gettimeofday-for-VS2008.patch
    sha256: 3313fd2a95f43d88e44264e6b015e7d03053e681860b0d5d3f9baca79c57b7bf
    url: http://downloads.sourceforge.net/project/lzmautils/xz-5.2.4.tar.bz2
build:
    number: '1'
    run_exports:
        - xz >=5.2.4,<6.0a0
    string: h470a237_1
requirements:
    build:
        - autoconf 2.69 pl526_7
        - automake 1.15.1 pl526_1
        - libgcc-ng 7.2.0 hdf63c60_3
        - m4 1.4.18 0
        - make 4.2.1 h470a237_0
        - perl 5.26.2 h470a237_0
        - toolchain 2.1.6 0
        - toolchain_c_linux-64 2.1.6 0
    host:
        - libgcc-ng 7.2.0 hdf63c60_3
    run:
        - libgcc-ng >=4.9
test:
    commands:
        - xz --help
        - unxz --help
        - lzma --help
        - conda inspect linkages -p $PREFIX $PKG_NAME
about:
    description: 'XZ Utils is free general-purpose data compression software with
        a high

        compression ratio. XZ Utils were written for POSIX-like systems, but also

        work on some not-so-POSIX systems.

        '
    dev_url: http://git.tukaani.org/
    doc_source_url: https://github.com/xz-mirror/xz/blob/master/README
    doc_url: http://tukaani.org/xz/
    home: http://tukaani.org/xz/
    license: LGPL-2.1 and GPL-2.0
    license_file: COPYING
    summary: Data compression software with high compression ratio
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - mingwandroid
        - msarahan
        - nehaljwani
        - ocefpaf
        - scopatz
