# This file created by conda-build 2.1.18
# meta.yaml template originally from:
# /recipe_root, last modified Sun Mar 18 08:33:10 2018
# ------------------------------------------------

package:
    name: notebook
    version: 5.4.1
source:
    fn: notebook-5.4.1.tar.gz
    sha256: 7d6143d10e9b026df888e0b2936ceff1827ef2f2087646b4dd475c8dcef58606
    url: https://pypi.io/packages/source/n/notebook/notebook-5.4.1.tar.gz
build:
    entry_points:
        - jupyter-notebook = notebook.notebookapp:main
        - jupyter-nbextension = notebook.nbextensions:main
        - jupyter-serverextension = notebook.serverextensions:main
        - jupyter-bundlerextension = notebook.bundler.bundlerextensions:main
    noarch: ''
    noarch_python: false
    number: '0'
    script:
        - pip install --no-deps .
    string: py36_0
requirements:
    build:
        - certifi 2018.1.18 py36_0
        - python 3.6.4 0
        - xz 5.2.3 0
        - openssl 1.0.2n 0
        - pip 9.0.1 py36_1
        - readline 7.0 0
        - zlib 1.2.11 0
        - tk 8.6.7 0
        - ca-certificates 2018.1.18 0
        - setuptools 39.0.0 py36_0
        - ncurses 5.9 10
        - wheel 0.30.0 py36_2
        - sqlite 3.20.1 2
    run:
        - ipykernel
        - ipython_genutils
        - jinja2
        - jupyter_core >=4.4.0
        - jupyter_client >=5.2.0
        - nbconvert
        - nbformat
        - python
        - send2trash
        - terminado >=0.8.1
        - tornado >=4
        - traitlets >=4.2.1
test:
    commands:
        - jupyter notebook -h
        - jupyter nbextension -h
        - jupyter serverextension -h
        - jupyter bundlerextension -h
    imports:
        - notebook
about:
    home: http://jupyter.org
    license: BSD 3-clause
    license_file: COPYING.md
    summary: A web-based notebook environment for interactive computing
extra:
    final: true
    recipe-maintainers:
        - SylvainCorlay
        - jakirkham
        - minrk
        - pelson
        - gnestor
        - takluyver
