# This file created by conda-build 3.12.1
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Thu Aug  9 17:19:07 2018
# ------------------------------------------------

package:
    name: kiwisolver
    version: 1.0.1
source:
    sha256: ce3be5d520b4d2c3e5eeb4cd2ef62b9b9ab8ac6b6fedbaa0e39cdb6f50644278
    url: https://pypi.io/packages/source/k/kiwisolver/kiwisolver-1.0.1.tar.gz
build:
    number: '2'
    script: /home/conda/feedstock_root/build_artifacts/kiwisolver_1533835214282/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/python
        -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
    string: py36h2d50403_2
requirements:
    build:
        - toolchain 2.1.6 0
        - toolchain_cxx_linux-64 2.1.6 0
    host:
        - bzip2 1.0.6 h470a237_2
        - ca-certificates 2018.4.16 0
        - certifi 2018.4.16 py36_0
        - libffi 3.2.1 3
        - libgcc-ng 7.2.0 hdf63c60_3
        - libstdcxx-ng 7.2.0 hdf63c60_3
        - ncurses 6.1 hfc679d8_1
        - openssl 1.0.2o h470a237_1
        - pip 18.0 py36_1
        - python 3.6.6 h5001a0f_0
        - readline 7.0 haf1bffa_1
        - setuptools 40.0.0 py36_1
        - sqlite 3.24.0 h2f33b56_0
        - tk 8.6.8 0
        - wheel 0.31.1 py36_1
        - xz 5.2.4 h470a237_1
        - zlib 1.2.11 h470a237_3
    run:
        - libstdcxx-ng >=4.9
        - python >=3.6,<3.7.0a0
test:
    imports:
        - kiwisolver
about:
    home: https://github.com/nucleic/kiwi
    license: BSD 3-Clause
    license_family: BSD
    license_file: COPYING.txt
    summary: A fast implementation of the Cassowary constraint solver
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - MatthieuDartiailh
        - blink1073
        - ericdill
        - licode
        - sccolbert
        - tacaswell
