# This file created by conda-build 3.13.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Aug 21 18:46:52 2018
# ------------------------------------------------

package:
    name: conda
    version: 4.5.11
source:
    sha256: 99080c5fc43a76ae7dc082943a793a62cb3d4ec66f3986ff0216d22f1594401f
    url: https://github.com/conda/conda/archive/4.5.11.tar.gz
build:
    always_include_files:
        - bin/activate
        - bin/conda
        - bin/deactivate
    entry_points:
        - conda = conda.cli:main
        - conda-env = conda_env.cli.main:main
    number: '0'
    string: py36_0
requirements:
    build:
        - bzip2 1.0.6 h470a237_2
        - ca-certificates 2018.8.13 ha4d7672_0
        - libffi 3.2.1 hfc679d8_4
        - libgcc-ng 7.2.0 hdf63c60_3
        - libstdcxx-ng 7.2.0 hdf63c60_3
        - ncurses 6.1 hfc679d8_1
        - openssl 1.0.2o h470a237_1
        - python 3.6.6 h5001a0f_0
        - readline 7.0 haf1bffa_1
        - sqlite 3.24.0 h2f33b56_0
        - tk 8.6.8 0
        - xz 5.2.4 h470a237_1
        - zlib 1.2.11 h470a237_3
    run:
        - conda-env >=2.6
        - pycosat >=0.6.3
        - pyopenssl >=16.2.0
        - python >=3.6,<3.7.0a0
        - requests >=2.12.4,<3
        - ruamel_yaml >=0.11.14
    run_constrained:
        - conda-build >=2.1
        - cytoolz >=0.8.1
        - setuptools >=31.0.1
test:
    files:
        - test_conda.sh
    imports:
        - conda
about:
    description: 'Conda is an open source package management system and environment

        management system for installing multiple versions of software packages

        and their dependencies and switching easily between them. It works on

        Linux, OS X and Windows, and was created for Python programs but can

        package and distribute any software.

        '
    dev_url: https://github.com/conda/conda
    doc_url: https://conda.io/docs/
    home: https://conda.io
    license: BSD 3-Clause
    license_file: LICENSE.txt
    summary: OS-agnostic, system-level binary package and environment manager.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - kalefranz
        - mbargull
        - mcg1969
        - mingwandroid
        - msarahan
        - mwcraig
        - ocefpaf
        - patricksnape
        - pelson
        - scopatz
