# This file created by conda-build 2.1.17
# meta.yaml template originally from:
# /recipe_root, last modified Wed Nov 15 14:54:07 2017
# ------------------------------------------------

package:
    name: numpy
    version: 1.13.3
source:
    sha256: 4c6b4eef790528bebb7ec9590d74cc193868940fe68e4109a91c196df72d8094
    url: https://github.com/numpy/numpy/releases/download/v1.13.3/numpy-1.13.3.tar.gz
build:
    features:
        - blas_openblas
    noarch: ''
    noarch_python: false
    number: '201'
    string: py36_blas_openblas_201
requirements:
    build:
        - ncurses 5.9 10
        - readline 6.2 0
        - tk 8.5.19 2
        - ca-certificates 2017.7.27.1 0
        - libgfortran 3.0.0 1
        - setuptools 36.6.0 py36_1
        - blas 1.1 openblas
        - zlib 1.2.11 0
        - xz 5.2.3 0
        - certifi 2017.7.27.1 py36_0
        - toolchain 2.1.2 0
        - sqlite 3.13.0 1
        - openssl 1.0.2l 0
        - python 3.6.3 1
        - cython 0.27.3 py36_0
        - openblas 0.2.20 4
    run:
        - python
        - blas 1.1 openblas
        - openblas 0.2.20|0.2.20.*
test:
    commands:
        - f2py -h
        - conda inspect linkages -p $PREFIX numpy
    imports:
        - numpy
        - numpy.linalg.lapack_lite
    requires:
        - nose
about:
    home: http://numpy.scipy.org/
    license: BSD 3-Clause
    license_file: LICENSE.txt
    summary: Array processing for numbers, strings, records, and objects.
extra:
    final: true
    recipe-maintainers:
        - jakirkham
        - msarahan
        - pelson
        - rgommers
        - ocefpaf
