# This file created by conda-build 2.1.18
# meta.yaml template originally from:
# /recipe_root, last modified Thu Dec  7 14:07:39 2017
# ------------------------------------------------

package:
    name: qt
    version: 5.6.2
source:
    patches:
        - 0005-Remove-unused-include-sys-signalfd.h.patch
        - 0006-zlib_dependency-Add-EXTRA_INCLUDEPATH-for-system-zli.patch
        - 0007-CentOS5-Do-not-use-strict_c-when-using-c-11.patch
        - 0008-disable-Ubuntu-overlay-scrollbars-as-they-don-t-play.patch
    sha256: 7551f5af1312082c3c8ab52f5e102e3f83aae2dd96dc4a3a9a197f3e58b3214c
    url: http://download.qt.io/official_releases/qt/5.6/5.6.2/single/qt-everywhere-opensource-src-5.6.2.tar.gz
build:
    detect_binary_files_with_prefix: 'true'
    features: ''
    noarch: ''
    noarch_python: false
    number: '7'
    string: '7'
requirements:
    build:
        - freetype 2.8.1 0
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - gst-plugins-base 1.8.0 0
        - ncurses 6.0 h9df7e31_2
        - gettext 0.19.7 1
        - libpng 1.6.34 0
        - xz 5.2.3 0
        - ca-certificates 2017.11.5 0
        - bison 3.0.4 1
        - libxcb 1.12 1
        - xorg-libxdmcp 1.1.2 3
        - gstreamer 1.8.0 1
        - zlib 1.2.11 0
        - libgcc-ng 7.2.0 h7cc24e2_2
        - fontconfig 2.12.6 0
        - readline 7.0 ha6073c6_4
        - dbus 1.10.22 0
        - libiconv 1.15 0
        - libxml2 2.9.5 2
        - xorg-libxau 1.0.8 3
        - libffi 3.2.1 3
        - tk 8.6.7 0
        - expat 2.2.5 0
        - jpeg 9b 2
        - python 2.7.14 h91f54f5_26
        - pcre 8.39 0
        - glib 2.55.0 0
        - sqlite 3.20.1 0
        - perl 5.22.2.1 0
        - icu 58.2 0
        - gperf 3.0.4 0
        - flex 2.6.3 2
        - m4 1.4.17 1
        - openssl 1.0.2m 0
    run:
        - freetype 2.8.1
        - fontconfig 2.12.*
        - openssl 1.0.*
        - jpeg 9*
        - zlib 1.2.11
        - libpng >=1.6.32,<1.6.35
        - gst-plugins-base
        - icu 58.*
        - sqlite 3.20.*
        - libxcb
        - dbus
test:
    commands:
        - test -f $PREFIX/lib/libQt5WebKit.so
        - test -f $PREFIX/plugins/sqldrivers/libqsqlite${SHLIB_EXT}
        - conda inspect linkages -p $PREFIX $PKG_NAME
    files:
        - test/hello.pro
        - test/main.cpp
about:
    description: 'Qt helps you create connected devices, UIs & applications that run

        anywhere on any device, on any operating system at any time.

        '
    dev_url: https://github.com/qtproject
    doc_url: http://doc.qt.io/
    home: http://qt-project.org
    license: LGPL-3.0
    summary: Qt is a cross-platform application and UI framework.
extra:
    final: true
    recipe-maintainers:
        - ccordoba12
        - mingwandroid
        - gillins
        - msarahan
        - ocefpaf
        - stuarteberg
