# This file created by conda-build 2.1.17
# meta.yaml template originally from:
# /recipe_root, last modified Wed Sep  6 13:31:13 2017
# ------------------------------------------------

package:
    name: pyshp
    version: 1.2.12
source:
    sha256: 8dcd65e0aa2aa2951527ddb7339ea6e69023543d8a20a73fc51e2829b9ed6179
    url: https://pypi.io/packages/source/p/pyshp/pyshp-1.2.12.tar.gz
build:
    noarch: python
    noarch_python: false
    number: '0'
    script: python setup.py install --single-version-externally-managed --record record.txt
    string: py_0
requirements:
    build:
        - ncurses 5.9 10
        - readline 6.2 0
        - tk 8.5.19 2
        - ca-certificates 2017.7.27.1 0
        - setuptools 36.3.0 py36_0
        - zlib 1.2.11 0
        - xz 5.2.3 0
        - certifi 2017.7.27.1 py36_0
        - python 3.6.2 0
        - sqlite 3.13.0 1
        - openssl 1.0.2l 0
    run:
        - python
test:
    imports:
        - shapefile
about:
    home: https://pypi.python.org/pypi/pyshp
    license: MIT
    license_file: LICENSE.TXT
    summary: Pure Python read/write support for ESRI Shapefile format.
extra:
    final: true
    recipe-maintainers:
        - pelson
        - ocefpaf
