# This file created by conda-build 3.0.15+148.g91b57bf
# meta.yaml template originally from:
# /home/rdonnelly/conda/aggregate/pycosat-feedstock/recipe, last modified Mon Oct 30 09:19:50 2017
# ------------------------------------------------

package:
    name: pycosat
    version: 0.6.3
source:
    git_rev: 0.6.3
    git_url: https://github.com/mingwandroid/pycosat.git
build:
    number: '0'
    string: py36h0a5515d_0
requirements:
    build:
        - binutils_impl_linux-64 2.28.1 h04c84fa_2
        - binutils_linux-64 7.2.0 hc67e822_7
        - ca-certificates 2017.08.26 h1d4fec5_0
        - gcc_impl_linux-64 7.2.0 hc5ce805_2
        - gcc_linux-64 7.2.0 h22f992b_7
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 h4deb6c0_3
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - ncurses 6.0 h06874d7_1
        - openssl 1.0.2l h077ae2c_5
        - python 3.6.3 hefd0734_2
        - readline 7.0 hac23ff0_3
        - sqlite 3.20.1 h6d8b0f3_1
        - tk 8.6.7 h5979e9b_1
        - xz 5.2.3 h2bcbf08_1
        - zlib 1.2.11 hfbfcf68_1
    host:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 h4deb6c0_3
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - ncurses 6.0 h06874d7_1
        - openssl 1.0.2l h077ae2c_5
        - python 3.6.3 hefd0734_2
        - readline 7.0 hac23ff0_3
        - sqlite 3.20.1 h6d8b0f3_1
        - tk 8.6.7 h5979e9b_1
        - xz 5.2.3 h2bcbf08_1
        - zlib 1.2.11 hfbfcf68_1
    run:
        - libgcc-ng 7.2.0.*
        - python >=3.6,<3.7.0a0
test:
    files:
        - qg3-08.cnf
        - sudoku.py
        - uf20-098.cnf
    imports:
        - pycosat
about:
    description: 'PicoSAT is a popular SAT solver written by Armin Biere in pure C.
        This

        package provides efficient Python bindings to picosat on the C level, i.e.

        when importing pycosat, the picosat solver becomes part of the Python

        process itself.

        '
    dev_url: https://github.com/ContinuumIO/pycosat
    doc_source_url: https://github.com/ContinuumIO/pycosat/blob/master/README.rst
    doc_url: https://pypi.python.org/pypi/pycosat
    home: https://github.com/ContinuumIO/pycosat
    license: MIT
    summary: Bindings to picosat (a SAT solver)
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - kalefranz
        - mcg1969
        - mingwandroid
        - msarahan
        - nehaljwani
        - pelson
