# This file created by conda-build 2.1.18
# meta.yaml template originally from:
# /recipe_root, last modified Thu Jul 19 12:41:22 2018
# ------------------------------------------------

package:
    name: tk
    version: 8.6.8
build:
    detect_binary_files_with_prefix: 'true'
    features: ''
    noarch: ''
    noarch_python: false
    number: '0'
    string: '0'
requirements:
    build: []
    run: ''
test:
    commands:
        - test -f "${PREFIX}/bin/tclsh"
        - test -f "${PREFIX}/bin/wish"
        - test -f "${PREFIX}/bin/tclsh8.6"
        - test -f "${PREFIX}/bin/wish8.6"
        - test -f "${PREFIX}/include/tcl.h"
        - test -f "${PREFIX}/include/tclDecls.h"
        - test -f "${PREFIX}/include/tclPlatDecls.h"
        - test -f "${PREFIX}/include/tclPlatDecls.h"
        - test -f "${PREFIX}/include/tclTomMathDecls.h"
        - test -f "${PREFIX}/include/tclTomMath.h"
        - test -f "${PREFIX}/include/tk.h"
        - test -f "${PREFIX}/include/tkDecls.h"
        - test -f "${PREFIX}/include/tkPlatDecls.h"
        - test -f "${PREFIX}/lib/libtcl8.6.so"
        - test -f "${PREFIX}/lib/libtclstub8.6.a"
        - test -f "${PREFIX}/lib/libtk8.6.so"
        - test -f "${PREFIX}/lib/libtkstub8.6.a"
        - tclsh hello.tcl
        - tclsh8.6 hello.tcl
        - wish hello.tcl
        - wish8.6 hello.tcl
    files:
        - hello.tcl
about:
    home: http://www.tcl.tk/
    license: Tcl/Tk
    license_family: BSD
    summary: A dynamic programming language with GUI support.  Bundles Tcl and Tk.
extra:
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - msarahan
        - pelson
        - ocefpaf
