# This file created by conda-build 2.1.18
# meta.yaml template originally from:
# /recipe_root, last modified Mon Dec 18 05:11:43 2017
# ------------------------------------------------

package:
    name: fastcluster
    version: 1.1.24
source:
    fn: fastcluster-1.1.24.tar.gz
    sha256: a5d1922b1db6f4c3012416e7dc14de2984b9335a48c895e1698afd5c718312b0
    url: https://pypi.io/packages/source/f/fastcluster/fastcluster-1.1.24.tar.gz
build:
    noarch: ''
    noarch_python: false
    number: '0'
    script: python setup.py install --single-version-externally-managed --record record.txt
    string: py36_0
requirements:
    build:
        - xz 5.2.3 0
        - ca-certificates 2017.11.5 0
        - openssl 1.0.2n 0
        - readline 7.0 0
        - openblas 0.2.20 6
        - zlib 1.2.11 0
        - certifi 2017.11.5 py36_0
        - tk 8.6.7 0
        - python 3.6.3 4
        - sqlite 3.20.1 0
        - setuptools 38.2.4 py36_0
        - blas 1.1 openblas
        - libgfortran 3.0.0 1
        - ncurses 5.9 10
        - numpy 1.8.2 py36_blas_openblas_201
        - toolchain 2.1.2 0
    run:
        - python
        - numpy >=1.9
test:
    imports:
        - fastcluster
about:
    description: "This library provides Python functions for hierarchical clustering.\
        \ It generates hierarchical\nclusters from distance matrices or from vector\
        \ data.\n\nPart of this module is intended to replace the functions\nlinkage,\
        \ single, complete, average, weighted, centroid, median, ward\nin the module\
        \ scipy.cluster.hierarchy with the same functionality but much faster algorithms.\n\
        Moreover, the function linkage_vector provides memory-efficient clustering\
        \ for vector data.\n\nThe interface is very similar to MATLAB\u2019s Statistics\
        \ Toolbox API to make code easier to\nport from MATLAB to Python/NumPy. The\
        \ core implementation of this library is in C++ for efficiency.\n"
    dev_url: https://github.com/dmuellner/fastcluster
    doc_url: https://github.com/dmuellner/fastcluster/raw/master/docs/fastcluster.pdf
    home: http://danifold.net/fastcluster.html
    license: BSD-2-Clause
    license_file: COPYING.txt
    summary: Fast hierarchical clustering routines for R and Python.
extra:
    final: true
    recipe-maintainers:
        - mpharrigan
