# This file created by conda-build 3.10.2
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/libedit-3.1.20170329-on-linux_64, last modified Thu May 10 00:49:08 2018
# ------------------------------------------------

package:
    name: libedit
    version: 3.1.20170329
source:
    fn: libedit-20170329-3.1.tar.gz
    patches:
        - 0001-Also-look-in-libtinfo-for-tgetent.patch
    sha256: 91f2d90fbd2a048ff6dad7131d9a39e690fd8a8fd982a353f1333dd4017dd4be
    url: http://thrysoee.dk/editline/libedit-20170329-3.1.tar.gz
build:
    number: '2'
    run_exports:
        - libedit >=3.1.20170329,<3.2.0a0
    string: h6b74fdf_2
requirements:
    build:
        - autoconf 2.69 pl526hebd4dad_5
        - automake 1.15.1 pl526h7747ae0_0
        - binutils_impl_linux-64 2.28.1 had2808c_3
        - binutils_linux-64 7.2.0 26
        - gcc_impl_linux-64 7.2.0 habb00fd_3
        - gcc_linux-64 7.2.0 26
        - libgcc-ng 7.2.0 hdf63c60_3
        - libstdcxx-ng 7.2.0 hdf63c60_3
        - m4 1.4.18 h4e445db_0
        - make 4.2.1 h1bed415_1
        - perl 5.26.0 hae598fd_0
    host:
        - libgcc-ng 7.2.0 hdf63c60_3
        - libstdcxx-ng 7.2.0 hdf63c60_3
        - ncurses 6.1 hf484d3e_0
    run:
        - libgcc-ng >=7.2.0
        - ncurses >=6.1,<7.0a0
test:
    commands:
        - test -f $PREFIX/lib/libedit.so
    downstreams:
        - krb5
        - sqlite
about:
    description: 'This is an autotool- and libtoolized port of the NetBSD Editline
        library

        (libedit). This Berkeley-style licensed command line editor library provides

        generic line editing, history, and tokenization functions, similar to those

        found in GNU Readline

        '
    home: http://thrysoee.dk/editline/
    license: NetBSD
    license_family: BSD
    license_file: COPYING
    summary: Editline Library (libedit)
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - dougalsutherland
        - mingwandroid
        - scopatz
