# This file created by conda-build 3.13.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Aug 28 00:10:49 2018
# ------------------------------------------------

package:
    name: jsonschema
    version: 2.6.0
source:
    sha256: 6ff5f3180870836cae40f06fa10419f557208175f13ad7bc26caa77beb1f6e02
    url: https://pypi.io/packages/source/j/jsonschema/jsonschema-2.6.0.tar.gz
build:
    entry_points:
        - jsonschema = jsonschema.cli:main
    number: '2'
    script: /home/conda/feedstock_root/build_artifacts/jsonschema_1535415153208/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/python
        -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
    string: py36_2
requirements:
    host:
        - bzip2 1.0.6 h470a237_2
        - ca-certificates 2018.8.24 ha4d7672_0
        - certifi 2018.8.24 py36_1
        - libffi 3.2.1 hfc679d8_4
        - libgcc-ng 7.2.0 hdf63c60_3
        - libstdcxx-ng 7.2.0 hdf63c60_3
        - ncurses 6.1 hfc679d8_1
        - openssl 1.0.2o h470a237_1
        - pip 18.0 py36_1
        - python 3.6.6 h5001a0f_0
        - readline 7.0 haf1bffa_1
        - setuptools 40.2.0 py36_0
        - sqlite 3.24.0 h2f33b56_0
        - tk 8.6.8 0
        - vcversioner 2.16.0.0 py_1
        - wheel 0.31.1 py36_1
        - xz 5.2.4 h470a237_1
        - zlib 1.2.11 h470a237_3
    run:
        - python >=3.6,<3.7.0a0
test:
    commands:
        - jsonschema --help
    imports:
        - jsonschema
about:
    description: 'jsonschema is an implementation of JSON Schema for Python

        (supporting 2.7+ including Python 3)

        '
    dev_url: https://github.com/Julian/jsonschema/
    doc_source_url: https://github.com/Julian/jsonschema/blob/master/docs/index.rst
    doc_url: https://python-jsonschema.readthedocs.org
    home: https://github.com/Julian/jsonschema
    license: MIT
    license_file: COPYING
    summary: An implementation of JSON Schema validation for Python
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - minrk
        - nehaljwani
        - ocefpaf
